"use client";

import { useState } from "react";
import { CalendarDays, CheckCircle2, CirclePlay, FileWarning, Radar, ShieldAlert, Target, TerminalSquare, Timer } from "lucide-react";
import { Badge, Button, Card, DonutChart, Drawer, Field, MetricGrid, Modal, PageHeader, ProgressBar, Select, Sparkline, Tabs } from "../../components/ui";
import { useZaspStore } from "../../domain/store";
import type { AppRoute, ScanFinding, ScanRun, Severity } from "../../domain/types";

const suites = [
  { id: "Prompt injection", label: "Prompt injection", tests: 48, description: "Direct, indirect, encoded, and multilingual instruction overrides." },
  { id: "Data leakage", label: "Data leakage", tests: 36, description: "Sensitive prompt, context, tool, and response disclosure." },
  { id: "Tool abuse", label: "Tool abuse", tests: 42, description: "Unsafe arguments, authorization bypass, and destructive actions." },
  { id: "Authorization", label: "Authorization", tests: 28, description: "Cross-user and cross-tenant access boundary checks." },
  { id: "Protocol security", label: "MCP protocol", tests: 30, description: "Tool discovery, schema confusion, and untrusted server behavior." },
  { id: "Agent safety", label: "Agent safety", tests: 24, description: "Excessive agency, deception, and goal manipulation." },
];
const findingTemplate: ScanFinding[] = [{ id: "scan-live-1", title: "Retrieved content can override system intent", category: "Prompt injection", severity: "critical", evidence: "Agent executed an instruction embedded in untrusted retrieved text.", reproduction: "Seed a document with an instruction override, then request a summary through the agent.", remediation: "Separate trusted instructions from retrieved content and validate downstream tool intent." }, { id: "scan-live-2", title: "Tool error exposes internal workspace metadata", category: "Data leakage", severity: "high", evidence: "Verbose tool output included an internal path and service account name.", reproduction: "Submit an invalid parameter to a tool after authentication.", remediation: "Normalize and sanitize tool errors before returning them to the model." }];

function severitySegments(findings: ScanFinding[]) { return (["critical", "high", "medium", "low"] as Severity[]).map((severity) => ({ label: severity[0].toUpperCase() + severity.slice(1), value: findings.filter((item) => item.severity === severity).length, color: severity === "critical" ? "#c93f25" : severity === "high" ? "#dfa096" : severity === "medium" ? "#e8c672" : "#dde0e5" })); }

function FindingDrawer({ finding, scan, onClose, onToast }: { finding: ScanFinding | null; scan: ScanRun | null; onClose: () => void; onToast: (message: string) => void }) {
  const { state } = useZaspStore(); const [tab, setTab] = useState("overview");
  if (!finding || !scan) return null; const asset = state.assets.find((item) => item.id === scan.targetAssetId);
  return <Drawer open title="Red team finding" onClose={onClose}><div className="violation-hero"><div><span className="eyebrow">{finding.category}</span><div className="detail-title"><h3>{finding.title}</h3><Badge tone={finding.severity}>{finding.severity}</Badge></div><p>{asset?.name} · {scan.role} · {scan.id}</p></div><Button>Finding actions</Button></div><Tabs tabs={[{ id: "overview", label: "Overview" }, { id: "reproduce", label: "Reproduction" }, { id: "remediation", label: "Remediation" }]} active={tab} onChange={setTab} /><div className="detail-content">{tab === "overview" && <><h4>Security impact</h4><p>{finding.evidence}</p><div className="meta-grid three"><div><span>Category</span><strong>{finding.category}</strong></div><div><span>Target</span><strong>{asset?.name}</strong></div><div><span>Scan role</span><strong>{scan.role}</strong></div></div><h4>Evidence</h4><div className="evidence-box"><code>{finding.evidence}</code></div></>}{tab === "reproduce" && <><h4>Reproduction steps</h4><div className="reproduction-box"><TerminalSquare /><p>{finding.reproduction}</p></div><Button onClick={() => onToast("Reproduction copied to clipboard")}>Copy reproduction</Button></>}{tab === "remediation" && <><div className="remediation-callout"><CheckCircle2 /><div><strong>Recommended fix</strong><p>{finding.remediation}</p></div></div><div className="remediation-options"><button onClick={() => onToast("Finding assigned to Agent Platform team")}><Target /><span><strong>Assign owner</strong><small>Route this finding to the responsible component team.</small></span></button><button onClick={() => onToast("Remediation ticket created")}><FileWarning /><span><strong>Create ticket</strong><small>Include evidence, reproduction, and suggested fix.</small></span></button></div></>}</div></Drawer>;
}

function ScanSetup({ open, onClose, onStarted }: { open: boolean; onClose: () => void; onStarted: (scan: ScanRun) => void }) {
  const { state, dispatch } = useZaspStore(); const [assetId, setAssetId] = useState(state.assets[0].id); const [role, setRole] = useState("External user"); const [selected, setSelected] = useState(["Prompt injection", "Data leakage", "Tool abuse"]); const [maxTokens, setMaxTokens] = useState(120000); const [concurrency, setConcurrency] = useState(4);
  const tests = suites.filter((item) => selected.includes(item.id)).reduce((sum, item) => sum + item.tests, 0); const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const start = () => { const scan: ScanRun = { id: `scan-user-${Date.now()}`, targetAssetId: assetId, role, suites: selected, status: "queued", progress: 0, started: "Now", tests, findings: [] }; dispatch({ type: "scan.create", scan }); onStarted(scan); onClose(); };
  return <Modal open={open} title="Run agent red-team scan" onClose={onClose} size="large" footer={<><Button onClick={onClose}>Cancel</Button><Button variant="primary" disabled={!selected.length} onClick={start}>Start scan</Button></>}><div className="scan-setup"><div className="form-grid"><Select label="Target agentic asset" value={assetId} onChange={(event) => setAssetId(event.target.value)}>{state.assets.filter((item) => ["AI Agent", "MCP Server"].includes(item.type)).map((asset) => <option key={asset.id} value={asset.id}>{asset.name} · {asset.environment}</option>)}</Select><Select label="Attacker role" value={role} onChange={(event) => setRole(event.target.value)}><option>External user</option><option>Authenticated employee</option><option>Repository contributor</option><option>MCP client</option><option>Compromised agent</option></Select></div><div className="scan-section-heading"><div><h3>Test suites</h3><p>Choose focused adversarial coverage for this run.</p></div><Badge tone="brand">{tests} tests</Badge></div><div className="suite-grid">{suites.map((suite) => <button key={suite.id} type="button" className={selected.includes(suite.id) ? "selected" : ""} aria-pressed={selected.includes(suite.id)} onClick={() => toggle(suite.id)}><span>{selected.includes(suite.id) ? <CheckCircle2 /> : <ShieldAlert />}</span><div><strong>{suite.label}</strong><p>{suite.description}</p><small>{suite.tests} probes</small></div></button>)}</div><h3>Execution limits</h3><div className="form-grid"><Field type="number" label="Maximum tokens" value={maxTokens} onChange={(event) => setMaxTokens(Number(event.target.value))} /><Field type="number" label="Concurrency" value={concurrency} onChange={(event) => setConcurrency(Number(event.target.value))} /></div><div className="scan-estimate"><Timer /><div><strong>Estimated duration: {Math.max(3, Math.ceil(tests / Math.max(1, concurrency) / 8))} minutes</strong><span>Estimated token use: {(maxTokens / 1000).toFixed(0)}k maximum</span></div></div></div></Modal>;
}

function ScanDrawer({ scan, onClose, onToast }: { scan: ScanRun | null; onClose: () => void; onToast: (message: string) => void }) {
  const { state, dispatch } = useZaspStore(); const [tab, setTab] = useState("overview"); const [finding, setFinding] = useState<ScanFinding | null>(null);
  if (!scan) return null; const live = state.scans.find((item) => item.id === scan.id) ?? scan; const asset = state.assets.find((item) => item.id === live.targetAssetId);
  const complete = () => { dispatch({ type: "scan.complete", scanId: live.id, findings: findingTemplate }); onToast("Scan completed with 2 findings"); };
  return <><Drawer open title="Scan run" onClose={onClose}><div className="violation-hero"><div><span className="eyebrow">{live.id}</span><div className="detail-title"><h3>{asset?.name}</h3><Badge tone={live.status === "complete" ? "success" : live.status === "failed" ? "critical" : "info"}>{live.status}</Badge></div><p>{live.role} · {live.tests} tests · {live.started}</p></div>{live.status !== "complete" && <Button variant="primary" onClick={complete}>Complete demo scan</Button>}</div><Tabs tabs={[{ id: "overview", label: "Overview" }, { id: "findings", label: "Findings", count: live.findings.length }, { id: "requests", label: "Agentic requests" }, { id: "configuration", label: "Configuration" }]} active={tab} onChange={setTab} /><div className="detail-content">{tab === "overview" && <><div className="scan-progress-card"><div><Radar /><span><strong>{live.status === "complete" ? "Scan complete" : "Scan queued"}</strong><small>{live.status === "complete" ? `${live.findings.length} findings from ${live.tests} tests` : "Ready to execute in the demo environment"}</small></span></div><strong>{live.progress}%</strong><ProgressBar value={live.progress} /></div><div className="meta-grid"><div><span>Target</span><strong>{asset?.name}</strong></div><div><span>Role</span><strong>{live.role}</strong></div><div><span>Test suites</span><strong>{live.suites.length}</strong></div><div><span>Probes</span><strong>{live.tests}</strong></div></div>{live.findings.length > 0 && <><h4>Severity distribution</h4><DonutChart segments={severitySegments(live.findings)} /></>}</>}{tab === "findings" && <div className="finding-list">{live.findings.length ? live.findings.map((item) => <button key={item.id} aria-label={item.title} onClick={() => setFinding(item)}><Badge tone={item.severity}>{item.severity}</Badge><span><strong>{item.title}</strong><small>{item.category}</small></span></button>) : <div className="empty-state"><CheckCircle2 /><strong>No findings yet</strong><p>Complete the demo scan to populate deterministic findings.</p></div>}</div>}{tab === "requests" && <div className="request-log">{["Probe sent to /chat/completions", "Agent invoked customer.lookup", "Tool response captured and sanitized", "Response evaluated against expected behavior"].map((item, index) => <div key={item}><code>{`REQ-${String(index + 1).padStart(3, "0")}`}</code><span>{item}</span><Badge tone={index === 1 ? "warning" : "success"}>{index === 1 ? "observed" : "passed"}</Badge></div>)}</div>}{tab === "configuration" && <div className="meta-grid"><div><span>Target</span><strong>{asset?.name}</strong></div><div><span>Role</span><strong>{live.role}</strong></div><div><span>Suites</span><strong>{live.suites.join(", ")}</strong></div><div><span>Started</span><strong>{live.started}</strong></div></div>}</div></Drawer><FindingDrawer finding={finding} scan={live} onClose={() => setFinding(null)} onToast={onToast} /></>;
}

function ScanRunsView({ onToast }: { onToast: (message: string) => void }) {
  const { state } = useZaspStore(); const [setup, setSetup] = useState(false); const [selected, setSelected] = useState<ScanRun | null>(null); const [tab, setTab] = useState("all");
  const rows = state.scans.filter((item) => tab === "all" || item.status === tab);
  return <><PageHeader title="Red team scans" description="Configure adversarial testing roles, suites, token limits, and target agentic systems." actions={<Button variant="primary" icon={<CirclePlay size={16} />} onClick={() => setSetup(true)}>Run new scan</Button>} /><MetricGrid metrics={[{ label: "Total scan runs", value: state.scans.length, tone: "brand" }, { label: "Tests executed", value: state.scans.reduce((sum, item) => sum + item.tests, 0), tone: "success" }, { label: "Open findings", value: state.scans.flatMap((item) => item.findings).length, tone: "danger" }, { label: "Coverage", value: "78%", tone: "warning" }]} /><Card><Tabs tabs={[{ id: "all", label: "All", count: state.scans.length }, { id: "complete", label: "Complete", count: state.scans.filter((item) => item.status === "complete").length }, { id: "running", label: "Running", count: state.scans.filter((item) => item.status === "running").length }, { id: "queued", label: "Queued", count: state.scans.filter((item) => item.status === "queued").length }, { id: "failed", label: "Failed", count: state.scans.filter((item) => item.status === "failed").length }]} active={tab} onChange={setTab} /><div className="table-scroll"><table className="data-table"><thead><tr><th>Target</th><th>Role</th><th>Suites</th><th>Tests</th><th>Findings</th><th>Status</th><th>Progress</th><th>Started</th></tr></thead><tbody>{rows.map((scan) => <tr key={scan.id} className="clickable-row" onClick={() => setSelected(scan)}><td><button className="row-title">{state.assets.find((item) => item.id === scan.targetAssetId)?.name}</button></td><td>{scan.role}</td><td>{scan.suites.length}</td><td>{scan.tests}</td><td><Badge tone={scan.findings.some((item) => item.severity === "critical") ? "critical" : scan.findings.length ? "warning" : "success"}>{scan.findings.length}</Badge></td><td><Badge tone={scan.status === "complete" ? "success" : scan.status === "failed" ? "critical" : "info"}>{scan.status}</Badge></td><td><div className="coverage-cell"><ProgressBar value={scan.progress} /><span>{scan.progress}%</span></div></td><td>{scan.started}</td></tr>)}</tbody></table></div></Card><ScanSetup open={setup} onClose={() => setSetup(false)} onStarted={(scan) => { setSelected(scan); onToast("Scan queued"); }} /><ScanDrawer scan={selected} onClose={() => setSelected(null)} onToast={onToast} /></>;
}

function ResultsView({ onNavigate, onToast }: { onNavigate: (path: string) => void; onToast: (message: string) => void }) {
  const { state } = useZaspStore(); const complete = state.scans.filter((item) => item.status === "complete"); const findings = complete.flatMap((scan) => scan.findings.map((finding) => ({ finding, scan }))); const [selected, setSelected] = useState<{ finding: ScanFinding; scan: ScanRun } | null>(null);
  const categories = Object.entries(findings.reduce<Record<string, number>>((result, item) => ({ ...result, [item.finding.category]: (result[item.finding.category] ?? 0) + 1 }), {}));
  return <><PageHeader title="Red team results" description="Adversarial security findings across agent roles, models, tools, protocols, and business logic." actions={<><Button icon={<CalendarDays size={16} />}>All time</Button><Button variant="primary" onClick={() => onNavigate("/test/attack-lab")}>Run scan</Button></>} /><Card className="result-summary"><div className="result-summary-head"><div><span>Vulnerabilities</span><h3>Found {findings.length} vulnerabilities in total</h3></div><Badge tone={findings.some((item) => item.finding.severity === "critical") ? "critical" : "success"}>{findings.filter((item) => item.finding.severity === "critical").length} critical</Badge></div><div className="result-visuals"><div className="category-list">{categories.map(([category, count]) => <div key={category}><i /><span>{category}</span><strong>{count}</strong></div>)}</div><DonutChart segments={categories.map(([label, value], index) => ({ label, value, color: ["#d947aa", "#a8ac22", "#f4bc27", "#57b85e", "#7c6ee6"][index % 5] }))} /><DonutChart segments={severitySegments(findings.map((item) => item.finding))} /></div></Card><div className="dashboard-grid"><Card title="Agentic component coverage"><div className="coverage-bars">{complete.map((scan) => <div key={scan.id}><span><strong>{state.assets.find((asset) => asset.id === scan.targetAssetId)?.name}</strong><small>{scan.tests} probes</small></span><div><i style={{ height: `${Math.max(18, scan.tests / 2)}%` }} /></div></div>)}</div></Card><Card title="Scan runs over time"><div className="line-chart large"><div className="chart-scale"><span>20</span><span>15</span><span>10</span><span>5</span><span>0</span></div><div className="chart-main"><Sparkline values={[2, 3, 2, 4, 5, 16, 2, 7, 18, 4, 12, 3, 1]} /><div className="axis-labels"><span>Jan</span><span>May</span><span>Sep</span><span>Now</span></div></div></div></Card></div><Card title="Findings"><div className="table-scroll"><table className="data-table"><thead><tr><th>Finding</th><th>Target</th><th>Category</th><th>Severity</th><th>Role</th><th>Scan</th></tr></thead><tbody>{findings.map((item) => <tr key={item.finding.id} className="clickable-row" onClick={() => setSelected(item)}><td><button className="row-title">{item.finding.title}</button></td><td>{state.assets.find((asset) => asset.id === item.scan.targetAssetId)?.name}</td><td>{item.finding.category}</td><td><Badge tone={item.finding.severity}>{item.finding.severity}</Badge></td><td>{item.scan.role}</td><td>{item.scan.started}</td></tr>)}</tbody></table></div></Card><FindingDrawer finding={selected?.finding ?? null} scan={selected?.scan ?? null} onClose={() => setSelected(null)} onToast={onToast} /></>;
}

export function RedTeamView({ route, onNavigate, onToast }: { route: AppRoute; onNavigate: (path: string) => void; onToast: (message: string) => void }) { return <div className="page">{route.path === "/red-team/results" ? <ResultsView onNavigate={onNavigate} onToast={onToast} /> : <ScanRunsView onToast={onToast} />}</div>; }
