tetragon:
  export:
    mode: ""
  exportDirectory: /var/run/cilium/tetragon
  hostNetwork: true
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 1 }
  tetragon:
    image:
      override: quay.io/cilium/tetragon:v1.7.0@sha256:deda51c3f88e4d26b4d76c99ea207f2b05f9e40c210e0f04a37ca632ab7bf527
    enablePolicyFilter: true
    enableProcessCred: true
    enableProcessNs: true
    clusterName: zasp-runtime
    exportFilename: tetragon.log
    exportFilePerm: "644"
    exportAllowList: '{"event_set":["PROCESS_EXEC","PROCESS_EXIT","PROCESS_KPROBE"]}'
    exportDenyList: |-
      {"health_check":true}
      {"namespace":["","cilium","kube-system"]}
    fieldFilters: '{"fields":"process.arguments,parent.arguments,ancestors.arguments,process.cwd,parent.cwd,ancestors.cwd","action":"EXCLUDE"}'
    exportFileCompress: false
    exportFileMaxBackups: 4
    exportFileMaxSizeMB: 32
    resources:
      requests: { cpu: 100m, memory: 256Mi }
      limits: { cpu: "1", memory: 1Gi }
    prometheus:
      metricsLabelFilter: namespace,workload
  tetragonOperator:
    enabled: false
    image:
      override: quay.io/cilium/tetragon-operator:v1.7.0@sha256:074ffbd19208eed79f68e191ed606e05009f910b4bb5148efcf2973e13504b82
    tracingPolicy:
      enabled: true
  crds:
    installMethod: helm
