"use client";

import { useState } from "react";
import { CheckCircle2, Cloud, ExternalLink, Filter, PlugZap, RefreshCcw, ShieldCheck, Unplug } from "lucide-react";
import { Badge, Button, Card, Field, MetricGrid, Modal, PageHeader, SearchBox, Tabs } from "../../components/ui";
import { useZaspStore } from "../../domain/store";
import type { Connector } from "../../domain/types";

function ConnectorSetup({ connector, onClose, onToast }: { connector: Connector | null; onClose: () => void; onToast: (message: string) => void }) {
  const { dispatch } = useZaspStore(); const [values, setValues] = useState<Record<string, string>>({}); const [step, setStep] = useState<"configure" | "test" | "success">("configure"); const [error, setError] = useState("");
  if (!connector) return null;
  const validate = () => { const missing = connector.fields.find((field) => !values[field.key]?.trim()); if (missing) { setError(`${missing.label} is required`); return false; } setError(""); return true; };
  const test = () => { if (validate()) setStep("test"); };
  const connect = () => { if (!validate()) return; dispatch({ type: "connector.connect", connectorId: connector.id }); setStep("success"); onToast(`${connector.name} connected`); };
  return <Modal open title={`Connect ${connector.name}`} onClose={onClose} size="large" footer={step !== "success" ? <><Button onClick={onClose}>Cancel</Button><Button onClick={test}>Test connection</Button><Button variant="primary" onClick={connect}>Connect now</Button></> : <Button variant="primary" onClick={onClose}>Done</Button>}><div className="connector-setup"><div className="connector-setup-hero"><div className="connector-logo" style={{ background: `${connector.accent}18`, color: connector.accent }}><PlugZap /></div><div><h3>{connector.name}</h3><p>{connector.description}</p></div></div>{step === "success" ? <div className="connection-success"><CheckCircle2 /><h3>Connection established</h3><p>Zasp is synchronizing inventory and will correlate new assets, identities, and runtime data automatically.</p><div><Badge tone="success">Encrypted</Badge><Badge tone="brand">Read only</Badge><Badge tone="info">Initial sync running</Badge></div></div> : <><div className="setup-progress"><span className="active">1. Configure</span><i /><span className={step === "test" ? "active" : ""}>2. Validate</span><i /><span>3. Discover</span></div><div className="connector-fields">{connector.fields.map((field) => <Field key={field.key} label={field.label} type={field.secret ? "password" : "text"} value={values[field.key] ?? ""} onChange={(event) => { setValues((current) => ({ ...current, [field.key]: event.target.value })); setError(""); }} placeholder={field.placeholder} />)}{error && <div className="form-error">{error}</div>}</div>{step === "test" && <div className="test-connection-result"><CheckCircle2 /><div><strong>Credentials validated</strong><p>Endpoint reachable with the required read-only permissions.</p></div></div>}<div className="permission-note"><ShieldCheck /><div><strong>Least-privilege by design</strong><p>This demo stores values only in component memory and never sends credentials to a server.</p></div></div></>}</div></Modal>;
}

export function ConnectorView({ onToast }: { onToast: (message: string) => void }) {
  const { state, dispatch } = useZaspStore(); const [tab, setTab] = useState("All"); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Connector | null>(null);
  const categories = ["All", ...new Set(state.connectors.map((item) => item.category))]; const rows = state.connectors.filter((item) => (tab === "All" || item.category === tab) && `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase()));
  const connected = state.connectors.filter((item) => item.status === "connected");
  return <div className="page"><PageHeader title="Connectors" description="Bring cloud, model, framework, developer, data, and security telemetry into the Zasp graph." actions={<Button icon={<ExternalLink size={16} />}>Integration guide</Button>} /><MetricGrid metrics={[{ label: "Available integrations", value: state.connectors.length, tone: "brand" }, { label: "Connected", value: connected.length, tone: "success" }, { label: "Assets discovered", value: connected.reduce((sum, item) => sum + (item.assetsDiscovered ?? 0), 0), tone: "brand" }, { label: "Connection issues", value: state.connectors.filter((item) => item.status === "error").length, tone: "danger" }]} /><Card><Tabs tabs={categories.map((category) => ({ id: category, label: category, count: category === "All" ? state.connectors.length : state.connectors.filter((item) => item.category === category).length }))} active={tab} onChange={setTab} /><div className="data-toolbar"><SearchBox value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search connectors" /><span className="toolbar-spacer" /><Button icon={<Filter size={15} />}>Filters</Button></div><div className="connector-grid">{rows.map((connector) => <article key={connector.id} className="connector-card"><div className="connector-card-top"><div className="connector-logo" style={{ background: `${connector.accent}18`, color: connector.accent }}><PlugZap /></div><Badge tone={connector.status === "connected" ? "success" : connector.status === "error" ? "critical" : "neutral"}>{connector.status}</Badge></div><h3>{connector.name}</h3><p>{connector.description}</p>{connector.status === "connected" && <div className="connector-stats"><span><RefreshCcw /> Synced {connector.lastSync}</span><span><Cloud /> {connector.assetsDiscovered} assets</span></div>}<div className="connector-actions">{connector.status === "connected" ? <><Button onClick={() => { setSelected(connector); }}>Manage</Button><Button variant="ghost" aria-label={`Disconnect ${connector.name}`} onClick={() => { dispatch({ type: "connector.disconnect", connectorId: connector.id }); onToast(`${connector.name} disconnected`); }}><Unplug size={16} /></Button></> : <><Button aria-label={`Connect ${connector.name}`} onClick={() => setSelected(connector)}>Connect</Button><Button variant="ghost">See docs</Button></>}</div></article>)}</div></Card><ConnectorSetup connector={selected} onClose={() => setSelected(null)} onToast={onToast} /></div>;
}
