"use client";

import { useMemo, useState } from "react";
import { Check, CheckCircle2, Circle, Code2, FileSliders, KeyRound, RotateCw, TimerReset } from "lucide-react";
import { useZaspStore } from "../../domain/store";
import type { Policy } from "../../domain/types";
import { Badge, Button, Field, Modal, Select } from "../../components/ui";

const steps = [
  { id: "details", label: "Policy details & scope", icon: FileSliders },
  { id: "segregation", label: "Token segregation", icon: KeyRound },
  { id: "expiration", label: "Expiration tracking", icon: TimerReset },
  { id: "rotation", label: "Rotation enforcement", icon: RotateCw },
  { id: "review", label: "Review policy", icon: CheckCircle2 },
];

export function PolicyWizard({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: (name: string) => void }) {
  const { state, dispatch } = useZaspStore(); const [step, setStep] = useState(0); const [mode, setMode] = useState<"guided" | "raw">("guided");
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [assetId, setAssetId] = useState("all"); const [identityId, setIdentityId] = useState("all"); const [segregation, setSegregation] = useState(true); const [expiration, setExpiration] = useState(true); const [flagExpired, setFlagExpired] = useState(true); const [maxAge, setMaxAge] = useState(60); const [warning, setWarning] = useState(14); const [severity, setSeverity] = useState<Policy["severity"]>("high"); const [error, setError] = useState("");
  const generatedRaw = useMemo(() => `id: pol-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "new"}\nname: ${name || "Untitled policy"}\ndescription: >\n  ${description || "Continuous identity security policy."}\nseverity: ${severity}\nstatus: active\nscope:\n  assets: ${assetId === "all" ? "all" : `[${assetId}]`}\n  identities: ${identityId === "all" ? "all" : `[${identityId}]`}\ncontrols:\n  token_segregation: ${segregation}\n  expiration_tracking: ${expiration}\n  flag_expired_active_use: ${flagExpired}\n  max_credential_age_days: ${maxAge}\n  warning_threshold_days: ${warning}\n`, [name, description, severity, assetId, identityId, segregation, expiration, flagExpired, maxAge, warning]);
  const [rawOverride, setRawOverride] = useState(""); const raw = rawOverride || generatedRaw;
  const reset = () => { setStep(0); setMode("guided"); setName(""); setDescription(""); setAssetId("all"); setIdentityId("all"); setSegregation(true); setExpiration(true); setFlagExpired(true); setMaxAge(60); setWarning(14); setSeverity("high"); setError(""); setRawOverride(""); };
  const close = () => { reset(); onClose(); };
  const save = (status: Policy["status"]) => {
    if (!name.trim()) { setError("Policy name is required"); setStep(0); setMode("guided"); return; }
    if (maxAge < 1 || warning < 1 || warning >= maxAge) { setError("Warning threshold must be lower than maximum age"); setStep(3); setMode("guided"); return; }
    const policy: Policy = { id: `pol-user-${Date.now()}`, name: name.trim(), description: description.trim() || "Custom identity security policy.", status, severity, scopeAssetIds: assetId === "all" ? [] : [assetId], scopeIdentityIds: identityId === "all" ? [] : [identityId], violationCount: 0, segregation, expirationTracking: expiration, flagExpired, maxAgeDays: maxAge, warningDays: warning, created: "Aug 13, 2026", modified: "Aug 13, 2026", lastTriggered: "Never", raw };
    dispatch({ type: "policy.create", policy }); onSaved(policy.name); reset();
  };
  return <Modal open={open} title="Create identity policy" onClose={close} size="full" footer={<><Button onClick={close}>Cancel</Button><Button onClick={() => save("draft")}>Save draft</Button>{step > 0 && mode === "guided" && <Button onClick={() => setStep(step - 1)}>Previous</Button>}{step < steps.length - 1 && mode === "guided" ? <Button variant="primary" onClick={() => setStep(step + 1)}>Next</Button> : <Button variant="primary" onClick={() => save("active")}>Create policy</Button>}</>}><div className="wizard-layout">
    <aside className="wizard-sidebar"><div className="wizard-sidebar-title">Policy categories</div>{steps.map((item, index) => { const Icon = item.icon; return <button className={index === step ? "active" : index < step ? "complete" : ""} key={item.id} onClick={() => { setStep(index); setMode("guided"); }}><span>{index < step ? <Check size={15} /> : <Icon size={16} />}</span><div><strong>{item.label}</strong><small>{index < step ? "Configured" : index === step ? "In progress" : "Not configured"}</small></div></button>; })}<button className={mode === "raw" ? "active raw-mode" : "raw-mode"} onClick={() => setMode("raw")}><span><Code2 size={16} /></span><div><strong>Raw policy</strong><small>Advanced editor</small></div></button></aside>
    <section className="wizard-main">{mode === "raw" ? <><div className="wizard-heading"><div><span className="eyebrow">Advanced mode</span><h3>Raw policy definition</h3><p>Edit the generated policy directly. Guided configuration remains available.</p></div><Badge tone="brand">YAML</Badge></div><textarea className="raw-editor" aria-label="Raw policy" value={raw} onChange={(event) => setRawOverride(event.target.value)} /></> : <>
      {step === 0 && <><div className="wizard-heading"><div><span className="eyebrow">Step 1 of 5</span><h3>Policy details & scope</h3><p>Name the control and choose the agentic systems and identities it applies to.</p></div></div><div className="form-stack"><Field label="Policy name" value={name} onChange={(event) => { setName(event.target.value); setError(""); }} placeholder="Protect production agent credentials" error={error && !name.trim() ? error : undefined} /><Field label="Description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe what this policy enforces…" multiline /><div className="form-grid"><Select label="Select agentic asset" value={assetId} onChange={(event) => setAssetId(event.target.value)}><option value="all">All assets</option>{state.assets.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select label="Select identity" value={identityId} onChange={(event) => setIdentityId(event.target.value)}><option value="all">All identities</option>{state.identities.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></div><Select label="Violation severity" value={severity} onChange={(event) => setSeverity(event.target.value as Policy["severity"])}><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></Select></div></>}
      {step === 1 && <><div className="wizard-heading"><div><span className="eyebrow">Step 2 of 5</span><h3>Token segregation</h3><p>Detect and flag a single token shared across agent profiles, tools, or environments.</p></div></div><label className="control-option"><input type="checkbox" checked={segregation} onChange={(event) => setSegregation(event.target.checked)} /><span><strong>Enable token segregation monitoring</strong><small>Correlate credential fingerprints and alert when a value crosses declared boundaries.</small></span></label><div className="policy-example"><KeyRound /><div><strong>Example violation</strong><p>A bearer token used by Customer Support Agent is also observed on a development MCP server.</p></div></div></>}
      {step === 2 && <><div className="wizard-heading"><div><span className="eyebrow">Step 3 of 5</span><h3>Expiration tracking</h3><p>Monitor credential validity and active use near or after expiration.</p></div></div><label className="control-option"><input type="checkbox" checked={expiration} onChange={(event) => setExpiration(event.target.checked)} /><span><strong>Enable token lifecycle tracking</strong><small>Flag credentials that approach their provider or policy-defined expiration.</small></span></label><label className="control-option"><input type="checkbox" checked={flagExpired} onChange={(event) => setFlagExpired(event.target.checked)} /><span><strong>Flag expired tokens in active use</strong><small>Detect successful API calls made with credentials already past their expected expiry.</small></span></label></>}
      {step === 3 && <><div className="wizard-heading"><div><span className="eyebrow">Step 4 of 5</span><h3>Rotation enforcement</h3><p>Set a maximum credential age and the warning threshold before it becomes a violation.</p></div></div><label className="control-option"><input type="checkbox" checked={maxAge > 0} onChange={(event) => setMaxAge(event.target.checked ? 60 : 0)} /><span><strong>Enable rotation enforcement</strong><small>Require managed keys and tokens to rotate on a predictable schedule.</small></span></label><div className="form-grid rotation-fields"><Field type="number" label="Maximum credential age (days)" value={maxAge} onChange={(event) => { setMaxAge(Number(event.target.value)); setError(""); }} /><Field type="number" label="Warning threshold (days)" value={warning} onChange={(event) => { setWarning(Number(event.target.value)); setError(""); }} error={error || undefined} /></div></>}
      {step === 4 && <><div className="wizard-heading"><div><span className="eyebrow">Step 5 of 5</span><h3>Review policy</h3><p>Confirm the scope and controls before activation.</p></div><Badge tone={severity}>{severity}</Badge></div><div className="review-summary"><div><span>Policy name</span><strong>{name || "Untitled policy"}</strong></div><div><span>Scope</span><strong>{assetId === "all" ? "All agentic assets" : state.assets.find((item) => item.id === assetId)?.name}</strong></div><div><span>Token segregation</span><strong>{segregation ? "Enabled" : "Disabled"}</strong></div><div><span>Expiration tracking</span><strong>{expiration ? "Enabled" : "Disabled"}</strong></div><div><span>Rotation enforcement</span><strong>{maxAge ? `Maximum ${maxAge} days · warn at ${warning} days` : "Disabled"}</strong></div></div><pre className="policy-code">{generatedRaw}</pre></>}
    </>}</section>
    <aside className="wizard-assistant"><div><span className="assistant-orb">Z</span><strong>Policy assistant</strong></div><div className="assistant-empty"><FileSliders /><p>Zasp uses your security graph to propose a safe starting scope.</p></div><div className="quick-prompts"><span>Suggested questions</span><button onClick={() => { setAssetId("asset-release-agent"); setIdentityId("id-aws-prod"); setName("Protect production agent credentials"); }}>Which identity needs rotation?</button><button onClick={() => setSegregation(true)}>Where are tokens shared?</button><button onClick={() => { setExpiration(true); setMaxAge(45); }}>Recommend lifecycle settings</button></div></aside>
  </div></Modal>;
}
