"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import type { AttackLabPreflight, AttackLabRun, AttackLabRunDetail, TestRun } from "../../../apps/web/api/generated";
import { useAPI } from "../../api/APIProvider";
import { useAPIQuery } from "../../api/query";
import { Badge, Button, Card, Drawer, PageHeader, Select } from "../../components/ui";
import { createProductionRedTeamAPI, redTeamIdempotencyKey, redTeamProductID, type ProductionRedTeamAPI } from "./api";

type AttackLabData = Readonly<{ sources: readonly TestRun[]; runs: readonly AttackLabRun[] }>;
type AttackLabMutationIntent =
  | Readonly<{ kind: "create"; sourceRunID: string; decisionDigest: string; runID: string; idempotencyKey: string }>
  | Readonly<{ kind: "rerun"; sourceRunID: string; sourceVersion: number; runID: string; idempotencyKey: string }>
  | Readonly<{ kind: "cancel"; runID: string; sourceVersion: number; idempotencyKey: string }>;

export function ProductionAttackLabView({ canWrite, api: suppliedAPI }: { canWrite: boolean; api?: ProductionRedTeamAPI }) {
  const { client } = useAPI(); const api = useMemo(() => suppliedAPI ?? createProductionRedTeamAPI(client), [client, suppliedAPI]);
  const load = useCallback(async (signal?: AbortSignal): Promise<AttackLabData> => { const [redTeamRuns, runs] = await Promise.all([api.listRuns(signal), api.listAttackLabRuns(signal)]); return { sources: redTeamRuns.filter((run) => run.status === "complete" && run.verdict === "fail"), runs }; }, [api]);
  const query = useAPIQuery("attack-lab:surface", load); const [selectedSource, setSelectedSource] = useState(""); const [preflight, setPreflight] = useState<AttackLabPreflight | null>(null); const [approved, setApproved] = useState(false); const [preflightState, setPreflightState] = useState<"idle" | "loading" | "error">("idle"); const [selectedRun, setSelectedRun] = useState<AttackLabRunDetail | null>(null); const [detailState, setDetailState] = useState<"idle" | "loading" | "error">("idle"); const [mutationError, setMutationError] = useState(""); const [mutationPending, setMutationPending] = useState(false); const [mutationIntent, setMutationIntent] = useState<AttackLabMutationIntent | null>(null); const request = useRef<AbortController | null>(null); const mutationActive = useRef(false); const mutationIntentRef = useRef<AttackLabMutationIntent | null>(null);
  useEffect(() => () => request.current?.abort(), []);
  useEffect(() => {
    const intent = mutationIntentRef.current; const authoritativeRuns = query.data?.runs ?? [];
    const reconciled = intent?.kind === "create" || intent?.kind === "rerun" ? authoritativeRuns.some((run) => run.id === intent.runID) : intent?.kind === "cancel" ? authoritativeRuns.some((run) => run.id === intent.runID && (run.cancel_requested || terminal(run))) : false;
    if (reconciled) { mutationIntentRef.current = null; setMutationIntent(null); setMutationError(""); }
  }, [query.data]);
  if (query.status === "loading" || query.status === "idle") return <AttackLabState status="Loading authorized Attack Lab runs…" />;
  if (query.status === "forbidden") return <AttackLabState alert="Attack Lab is not authorized in this scope." />;
  if (query.status === "error") return <AttackLabState alert="Attack Lab is unavailable." retry={() => void query.retry()} />;
  const sources = query.data?.sources ?? []; const runs = query.data?.runs ?? []; const sourceRunID = selectedSource || sources[0]?.id || "";
  const selectSource = (value: string) => { if (mutationIntentRef.current) return; request.current?.abort(); setSelectedSource(value); setPreflight(null); setApproved(false); setPreflightState("idle"); setMutationError(""); };
  const review = async () => { if (!canWrite || sourceRunID === "") return; request.current?.abort(); const controller = new AbortController(); request.current = controller; setPreflightState("loading"); setPreflight(null); setApproved(false); setMutationError(""); try { const value = await api.preflightAttackLab(sourceRunID, controller.signal); if (!controller.signal.aborted) { if (Date.parse(value.decision_expires_at) <= Date.now()) setPreflightState("error"); else { setPreflight(value); setPreflightState("idle"); } } } catch { if (!controller.signal.aborted) setPreflightState("error"); } };
  const startMutation = (): boolean => { if (mutationActive.current) return false; mutationActive.current = true; setMutationPending(true); setMutationError(""); return true; };
  const finishMutation = (resolved: boolean) => { mutationActive.current = false; setMutationPending(false); if (resolved) { mutationIntentRef.current = null; setMutationIntent(null); } };
  const retainMutation = (intent: AttackLabMutationIntent) => { mutationIntentRef.current = intent; setMutationIntent(intent); };
  const create = async () => {
    if (!canWrite || !approved || preflight?.source_run_id !== sourceRunID) return;
    if (Date.parse(preflight.decision_expires_at) <= Date.now()) { setApproved(false); setPreflight(null); setPreflightState("error"); return; }
    if (!startMutation()) return;
    const existing = mutationIntentRef.current; if (existing && (existing.kind !== "create" || existing.sourceRunID !== sourceRunID || existing.decisionDigest !== preflight.decision_digest)) { finishMutation(false); setMutationError("Resolve the existing Attack Lab mutation before starting another run."); return; }
    const intent = existing ?? { kind: "create", sourceRunID, decisionDigest: preflight.decision_digest, runID: redTeamProductID(), idempotencyKey: redTeamIdempotencyKey() } as const; retainMutation(intent);
    try { await api.createAttackLabRun(preflight, intent.runID, { idempotencyKey: intent.idempotencyKey }); setApproved(false); setPreflight(null); finishMutation(true); await query.retry(); } catch { finishMutation(false); setMutationError("The Attack Lab request may be unresolved. Retry this exact request identity or reload the authoritative run list."); await query.retry(); }
  };
  const openRun = async (id: string) => { request.current?.abort(); const controller = new AbortController(); request.current = controller; setDetailState("loading"); setMutationError(""); try { const value = await api.getAttackLabRun(id, controller.signal); if (!controller.signal.aborted) { setSelectedRun(value); setDetailState("idle"); } } catch { if (!controller.signal.aborted) setDetailState("error"); } };
  const cancel = async (run: AttackLabRunDetail) => { if (!startMutation()) return; const existing = mutationIntentRef.current; if (existing && (existing.kind !== "cancel" || existing.runID !== run.id || existing.sourceVersion !== run.version)) { finishMutation(false); setMutationError("Resolve the existing Attack Lab mutation before cancelling another run."); return; } const intent = existing ?? { kind: "cancel", runID: run.id, sourceVersion: run.version, idempotencyKey: redTeamIdempotencyKey() } as const; retainMutation(intent); try { await api.cancelAttackLabRun(run.id, run.version, { idempotencyKey: intent.idempotencyKey }); setSelectedRun(null); finishMutation(true); await query.retry(); } catch { finishMutation(false); setMutationError("The Attack Lab cancellation is unresolved. Retry the exact cancellation identity or reload."); await query.retry(); } };
  const rerun = async (run: AttackLabRunDetail) => { if (!startMutation()) return; const existing = mutationIntentRef.current; if (existing && (existing.kind !== "rerun" || existing.sourceRunID !== run.id || existing.sourceVersion !== run.version)) { finishMutation(false); setMutationError("Resolve the existing Attack Lab mutation before rerunning."); return; } const intent = existing ?? { kind: "rerun", sourceRunID: run.id, sourceVersion: run.version, runID: redTeamProductID(), idempotencyKey: redTeamIdempotencyKey() } as const; retainMutation(intent); try { await api.rerunAttackLabRun(run.id, run.version, intent.runID, { idempotencyKey: intent.idempotencyKey }); setSelectedRun(null); finishMutation(true); await query.retry(); } catch { finishMutation(false); setMutationError("The Attack Lab rerun is unresolved. Retry the exact rerun identity or reload."); await query.retry(); } };
  return <div className="page"><PageHeader title="Attack Lab" description="Verify failed Red Team findings in an isolated, tenant-scoped, test-only sandbox." />{query.status === "stale" && <p role="alert">Showing stale Attack Lab data. Reload before approving a run.</p>}{mutationError && <p role="alert" className="form-error">{mutationError}</p>}<Card title="Safety approval"><p>Select a completed failing Red Team run. The server revalidates its live target, non-production environment, credential class, and exact destination before approval.</p>{sources.length === 0 ? <p>No eligible failed Red Team run is available in this scope.</p> : <><Select label="Failed Red Team run" value={sourceRunID} disabled={!canWrite || mutationPending || mutationIntent !== null} onChange={(event) => selectSource(event.target.value)}>{sources.map((run) => <option key={run.id} value={run.id}>{run.id}</option>)}</Select>{canWrite && <Button onClick={() => void review()} disabled={preflightState === "loading" || mutationPending || mutationIntent !== null}>Review safety decision</Button>}{preflightState === "loading" && <p role="status">Revalidating live Attack Lab authority…</p>}{preflightState === "error" && <p role="alert">The safety decision is unavailable or expired.</p>}{preflight && <PreflightDecision value={preflight} approved={approved} onApproved={setApproved} disabled={mutationPending} />}</>}<Button variant="primary" disabled={!canWrite || !approved || preflight?.source_run_id !== sourceRunID || mutationPending} onClick={() => void create()}>{mutationIntent?.kind === "create" ? "Retry unresolved Attack Lab request" : "Run Attack Lab"}</Button></Card><Card title="Runs">{runs.length === 0 ? <p>No Attack Lab runs in this scope.</p> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Run</th><th>Source</th><th>Target</th><th>Status</th><th>Verdict</th><th>Attempt</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td><button className="row-title" aria-label={`Open Attack Lab run ${run.id}`} onClick={() => void openRun(run.id)}>{run.id}</button></td><td>{run.source_run_id}</td><td>{run.target_id}</td><td><Badge tone={attackLabTone(run)}>{run.cancel_requested && !terminal(run) ? "cancelling" : run.status}</Badge></td><td>{run.verdict ?? "—"}</td><td>{run.attempt}</td></tr>)}</tbody></table></div>}</Card>{detailState === "loading" && <p role="status">Loading Attack Lab evidence…</p>}{detailState === "error" && <p role="alert">Attack Lab evidence is unavailable.</p>}{selectedRun && <AttackLabRunDrawer run={selectedRun} canWrite={canWrite} mutationPending={mutationPending} onClose={() => setSelectedRun(null)} onCancel={() => void cancel(selectedRun)} onRerun={() => void rerun(selectedRun)} />}</div>;
}

function PreflightDecision({ value, approved, disabled, onApproved }: { value: AttackLabPreflight; approved: boolean; disabled: boolean; onApproved(value: boolean): void }) {
  return <section aria-label="Exact safety decision"><div className="dashboard-grid"><Card title="Target and credential"><p><code>{value.target_id}</code></p><p>{value.target_kind.replaceAll("_", " ")} · {value.environment} · {value.credential_class.replaceAll("_", " ")}</p></Card><Card title="Destination and side effects"><p><strong>{value.destination}</strong></p><ul>{value.expected_side_effects.map((effect) => <li key={effect}>{effect}</li>)}</ul></Card><Card title="Limits and cleanup"><p>{value.limits.cpu} CPU · {value.limits.memory} memory · {value.limits.ephemeral_storage} ephemeral</p><p>{value.limits.timeout_seconds} seconds, followed by mandatory cleanup.</p></Card></div><h3>Success criterion</h3><p>{value.success_criterion}</p><p>Decision expires <time dateTime={value.decision_expires_at}>{value.decision_expires_at}</time>.</p><label><input type="checkbox" aria-label="Approve exact safety decision" checked={approved} disabled={disabled} onChange={(event) => onApproved(event.target.checked)} /> I approve only this exact target, destination, credential class, side effects, and resource limit.</label></section>;
}

function AttackLabRunDrawer({ run, canWrite, mutationPending, onClose, onCancel, onRerun }: { run: AttackLabRunDetail; canWrite: boolean; mutationPending: boolean; onClose(): void; onCancel(): void; onRerun(): void }) {
  return <Drawer open title="Attack Lab run" onClose={onClose}><p><Badge tone={attackLabTone(run)}>{run.cancel_requested && !terminal(run) ? "cancelling" : run.status}</Badge> · attempt {run.attempt} · version {run.version}</p><dl><dt>Run</dt><dd><code>{run.id}</code></dd><dt>Source</dt><dd><code>{run.source_run_id}</code></dd><dt>Target</dt><dd><code>{run.target_id}</code> · {run.target_kind.replaceAll("_", " ")}</dd><dt>Authority</dt><dd>{run.environment} · {run.credential_class.replaceAll("_", " ")} · {run.destination}</dd><dt>Limits</dt><dd>{run.limits.cpu} / {run.limits.memory} / {run.limits.ephemeral_storage} / {run.limits.timeout_seconds}s</dd></dl>{run.verdict && <><h3>Verdict</h3><p>{run.verdict.replaceAll("_", " ")}</p></>}{run.error_code && <p role="alert">{run.error_code.replaceAll("_", " ")}</p>}{run.attempts.map((attempt) => <section key={attempt.attempt}><h3>Attempt {attempt.attempt}: {attempt.verdict?.replaceAll("_", " ") ?? attempt.error_code?.replaceAll("_", " ")}</h3><p>Criterion observed: {attempt.criterion_observed ? "yes" : "no"} · Canary touched: {attempt.canary_touched ? "yes" : "no"} · Cleanup complete: {attempt.cleanup_completed ? "yes" : "no"}</p><ul>{attempt.evidence.map((item) => <li key={item}>{item}</li>)}</ul>{attempt.evidence_reference && <p>Immutable evidence: <code>{attempt.evidence_reference}</code> @ <code>{attempt.evidence_version_id}</code> · <code>sha256:{attempt.evidence_checksum}</code> · {attempt.evidence_size} bytes</p>}</section>)}{canWrite && !terminal(run) && !run.cancel_requested && <Button variant="danger" disabled={mutationPending} onClick={onCancel}>Cancel run</Button>}{canWrite && terminal(run) && <Button disabled={mutationPending} onClick={onRerun}>Re-run safely</Button>}</Drawer>;
}

function terminal(run: AttackLabRun): boolean { return ["complete", "failed", "cancelled"].includes(run.status); }
function attackLabTone(run: AttackLabRun): "success" | "critical" | "warning" | "info" | "neutral" { return run.status === "complete" && run.verdict === "verified" ? "critical" : run.status === "complete" && run.verdict === "not_reproduced" ? "success" : run.status === "failed" ? "critical" : run.status === "retryable" || run.verdict === "inconclusive" ? "warning" : run.status === "cancelled" ? "neutral" : "info"; }
function AttackLabState({ status, alert, retry }: { status?: string; alert?: string; retry?(): void }) { return <div className="page"><PageHeader title="Attack Lab" description="Tenant-scoped isolated verification." />{status && <p role="status">{status}</p>}{alert && <p role="alert">{alert}</p>}{retry && <Button onClick={retry}>Retry</Button>}</div>; }
