import pathlib,json,hashlib,gzip,shutil,tempfile,re
P=pathlib.Path;r=P(__file__).parent;out=P(tempfile.mkdtemp(prefix='publication-primary2912-',dir=r));out.chmod(0o700);expanded=out.parent/(out.name+'-expanded-scan');expanded.mkdir(mode=0o700);members={};h=lambda b:hashlib.sha256(b).hexdigest()
def add(path,name,compress=False):
 data=path.read_bytes();target=out/name;target.parent.mkdir(parents=True,exist_ok=True); ep=expanded/name;ep.parent.mkdir(parents=True,exist_ok=True)
 if compress:
  z=gzip.compress(data,mtime=0);target=target.with_name(target.name+'.gz');target.write_bytes(z);assert gzip.decompress(z)==data
 else:target.write_bytes(data)
 ep.write_bytes(data);members[str(target.relative_to(out))]={'sha256':h(target.read_bytes()),'bytes':target.stat().st_size,'originalSHA256':h(data),'originalBytes':len(data),'encoding':'gzip-mtime0-exact-roundtrip' if compress else 'identity','originalPrivatePath':str(path),'expandedScanMember':str(ep.relative_to(expanded))}
archive=r/'candidate-2912-ju2e8yei'
for p in sorted(archive.iterdir()):
 if p.name=='canonical-wire.json':continue
 add(p,'evidence/archive/'+p.name,p.suffix=='.mjs' or p.name in ['source-inputs.json','source-fact-delta.json','generated-identities.json'])
for p in sorted((r/'evidence').iterdir()):add(p,'evidence/author/'+p.name,p.stat().st_size>200000)
for name in ['identity.json','compile.log','full23.log']:add(r/'component-review-2912'/name,'evidence/component/'+name)
add(r/'primary-replay-2912-component-receipt.json','evidence/primary-replay-2912-component-receipt.json')
for p in sorted(P('/tmp/zasp-cloud-evidence/runtime-continuation').glob('native379-v2-independent-primary-replay-*.json')):add(p,'evidence/independent/'+p.name)
add(P('/tmp/zasp-cloud-evidence/runtime-continuation/native379-v2-independent-primary-replay-2912-full23.log'),'evidence/independent/native379-v2-independent-primary-replay-2912-full23.log')
add(P('/workspace/.zasp-cloud-owned/native379-v2-readonly-primary-diagnosis-lwq06b3u/read-only-primary-diagnosis.json'),'evidence/read-only-primary-diagnosis.json')
for name in ['add-red.py','integrate.py','refresh-private-node.py','archive-primary-replay.py','archive-primary-replay-2912.py','retain-component-2912.py','implementation.txt','stream-run.txt']:add(r/name,'evidence/author-preparation/'+name,(r/name).stat().st_size>200000)
add(r/'source-checkpoint-a6e8/authorization_worker_ordered_current_native379_v2_test.go','evidence/superseded-a6e8/authorization_worker_ordered_current_native379_v2_test.go',True)
add(r/'candidate-a6e8-teffmiud/summary.json','evidence/superseded-a6e8/summary.json')
# Re-derive exact query hashes using the source algorithm, not runtime observations.
module=P('/workspace/.zasp-cloud-owned/native379-v2-diagnostic-foundation-ntje6h8r/module-cache/owned-source/services/platform/migrations/ordered_current/development-module.sql').read_text();mh=h(module.encode());code=(r/'source/services/platform/apiserver/authorization_worker_ordered_current_native379_v2_test.go').read_text();head='CREATE FUNCTION zasp_authorization80_ordered_current.catalog(expected_manifest text) RETURNS boolean\n';assert module.count(head)==1;body=module[module.index(head):];body=body[:body.index('$catalog$;')];term=' THEN RETURN false; END IF;'
def span(start,finish=term):
 assert body.count(start)==1;a=body.index(start);b=body.index(finish,a);return body[a:b+len(finish)]
frame=re.search(r'const native379V2ReplayFrameSQL = `([^`]+)`',code).group(1);plan=[('session-frame',frame,frame,'session-pid/user-actual-owner-binding')]
for id,start in [('public-wrapper-admission',' IF (SELECT count(*)=3 AND'),('resolver-admission',' IF (SELECT count(*)=1 AND')]:
 raw=span(start,') IS DISTINCT FROM true'+term);plan.append((id,raw,raw[len(' IF ('):-len(') IS DISTINCT FROM true'+term)],'none'))
for id,start,manifest in [('caller-and-manifest',' IF current_user<>',True),('registration-count',' IF (SELECT count(*) FROM zasp_authorization80_ordered_current.registration)<>1',False),('registration-binding',' IF NOT EXISTS(SELECT 1 FROM zasp_authorization80_ordered_current.registration WHERE singleton AND format_version=1',True)]:
 raw=span(start);expr=raw[len(' IF '):-len(term)].replace('expected_manifest','$1::text');plan.append((id,raw,'SELECT NOT ('+expr+')','source-manifest' if manifest else 'none'))
raw=span(' SELECT jsonb_agg(jsonb_build_object(\'kind\',kind,\'identity\',identity,\'fact\',fact) ORDER BY kind COLLATE "C",identity COLLATE "C")');parts=raw.split(';\n');assert len(parts)==3;aggregate=parts[0].strip().replace('INTO expected_rows ','');expr=parts[2][len(' IF '):-len(term)].replace('expected_manifest','$1::text');sql='WITH expected_snapshot(expected_rows) AS MATERIALIZED ('+aggregate+'), normalized_snapshot AS MATERIALIZED (SELECT zasp_authorization80_ordered_current.normalize_rows(expected_rows,$1::text) AS normalized FROM expected_snapshot) SELECT NOT ('+expr+') FROM normalized_snapshot';plan.append(('expected-normalization-and-digest',raw,sql,'source-manifest'))
provenance="WITH provenance_snapshot AS MATERIALIZED (SELECT fact AS provenance FROM zasp_authorization80_ordered_current.expected WHERE kind='build' AND identity='provenance') "
for id,start in [('postgres-provenance'," IF provenance->>'postgres'"),('profile-checksum',' IF NOT EXISTS(SELECT 1 FROM zasp_authorization80_ordered_current.registration WHERE profile_checksum=')]:
 raw=span(start);plan.append((id,raw,provenance+'SELECT NOT ('+raw[len(' IF '):-len(term)]+') FROM provenance_snapshot','none'))
raw=span(' IF EXISTS(SELECT 1 FROM unnest(ARRAY[');plan.append(('private-routine-closure',raw,'SELECT NOT ('+raw[len(' IF '):-len(term)]+')','none'));assert len(plan)==10
steps=[]
for n,(id,raw,sql,shape) in enumerate(plan):
 sh=h(raw.encode());placement=json.dumps(['diagnostic-only-same-repeatable-read-current-role',n,id,sh,mh],ensure_ascii=False,separators=(',',':')).encode();steps.append({'index':n,'id':id,'sourceSpanSHA256':sh,'querySHA256':h(sql.encode()),'queryBytes':len(sql.encode()),'placementSHA256':h(placement),'parameterShape':shape,'parameterSHA256Rule':'SHA256 of JS-compatible canonical actual [] or [sourceManifest] or [actual owner PID,user]; no actual runtime parameters asserted'})
planfile=out/'query-placement-plan.json';planfile.write_text(json.dumps({'scope':'independent reproducible Python transcription of unchanged reviewed Go source extractor; NOT observed execution','moduleSHA256':mh,'implementationSHA256':h(code.encode()),'orderedSteps':steps},indent=2)+'\n');add(planfile,'evidence/query-placement-plan.json');planfile.unlink()
readme='''# Primary-false replay diagnostic: source-only reviewed checkpoint\n\nPrivate baseline512beb; implementation2912, authority-only wire93a6. Author Go23/0/0 (65.837s), independent retained-binary23/0/0 (63.590s), Node6/0/0 (35.838s). There is no seven-test execution claim.\n\nThe four source adoption paths and exact hashes are in evidence/archive/private-source-delta.json. All6239 baseline paths were compared; only these four change. The1544 source pins and every non-authority packet field match reviewed5d18:379rules,10052facts,565sites,589programs,6348steps,eight SQL identities and caps.\n\nReplay is diagnostic ordered re-execution after original normal false, under the owned same RR/current-role/session frame. It is never the original execution trace. NULL, row/cardinality/stream/query/context/charge errors stay unknown. Timing intervals include client/local work, not server profiles. The actual prior root failure remains unresolved; no PG/probes/native ran in this source batch. All589 recorded outcomes/programs are scripted source validation, not589 actual SQL executions.\n\nCurrent companion468734 is unchanged and stale. Fresh combined production readiness/source authority, exact companion anchors, full Go source/module/tool/binary envelope, independent reviews and separately root-authorized bounded execution remain necessary. No new helper frame, production SQL, caps or historical proof changes are authorized by this packet.\n\nRaw25MB JSON is intentionally omitted from publication; exact deterministic gzip is retained and must roundtrip to raw SHA93a6a59469725b7357d0119245726b93c08066abc6afb81972df5ad9d1d4c6a7 (25160408 bytes). SourceJSON/MJS and large hash metadata are deterministically compressed with original byte/hash binding in manifest. Original private raw/binary/baseline/evidence remain retained. Superseded a6 evidence is a distinct checkpoint.\n\nRED classifications are in component receipt: five meaningful behavioral REDs, separate absent-new-API compile RED, and two excluded invocation/implementation failures. Earlier RED logs do not retain complete argv/environment metadata; no invented historical invocation is claimed. Preparation scripts and final component identity are retained; reproduction instructions are not substituted for actual historical records.\n'''
p=out/'README.md';p.write_text(readme);add(p,'evidence/README.md');p.unlink()
manifest={'scope':'PRIVATE bounded source-only publication candidate; independent publication review required before durable adoption','members':members,'omissions':[{'path':str(archive/'canonical-wire.json'),'sha256':h((archive/'canonical-wire.json').read_bytes()),'bytes':(archive/'canonical-wire.json').stat().st_size,'reason':'exact deterministicgzip published instead'},{'path':str(r/'component-review-2912/apiserver-source-review.test'),'sha256':h((r/'component-review-2912/apiserver-source-review.test').read_bytes()),'bytes':(r/'component-review-2912/apiserver-source-review.test').stat().st_size,'reason':'retained private source-component executable; identity published, not frozen native envelope'},{'path':str(r/'baseline.tar'),'reason':'retained private6239-source baseline; reviewed complete source delta published'}]}
(out/'publication-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');(r/'publication-candidate-path.txt').write_text(str(out)+'\n');print(json.dumps({'publication':str(out),'expandedScan':str(expanded),'members':len(members),'manifestSHA256':h((out/'publication-manifest.json').read_bytes())}))
