/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** @description Opaque canonical base64url cursor without padding. */
        readonly Cursor: string;
        readonly PageInfo: {
            /** @constant */
            readonly has_more: true;
            readonly next_cursor: components["schemas"]["Cursor"];
        } | {
            /** @constant */
            readonly has_more: false;
            readonly next_cursor: null;
        };
        readonly ProductError: {
            readonly code: string;
            readonly correlation_id: components["schemas"]["ProductID"];
            readonly message: string;
            readonly retryable: boolean;
        };
        /** @description Canonical product identifier. */
        readonly ProductID: string;
    };
    responses: {
        /** @description Request rejected with a product error. */
        readonly ProductErrorResponse: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ProductError"];
            };
        };
    };
    parameters: {
        /** @description Opaque cursor returned by the preceding page. */
        readonly PageCursor: components["schemas"]["Cursor"];
        /** @description Maximum number of records to return. */
        readonly PageLimit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type Cursor = components['schemas']['Cursor'];
export type PageInfo = components['schemas']['PageInfo'];
export type ProductError = components['schemas']['ProductError'];
export type ProductId = components['schemas']['ProductID'];
export type ResponseProductErrorResponse = components['responses']['ProductErrorResponse'];
export type ParameterPageCursor = components['parameters']['PageCursor'];
export type ParameterPageLimit = components['parameters']['PageLimit'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
