"use client";

import { useState } from "react";
import { CalendarDays, Columns3, Download, Plus, ShieldCheck } from "lucide-react";
import { useZaspStore } from "../../domain/store";
import type { AppRoute, Asset, Severity } from "../../domain/types";
import { Badge, Button, Card, Drawer, EmptyState, MetricGrid, PageHeader, ProgressBar, SearchBox, Select, Tabs } from "../../components/ui";

const providerMark = (provider: string) => provider.slice(0, 2).toUpperCase();
const riskTone = (score: number): Severity => score >= 80 ? "critical" : score >= 65 ? "high" : score >= 45 ? "medium" : "low";

function DataToolbar({ search, setSearch, children }: { search: string; setSearch: (value: string) => void; children?: React.ReactNode }) {
  return <div className="data-toolbar"><SearchBox value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search this inventory" />{children}<span className="toolbar-spacer" /><Button icon={<Columns3 size={15} />}>Columns</Button><Button icon={<Download size={15} />}>Export</Button></div>;
}

function AssetDetail({ asset, onClose }: { asset: Asset | null; onClose: () => void }) {
  const { state } = useZaspStore(); const [tab, setTab] = useState("overview");
  if (!asset) return null;
  const identities = state.identities.filter((item) => asset.identityIds.includes(item.id));
  const violations = state.violations.filter((item) => item.assetId === asset.id);
  const endpoints = state.endpoints.filter((item) => item.assetId === asset.id);
  return <Drawer open title={asset.name} onClose={onClose}><div className="detail-hero"><div className="asset-avatar">{providerMark(asset.provider)}</div><div><div className="detail-title"><h3>{asset.name}</h3><Badge tone={riskTone(asset.riskScore)}>Risk {asset.riskScore}</Badge></div><p>{asset.type} · {asset.provider} · {asset.environment}</p><div className="tag-row">{asset.tags.map((tag) => <Badge key={tag} tone="brand">{tag}</Badge>)}</div></div><Button variant="primary">Run scan</Button></div><Tabs tabs={[{ id: "overview", label: "Overview" }, { id: "graph", label: "Relationships" }, { id: "endpoints", label: "Endpoints", count: endpoints.length }, { id: "identities", label: "Identities", count: identities.length }, { id: "findings", label: "Findings", count: violations.length }]} active={tab} onChange={setTab} />
    <div className="detail-content">{tab === "overview" && <><div className="detail-metrics"><div><span>Risk score</span><strong>{asset.riskScore}</strong></div><div><span>Interactions</span><strong>{asset.interactions.toLocaleString()}</strong></div><div><span>Coverage</span><strong>{asset.coverage}%</strong></div></div><h4>What Zasp discovered</h4><p>Zasp correlated this {asset.type.toLowerCase()} with its runtime endpoints, non-human identities, tools, and security activity. It was last observed {asset.lastSeen.toLowerCase()}.</p><div className="meta-grid"><div><span>Owner</span><strong>{asset.owner}</strong></div><div><span>Environment</span><strong>{asset.environment}</strong></div><div><span>First discovered</span><strong>{asset.discovered}</strong></div><div><span>Last traffic</span><strong>{asset.lastSeen}</strong></div></div></>}
      {tab === "graph" && <div className="relationship-graph"><div className="graph-node owner">{asset.owner}<small>Owner</small></div><i /><div className="graph-node agent">{asset.name}<small>{asset.type}</small></div><i /><div className="graph-stack">{identities.map((item) => <div className="graph-node identity" key={item.id}>{item.name}<small>{item.type}</small></div>)}</div><i /><div className="graph-stack">{[...new Set(identities.flatMap((item) => item.resources))].slice(0, 4).map((resource) => <div className="graph-node resource" key={resource}>{resource}<small>Resource</small></div>)}</div></div>}
      {tab === "endpoints" && <SimpleTable headers={["Endpoint", "Access", "Auth", "Risk", "Requests"]}>{endpoints.map((endpoint) => <tr key={endpoint.id}><td><code>{endpoint.method}</code> {endpoint.path}<small>{endpoint.hostname}</small></td><td>{endpoint.access}</td><td>{endpoint.auth}</td><td><Badge tone={riskTone(endpoint.riskScore)}>{endpoint.riskScore}</Badge></td><td>{endpoint.requests.toLocaleString()}</td></tr>)}</SimpleTable>}
      {tab === "identities" && <SimpleTable headers={["Identity", "Owner", "Type", "Access", "Expiry"]}>{identities.map((identity) => <tr key={identity.id}><td><strong>{identity.name}</strong><small>{identity.provider}</small></td><td>{identity.owner}</td><td><Badge>{identity.type}</Badge></td><td>{identity.access}</td><td>{identity.expiry}</td></tr>)}</SimpleTable>}
      {tab === "findings" && <SimpleTable headers={["Finding", "Severity", "Status", "Discovered"]}>{violations.map((finding) => <tr key={finding.id}><td><strong>{finding.title}</strong></td><td><Badge tone={finding.severity}>{finding.severity}</Badge></td><td>{finding.status.replaceAll("_", " ")}</td><td>{finding.discovered}</td></tr>)}</SimpleTable>}
    </div></Drawer>;
}

function SimpleTable({ headers, children }: { headers: string[]; children: React.ReactNode }) {
  return <div className="table-scroll"><table className="data-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
}

function AssetsView() {
  const { state } = useZaspStore(); const [search, setSearch] = useState(""); const [type, setType] = useState("All"); const [tab, setTab] = useState("all"); const [asset, setAsset] = useState<Asset | null>(null);
  const filtered = state.assets.filter((item) => (tab === "all" || item.status === tab) && (type === "All" || item.type === type) && item.name.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader title="Agentic assets" description="Every agent, MCP server, skill, model, and retrieval system discovered in your environment." actions={<><Button icon={<CalendarDays size={16} />}>Last 7 days</Button><Button variant="primary" icon={<Plus size={16} />}>Create collection</Button></>} /><MetricGrid metrics={[{ label: "Total agentic components", value: state.assets.length, note: "+3 this week", tone: "brand" }, { label: "Critical components", value: state.assets.filter((item) => item.riskScore >= 80).length, note: "Identity and MCP risk", tone: "danger" }, { label: "Average control coverage", value: `${Math.round(state.assets.reduce((sum, item) => sum + item.coverage, 0) / state.assets.length)}%`, note: "+4% this month", tone: "success" }, { label: "Sensitive components", value: new Set(state.sensitiveFindings.map((item) => item.assetId)).size, note: "Secrets, PII, financial data" }]} />
    <Card><Tabs tabs={[{ id: "all", label: "All", count: state.assets.length }, { id: "new", label: "New", count: state.assets.filter((item) => item.status === "new").length }, { id: "shadow", label: "Shadow", count: state.assets.filter((item) => item.status === "shadow").length }, { id: "dormant", label: "Dormant", count: state.assets.filter((item) => item.status === "dormant").length }]} active={tab} onChange={setTab} /><DataToolbar search={search} setSearch={setSearch}><Select value={type} onChange={(event) => setType(event.target.value)}><option>All</option>{["AI Agent", "MCP Server", "Skill", "Model", "RAG"].map((item) => <option key={item}>{item}</option>)}</Select></DataToolbar>{filtered.length ? <SimpleTable headers={["Agentic asset", "Type", "Owner", "Risk score", "Endpoints", "AI interactions", "Violations", "Coverage", "Last seen"]}>{filtered.map((item) => <tr key={item.id} className="clickable-row" onClick={() => setAsset(item)}><td><button className="entity-cell" aria-label={`Open ${item.name}`}><span className="provider-mark">{providerMark(item.provider)}</span><span><strong>{item.name}</strong><small>{item.environment} · {item.provider}</small></span></button></td><td><Badge tone={item.type === "MCP Server" ? "success" : item.type === "AI Agent" ? "brand" : "neutral"}>{item.type}</Badge></td><td>{item.owner}</td><td><Badge tone={riskTone(item.riskScore)}>{item.riskScore}</Badge></td><td>{item.endpoints}</td><td>{item.interactions.toLocaleString()}</td><td>{item.violations ? <Badge tone={item.violations >= 4 ? "critical" : "medium"}>{item.violations}</Badge> : "—"}</td><td><span className="coverage-cell"><ProgressBar value={item.coverage} />{item.coverage}%</span></td><td>{item.lastSeen}</td></tr>)}</SimpleTable> : <EmptyState action={<Button onClick={() => { setSearch(""); setType("All"); setTab("all"); }}>Reset filters</Button>} />}</Card><AssetDetail asset={asset} onClose={() => setAsset(null)} /></>;
}

function EndpointsView() {
  const { state } = useZaspStore(); const [search, setSearch] = useState(""); const [access, setAccess] = useState("All");
  const rows = state.endpoints.filter((item) => (access === "All" || item.access === access) && `${item.path} ${item.hostname}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader title="Agent endpoints" description="Observed model, tool, MCP, and agent routes with authentication and traffic context." actions={<Button variant="primary" icon={<ShieldCheck size={16} />}>Protect endpoints</Button>} /><MetricGrid metrics={[{ label: "Observed endpoints", value: state.endpoints.length, tone: "brand" }, { label: "Public endpoints", value: state.endpoints.filter((item) => item.access === "Public").length, tone: "danger" }, { label: "No authentication", value: state.endpoints.filter((item) => item.auth === "Unauthenticated").length, tone: "danger" }, { label: "Sensitive parameters", value: state.endpoints.filter((item) => item.sensitiveParams.length).length }]} /><Card><DataToolbar search={search} setSearch={setSearch}><Select value={access} onChange={(event) => setAccess(event.target.value)}><option>All</option><option>Public</option><option>Private</option><option>Internal</option></Select></DataToolbar>{rows.length ? <SimpleTable headers={["Endpoint", "Agentic asset", "Access", "Authentication", "Risk", "Requests", "Sensitive data", "Last seen"]}>{rows.map((endpoint) => { const asset = state.assets.find((item) => item.id === endpoint.assetId)!; return <tr key={endpoint.id}><td><strong><code>{endpoint.method}</code> {endpoint.path}</strong><small>{endpoint.hostname}</small></td><td>{asset.name}</td><td><Badge tone={endpoint.access === "Public" ? "critical" : "neutral"}>{endpoint.access}</Badge></td><td><Badge tone={endpoint.auth === "Unauthenticated" ? "critical" : "success"}>{endpoint.auth}</Badge></td><td><Badge tone={riskTone(endpoint.riskScore)}>{endpoint.riskScore}</Badge></td><td>{endpoint.requests.toLocaleString()}</td><td>{endpoint.sensitiveParams.join(", ") || "—"}</td><td>{endpoint.lastSeen}</td></tr>; })}</SimpleTable> : <EmptyState action={<Button onClick={() => { setSearch(""); setAccess("All"); }}>Reset filters</Button>} />}</Card></>;
}

function SensitiveDataView() {
  const { state } = useZaspStore(); const [search, setSearch] = useState("");
  const rows = state.sensitiveFindings.filter((item) => `${item.type} ${item.field}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader title="Sensitive data" description="Secrets, personal data, regulated fields, and code observed in agent requests and responses." actions={<Button variant="primary" icon={<ShieldCheck size={16} />}>Create guardrail</Button>} /><MetricGrid metrics={[{ label: "Sensitive data classes", value: new Set(state.sensitiveFindings.map((item) => item.type)).size, tone: "brand" }, { label: "Secrets observed", value: state.sensitiveFindings.filter((item) => item.type === "Secret").reduce((sum, item) => sum + item.occurrences, 0), tone: "danger" }, { label: "PII occurrences", value: state.sensitiveFindings.filter((item) => item.type === "PII").reduce((sum, item) => sum + item.occurrences, 0).toLocaleString() }, { label: "Affected components", value: new Set(state.sensitiveFindings.map((item) => item.assetId)).size }]} /><Card><DataToolbar search={search} setSearch={setSearch} /><SimpleTable headers={["Data class", "Field", "Agentic asset", "Endpoint", "Direction", "Occurrences", "Last seen"]}>{rows.map((item) => <tr key={item.id}><td><Badge tone={item.type === "Secret" ? "critical" : item.type === "PII" ? "high" : "medium"}>{item.type}</Badge></td><td><strong>{item.field}</strong></td><td>{state.assets.find((asset) => asset.id === item.assetId)?.name}</td><td><code>{state.endpoints.find((endpoint) => endpoint.id === item.endpointId)?.path}</code></td><td>{item.direction}</td><td>{item.occurrences.toLocaleString()}</td><td>{item.lastSeen}</td></tr>)}</SimpleTable></Card></>;
}

function ChangesView() {
  const { state } = useZaspStore(); const [search, setSearch] = useState(""); const rows = state.changes.filter((item) => item.description.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader title="Recent changes" description="New and changed agentic components, identities, endpoints, permissions, and traffic patterns." actions={<Button icon={<CalendarDays size={16} />}>Last 7 days</Button>} /><MetricGrid metrics={[{ label: "Changes detected", value: state.changes.length, tone: "brand" }, { label: "Critical changes", value: state.changes.filter((item) => item.risk === "critical").length, tone: "danger" }, { label: "New components", value: state.changes.filter((item) => item.kind === "New asset").length }, { label: "Permission changes", value: state.changes.filter((item) => item.kind === "Permission change").length }]} /><Card><DataToolbar search={search} setSearch={setSearch} /><div className="timeline-list">{rows.map((item) => { const asset = state.assets.find((candidate) => candidate.id === item.assetId)!; return <button key={item.id}><span className={`timeline-dot timeline-dot--${item.risk}`} /><span><strong>{item.description}</strong><small>{asset.name} · {item.kind}</small></span><Badge tone={item.risk}>{item.risk}</Badge><time>{item.time}</time></button>; })}</div></Card></>;
}

export function DiscoveryView({ route }: { route: AppRoute }) {
  return <div className="page">{route.path === "/discovery/assets" ? <AssetsView /> : route.path === "/discovery/endpoints" ? <EndpointsView /> : route.path === "/discovery/sensitive-data" ? <SensitiveDataView /> : <ChangesView />}</div>;
}
