import fs from "node:fs";
import path from "node:path";
import { describe,expect,it } from "vitest";
const read=(file:string)=>fs.readFileSync(path.join(process.cwd(),file),"utf8");
describe("M7 retention, external flows, AI, system health, and degraded UX batch",()=>{
  it("publishes the exact six product operations",()=>{const source=read("openapi/openapi.yaml");for(const id of ["getExternalDataFlows","updateExternalDataFlows","createAIExplanation","getSystemStatus","listSystemComponents","getSystemVersion"])expect(source).toContain(`operationId: ${id}`)});
  it("implements bounded service and UI boundaries",()=>{const admin=read("services/platform/admincontrol/admincontrol.go");const telemetry=read("services/platform/producttelemetry/m7.go");const ai=read("services/platform/aigateway/m7.go");const ui=read("app/features/administration/AdminOperationsView.tsx");for(const symbol of ["NewRetentionWorker","NewExternalFlowStore","NewSystemProbes"])expect(admin).toContain(` ${symbol}`);for(const symbol of ["SerializeProductEvent","NewFlagCache"])expect(telemetry).toContain(` ${symbol}`);for(const symbol of ["RedactApprovedFields","NewGovernor"])expect(ai).toContain(` ${symbol}`);for(const text of ["System health","External data flows","Audit log","AI explanation unavailable","Session activity degraded"])expect(ui).toContain(text)});
  it("records exactly the 29-task slice without provider claims",()=>{const tracker=read("docs/internal/implementation_status_v1.5.md");for(const value of ["| Pending | 216 |","| In progress | 325 |","| Complete | 184 |","| Blocked | 3 |","`216/325/184/3`","| M7 | 62 | 0 | 62 | 0 | 0 |"])expect(tracker).toContain(value);const active=tracker.match(/## In progress[\s\S]*?## Complete/)?.[0]??"";for(const task of ["M7-19","M7-20","M7-21","M7-22","M7-22a","M7-23","M7-24","M7-25","M7-26a","M7-26b","M7-26c","M7-26","M7-27","M7-28","M7-29","M7-30","M7-31","M7-32","M7-33","M7-34","M7-35","M7-36","M7-37","M7-38","M7-39a","M7-39b","M7-39c","M7-39d","M7-39e"])expect(active.match(new RegExp(`^\\| ${task} \\|`,"gm"))).toHaveLength(1);expect(tracker).toContain("provider probes remain unresolved");expect(tracker).toContain("provider scheduling remains unresolved")});
});
