package apiserver

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"reflect"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/zasp-ai/zasp-sec/services/platform/migrations"
)

func auditExportRepositoryFixture(t *testing.T) (*AuditExportRepository, *discoveryCallDatabase, RequestIdentity, AuditExportCreate) {
	t.Helper()
	identity := fixtureRequestIdentity(t)
	identity.CredentialKind = CredentialBrowserSession
	identity.FreshAuthenticated = true
	identity.Permissions = append(identity.Permissions, "view_audit")
	database := &discoveryCallDatabase{schema: ProductionRecoverySchemaVersion, responses: map[string]json.RawMessage{postgresAuditExportReadySQL: json.RawMessage(`true`)}, errors: map[string]error{}}
	repository, err := NewAuditExportRepository(database)
	if err != nil {
		t.Fatal(err)
	}
	digest := sha256.Sum256([]byte("owned-audit-session-fixture"))
	input := AuditExportCreate{ExportID: "pid_72000001-0000-4000-8000-000000000001", AuditID: "pid_72000002-0000-4000-8000-000000000002", OutboxID: "pid_72000003-0000-4000-8000-000000000003", IdempotencyKey: "audit-export-fixture-0001", SessionDigest: digest[:]}
	database.responses[postgresAuditExportCreateSQL] = auditExportQueuedFixture(t, identity, input)
	return repository, database, identity, input
}

func auditExportQueuedFixture(t *testing.T, identity RequestIdentity, input AuditExportCreate) json.RawMessage {
	t.Helper()
	body, err := json.Marshal(AuditExportDescriptor{ID: input.ExportID, OrganizationID: identity.Scope.OrganizationID().String(), WorkspaceID: identity.Scope.WorkspaceID().String(), EnvironmentID: identity.Scope.EnvironmentID().String(), CreatedAt: "2026-09-12T10:00:00.000000Z", AuditCorrelationID: input.AuditID, Status: "queued"})
	if err != nil {
		t.Fatal(err)
	}
	return body
}

func TestAuditExportRepositoryCreatesWithStoredSessionAndCompiledAuthority(t *testing.T) {
	if postgresAuditExportReadySQL != `SELECT to_jsonb(zasp_audit_export_api_readiness($1,$2))` {
		t.Fatal("API readiness must check registered export capability, not only release graph")
	}
	repository, database, identity, input := auditExportRepositoryFixture(t)
	got, err := repository.Create(context.Background(), identity, input)
	if err != nil || got.ID != input.ExportID || got.Status != "queued" || got.EventCount != nil {
		t.Fatalf("create: %v %#v", err, got)
	}
	digest := sha256.Sum256([]byte("{}"))
	want := []any{identity.Scope.OrganizationID().String(), identity.Scope.WorkspaceID().String(), identity.Scope.EnvironmentID().String(), identity.PrincipalID.String(), input.SessionDigest, identity.CSRFToken, input.IdempotencyKey, input.ExportID, input.AuditID, input.OutboxID, digest[:], migrations.ProductionAuditExports().Checksum(), migrations.ProductionAuditExportsSemanticFingerprint()}
	if database.query != postgresAuditExportCreateSQL || !reflect.DeepEqual(database.args, want) {
		t.Fatal("create did not bind exact stored-session and compiled authority")
	}
	// Exact-key replay can return the original IDs, not IDs regenerated by HTTP.
	input.ExportID = "pid_72000004-0000-4000-8000-000000000004"
	input.AuditID = "pid_72000005-0000-4000-8000-000000000005"
	if replay, err := repository.Create(context.Background(), identity, input); err != nil || replay.ID != got.ID || replay.AuditCorrelationID != got.AuditCorrelationID {
		t.Fatal("replay discarded persisted job/audit identity", err)
	}
}

func TestAuditExportRepositoryRefusesInvalidInputBeforeProviderCalls(t *testing.T) {
	for _, kind := range []string{"bearer", "stale", "permission", "digest", "zero digest", "id", "alias", "key", "csrf"} {
		t.Run(kind, func(t *testing.T) {
			repository, database, identity, input := auditExportRepositoryFixture(t)
			switch kind {
			case "bearer":
				identity.CredentialKind = CredentialBearerToken
			case "stale":
				identity.FreshAuthenticated = false
			case "permission":
				identity.Permissions = []string{"view"}
			case "digest":
				input.SessionDigest = input.SessionDigest[:31]
			case "zero digest":
				input.SessionDigest = make([]byte, 32)
			case "id":
				input.ExportID = "foreign"
			case "alias":
				input.AuditID = input.ExportID
			case "key":
				input.IdempotencyKey = ""
			case "csrf":
				identity.CSRFToken = ""
			}
			before := len(database.queries)
			if _, err := repository.Create(context.Background(), identity, input); err == nil || len(database.queries) != before {
				t.Fatal("invalid request reached provider", err)
			}
		})
	}
}

func TestAuditExportRepositoryRechecksReadinessAndMapsStableSQLFailures(t *testing.T) {
	repository, database, identity, input := auditExportRepositoryFixture(t)
	database.responses[postgresAuditExportReadySQL] = json.RawMessage(`false`)
	if _, err := repository.Create(context.Background(), identity, input); !errors.Is(err, ErrRepositoryUnavailable) || database.query != postgresAuditExportReadySQL {
		t.Fatal("cached readiness authorized create", err)
	}
	database.responses[postgresAuditExportReadySQL] = json.RawMessage(`true`)
	for code, want := range map[string]error{"22023": ErrRepositoryOperation, "23505": ErrRepositoryConflict, "P0002": ErrRepositoryNotFound, "28000": ErrRepositoryAuthentication, "42501": ErrAuditExportForbidden, "55000": ErrRepositoryUnavailable, "XX000": ErrRepositoryUnavailable} {
		database.errors[postgresAuditExportCreateSQL] = errors.Join(ErrRepositoryUnavailable, &pgconn.PgError{Code: code, Message: "private provider detail"})
		if _, err := repository.Create(context.Background(), identity, input); !errors.Is(err, want) || strings.Contains(err.Error(), "private provider detail") {
			t.Fatalf("SQL%s error not sanitized: %v", code, err)
		}
	}
}

func TestAuditExportRepositoryRejectsUntrustedDescriptorShapes(t *testing.T) {
	for _, kind := range []string{"alias", "duplicate", "extra", "missing", "foreign", "null", "trailing", "oversized", "partial ready"} {
		t.Run(kind, func(t *testing.T) {
			repository, database, identity, input := auditExportRepositoryFixture(t)
			body := string(database.responses[postgresAuditExportCreateSQL])
			switch kind {
			case "alias":
				body = strings.Replace(body, `"id":`, `"ID":`, 1)
			case "duplicate":
				body = strings.Replace(body, `"status":"queued"`, `"status":"ready","status":"queued"`, 1)
			case "extra":
				body = strings.Replace(body, `{`, `{"object_key":"private",`, 1)
			case "missing":
				body = strings.Replace(body, `"event_count":null`, `"ignored":null`, 1)
			case "foreign":
				body = strings.Replace(body, identity.Scope.OrganizationID().String(), "pid_72000009-0000-4000-8000-000000000009", 1)
			case "null":
				body = `null`
			case "trailing":
				body += `{}`
			case "oversized":
				body += strings.Repeat(" ", 8192)
			case "partial ready":
				body = strings.Replace(body, `"queued"`, `"ready"`, 1)
			}
			database.responses[postgresAuditExportCreateSQL] = json.RawMessage(body)
			if _, err := repository.Create(context.Background(), identity, input); !errors.Is(err, ErrRepositoryUnavailable) {
				t.Fatal("accepted invalid descriptor", err)
			}
		})
	}
}

func TestAuditExportDescriptorStateBoundaries(t *testing.T) {
	_, database, _, _ := auditExportRepositoryFixture(t)
	var queued map[string]any
	if err := json.Unmarshal(database.responses[postgresAuditExportCreateSQL], &queued); err != nil {
		t.Fatal(err)
	}
	for _, status := range []string{"queued", "processing", "failed", "ready empty", "ready populated"} {
		t.Run(status, func(t *testing.T) {
			body := make(map[string]any, len(queued))
			for key, value := range queued {
				body[key] = value
			}
			body["status"] = status
			switch status {
			case "failed":
				body["failure_code"] = "execution_failed"
			case "ready empty", "ready populated":
				body["status"] = "ready"
				body["captured_at"] = "2026-09-12T10:00:01.000000Z"
				body["manifest_sha256"] = strings.Repeat("a", 64)
				body["event_count"], body["chunk_count"], body["chunk_bytes"] = 0, 0, 0
				if status == "ready populated" {
					body["event_count"], body["chunk_count"], body["chunk_bytes"] = 1001, 2, 1048577
				}
			}
			encoded, err := json.Marshal(body)
			if err != nil {
				t.Fatal(err)
			}
			if _, err := decodeAuditExportDescriptor(encoded); err != nil {
				t.Fatal("valid state rejected", err)
			}
			for _, mutation := range []string{"null timestamp", "noncanonical timestamp", "null id", "extra null"} {
				bad := make(map[string]any, len(body))
				for key, value := range body {
					bad[key] = value
				}
				switch mutation {
				case "null timestamp":
					bad["created_at"] = nil
				case "noncanonical timestamp":
					bad["created_at"] = "2026-09-12T10:00:00Z"
				case "null id":
					bad["id"] = nil
				case "extra null":
					bad["object_reference"] = nil
				}
				encoded, err := json.Marshal(bad)
				if err != nil {
					t.Fatal(err)
				}
				if _, err := decodeAuditExportDescriptor(encoded); !errors.Is(err, ErrRepositoryUnavailable) {
					t.Fatalf("%s accepted: %v", mutation, err)
				}
			}
		})
	}
}

func TestAuditExportRepositoryCanceledRequestDoesNotQuery(t *testing.T) {
	repository, database, identity, input := auditExportRepositoryFixture(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	before := len(database.queries)
	if _, err := repository.Create(ctx, identity, input); !errors.Is(err, context.Canceled) || len(database.queries) != before {
		t.Fatal("canceled request queried database", err)
	}
}

type cancelingAuditExportDatabase struct {
	*discoveryCallDatabase
	cancel        context.CancelFunc
	queryToCancel string
}

func (database *cancelingAuditExportDatabase) QueryJSON(ctx context.Context, query string, args ...any) (json.RawMessage, error) {
	body, err := database.discoveryCallDatabase.QueryJSON(ctx, query, args...)
	if query == database.queryToCancel {
		database.cancel()
	}
	return body, err
}

func TestAuditExportRepositoryCancellationAtResponseBoundary(t *testing.T) {
	for _, query := range []string{postgresAuditExportReadySQL, postgresAuditExportCreateSQL} {
		t.Run(query, func(t *testing.T) {
			repository, database, identity, input := auditExportRepositoryFixture(t)
			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			repository.database = &cancelingAuditExportDatabase{discoveryCallDatabase: database, cancel: cancel, queryToCancel: query}
			before := len(database.queries)
			if _, err := repository.Create(ctx, identity, input); err != context.Canceled {
				t.Fatalf("cancellation returned %v", err)
			}
			if query == postgresAuditExportReadySQL && len(database.queries) != before+1 {
				t.Fatal("canceled readiness reached create")
			}
		})
	}
}

func TestAuditExportRepositorySanitizesWrappedCancellation(t *testing.T) {
	for _, sentinel := range []error{context.Canceled, context.DeadlineExceeded} {
		err := errors.Join(ErrRepositoryUnavailable, errors.New("private provider detail"), sentinel)
		if got := auditExportRepositoryError(err); got != sentinel {
			t.Fatalf("wrapped cancellation was not sanitized: %v", got)
		}
	}
}
