environment               = "production"
region                    = "us-west-2"
account_id                = "000000000000"
cluster_name              = "zasp-production"
vpc_cidr                  = "10.80.0.0/16"
private_subnet_cidrs      = ["10.80.0.0/20", "10.80.16.0/20"]
availability_zones        = ["us-west-2a", "us-west-2b"]
endpoint_public_access    = false
node_desired_size         = 3
node_min_size             = 3
node_max_size             = 6
node_instance_types       = ["m7i.xlarge"]
opensearch_instance_type  = "r7g.large.search"
opensearch_instance_count = 3
opensearch_volume_size    = 100
evidence_retention_days   = 365
attack_lab_namespace      = "zasp-attack-lab"
offline_validation        = true
connector_client_ids = {
  github = "Iv1.1234567890abcdef"
  okta   = "0oa1234567890abcdef"
}
