import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
const api=()=>import('./collect-production-go-advisory-evidence-v1.mjs');
const config={protocol_version:'v1.0.0',scanner_name:'govulncheck',scanner_version:'v1.7.0',db:'file:///workspace/scratch/official-go-vulndb-generated',db_last_modified:'2026-10-01T20:24:15Z',go_version:'go1.25.13',scan_level:'package',scan_mode:'source'};
const messages=()=>[{config:{...config}},{SBOM:{go_version:'go1.25.13',modules:[{path:'example/module',version:'v1.0.0'}],roots:['example/module']}},{osv:{id:'GO-2026-5932',schema_version:'1.3.1',modified:'2026-10-01T20:24:15Z',affected:[]}},{finding:{osv:'GO-2026-5932',trace:[{module:'example/module',version:'v1.0.0'}]}}];
const wire=xs=>Buffer.from(xs.map(x=>JSON.stringify(x)).join('\n')+'\n');
test('exit0 finding stream is collected with UNKNOWN severity and never release clearance',async()=>{
 const a=await api(),r=a.inspectGoScanStream(wire(messages()));assert.equal(r.findings.length,1);assert.equal(r.findings[0].severity,'UNKNOWN');assert.equal(r.releaseAccepted,false);assert.equal(r.scanLevel,'package');assert.equal(r.fullMVSClearance,false);
 const zero=messages().slice(0,2);assert.equal(a.inspectGoScanStream(wire(zero)).findings.length,0);assert.equal(a.inspectGoScanStream(wire(zero)).releaseAccepted,false);
});
test('actual old runtime scanner stream is a protocol fixture only',async()=>{
 const a=await api(),file='/workspace/scratch/go-compression-closure/package-scan.json';if(!fs.existsSync(file))return;
 const r=a.inspectGoScanStream(fs.readFileSync(file));assert.deepEqual([...new Set(r.findings.map(x=>x.id))].sort(),['GO-2026-5932','GO-2026-6354','GO-2026-6355']);assert.equal(r.releaseAccepted,false);
});
test('strict stream refuses duplicate/malformed/truncated/protocol/SBOM/unknown references',async()=>{
 const a=await api();for(const mutate of [x=>x.shift(),x=>x.splice(1,1),x=>x.push(x[0]),x=>x[0].config.scan_level='symbol',x=>x[0].config.scanner_version='untrusted',x=>x[0].config.db='https://unapproved.example',x=>x.push({error:{message:'failure'}}),x=>x[3].finding.osv='GO-UNKNOWN',x=>x[1].SBOM.roots=[],x=>x[1].SBOM.modules.push(x[1].SBOM.modules[0])]){const x=messages();mutate(x);assert.throws(()=>a.inspectGoScanStream(wire(x)),/advisory component refused/);}
 for(const raw of [Buffer.from('{"config":{},"config":{}}'),wire(messages()).subarray(0,-3),Buffer.from('{} trailing'),Buffer.alloc(64*1024*1024+1)])assert.throws(()=>a.inspectGoScanStream(raw),/advisory component refused/);
});
test('reviewed fixed manifest still refuses unowned execution and caller trust; private blank-pin fixture refuses approval',async()=>{
 const a=await api();assert.throws(()=>a.collectProductionGoAdvisoryEvidenceV1(),/owned Node tool authority/);
 assert.throws(()=>a.collectProductionGoAdvisoryEvidenceV1({path:'/tmp/fabricated',sha256:'0'.repeat(64)}),/caller authority/);
 assert.throws(()=>a.deriveProductionGoAdvisoryManifestV1({root:'/tmp/alternate'}),/caller authority/);
 const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-blank-pin-fixture-'));try{
  const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');
  assert.ok(source.includes("const APPROVED_INPUT_MANIFEST_SHA256='d25585907c7a50c963f215b1414ff3caae875e95cf284653234d78af8463c190';"));
  const fixture=path.join(temporary,'collector.mjs');fs.writeFileSync(fixture,source.replace(/const APPROVED_INPUT_MANIFEST_SHA256='[a-f0-9]*';/,"const APPROVED_INPUT_MANIFEST_SHA256='';"));
  const privateApi=await import(new URL('file://'+fixture));assert.throws(()=>privateApi.collectProductionGoAdvisoryEvidenceV1(),/manifest approval unavailable/);
 }finally{fs.rmSync(temporary,{recursive:true,force:true});}
});
// Owned-process fixtures are patched copies, never accepted collection tools.
function runnerFixture(mode){
 const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-runner-test-'));
 const original=fs.readFileSync(new URL('./production-advisory-owned-runner-v1.py',import.meta.url),'utf8');
 const child=path.join(temporary,'child.py');
 const scripts={success:'print("owned-success")',failure:'raise RuntimeError("private-child-error")',timeout:'import time;time.sleep(30)',overflow:'print("x"*100000)',orphan:'import os,time\npid=os.fork()\nif pid==0: time.sleep(30)\nelse: print("parent-exited",flush=True)',escape:'import os,time\npid=os.fork()\nif pid==0: os.setsid(); time.sleep(30)\nelse: print("escaped-child",flush=True)'};
 fs.writeFileSync(child,scripts[mode]);const runner=path.join(temporary,'runner.py');
 const patched=original.replace('# TEST_FIXTURE_INSERTION',`COMMANDS={'fixture': [sys.executable, ${JSON.stringify(child)}]}\nMODE_ROOTS={'fixture': ${JSON.stringify(temporary)}}\nTIMEOUT_SECONDS=0.3\nOUTPUT_LIMIT=4096`);
 fs.writeFileSync(runner,patched);return {temporary,runner};
}
test('owned runner joins success, exception, timeout, overflow and orphan without new survivors',()=>{
 for(const mode of ['success','failure','timeout','overflow','orphan','escape']){
  const f=runnerFixture(mode);try{const run=spawnSync('/usr/bin/python3',['-I',f.runner,'fixture'],{encoding:'utf8',timeout:10000,maxBuffer:1024*1024});assert.equal(run.status,0);const r=JSON.parse(run.stdout);assert.equal(r.waitJoined,true);assert.equal(r.newSurvivors.length,0);assert.ok(Array.isArray(r.preexistingZombies));
   if(mode==='success')assert.equal(r.childExit,0);if(mode==='failure')assert.notEqual(r.childExit,0);if(mode==='timeout')assert.equal(r.timeout,true);if(mode==='overflow')assert.equal(r.overflow,true);if(mode==='orphan'||mode==='escape')assert.ok(r.adoptedReaped>0);
  }finally{fs.rmSync(f.temporary,{recursive:true,force:true});}
 }
});

test('fixed local replacement multiplicity and repeated exact OSV truth stay closed',async()=>{
 const a=await api();const base=messages();base.push(structuredClone(base[2]));assert.equal(a.inspectGoScanStream(wire(base)).findings.length,1);
 const conflicting=messages();conflicting.push({...structuredClone(conflicting[2]),osv:{...conflicting[2].osv,summary:'different'}});assert.throws(()=>a.inspectGoScanStream(wire(conflicting)),/OSV protocol/);
 const fixture='/workspace/scratch/go-compression-closure/package-scan.json';if(!fs.existsSync(fixture))return;
 const raw=fs.readFileSync(fixture,'utf8');for(const change of [x=>x.replace('"path": "../health"','"path": "../unknown"'),x=>x.replace('"path": "../health"','"path": "../platform"')])assert.throws(()=>a.inspectGoScanStream(Buffer.from(change(raw))),/advisory component refused/);
});
test('patched-only input checker refuses changed/missing/symlink/capped members',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-input-test-'));try{
  const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {pinnedRead as fixtureRead};\n');const {fixtureRead}=await import(new URL('file://'+module));
  const file=path.join(temp,'input');fs.writeFileSync(file,'original');const crypto=await import('node:crypto');const pin=crypto.createHash('sha256').update('original').digest('hex');assert.equal(fixtureRead(file,pin).toString(),'original');fs.writeFileSync(file,'changed');assert.throws(()=>fixtureRead(file,pin),/input bytes/);fs.rmSync(file);assert.throws(()=>fixtureRead(file,pin));fs.writeFileSync(file,'original');const link=path.join(temp,'link');fs.symlinkSync(file,link);assert.throws(()=>fixtureRead(link,pin),/topology/);const fd=fs.openSync(file,'w');fs.ftruncateSync(fd,300*1024*1024);fs.closeSync(fd);assert.throws(()=>fixtureRead(file,pin),/byte cap/);
 }finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('runner rejects caller commands and extra arguments without executing them',()=>{
 const f=runnerFixture('success');try{for(const args of [['unlisted-mode'],['fixture','extra'],['fixture; arbitrary-command']]){const r=spawnSync('/usr/bin/python3',['-I','-S',f.runner,...args],{encoding:'utf8',timeout:10000});assert.equal(r.status,1);assert.equal(r.stdout,'');assert.equal(r.stderr,'owned advisory runner refused\n');}}
 finally{fs.rmSync(f.temporary,{recursive:true,force:true});}
});

test('runner scan modes remain disabled even when called directly before approval',()=>{
 const f=runnerFixture('success');try{
  const text=fs.readFileSync(f.runner,'utf8').replace("COMMANDS={'fixture':", "COMMANDS={'scan-health':").replace("MODE_ROOTS={'fixture':", "MODE_ROOTS={'scan-health':");fs.writeFileSync(f.runner,text);
  const r=spawnSync('/usr/bin/python3.13',['-I','-S',f.runner,'scan-health'],{encoding:'utf8',timeout:10000});assert.equal(r.status,1);assert.equal(r.stdout,'');assert.equal(r.stderr,'owned advisory runner refused\n');
 }finally{fs.rmSync(f.temporary,{recursive:true,force:true});}
});
test('inspection preserves exact advisory and finding stream multiplicities',async()=>{
 const a=await api(),xs=messages();xs.push(structuredClone(xs[2]),structuredClone(xs[3]));const r=a.inspectGoScanStream(wire(xs));assert.deepEqual(r.messageCounts,{config:1,SBOM:1,osv:2,finding:2});assert.equal(r.findings.length,2);
});

test('normal module ZIP authenticates h1 and refuses changed, duplicate, escaping and capped members',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-zip-test-'));try{
  const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {normalModuleZIP as fixtureZIP};\n');const {fixtureZIP}=await import(new URL('file://'+module));
  const crypto=await import('node:crypto'),prefix='example.org/module@v1.0.0/';const h1='h1:'+crypto.createHash('sha256').update(crypto.createHash('sha256').update('package module\n').digest('hex')+'  '+prefix+'module.go\n').digest('base64');
  function zip(names){const file=path.join(temp,'input.zip');const code='import sys,zipfile,json\nwith zipfile.ZipFile(sys.argv[1],"w",compression=zipfile.ZIP_DEFLATED) as z:\n for name in json.loads(sys.argv[2]):z.writestr(name,"package module\\n")';assert.equal(spawnSync('/usr/bin/python3.13',['-I','-S','-c',code,file,JSON.stringify(names)]).status,0);return fs.readFileSync(file);}
  const good=zip([prefix+'module.go']);assert.equal(fixtureZIP(good,'example.org/module','v1.0.0',h1)[0].raw.toString(),'package module\n');assert.throws(()=>fixtureZIP(good,'example.org/module','v1.0.0','h1:'+'A'.repeat(44)));for(const names of [[prefix+'module.go',prefix+'module.go'],[prefix+'../evil'],['elsewhere/file']])assert.throws(()=>fixtureZIP(zip(names),'example.org/module','v1.0.0',h1));assert.throws(()=>fixtureZIP(good.subarray(0,-4),'example.org/module','v1.0.0',h1));assert.throws(()=>fixtureZIP(Buffer.alloc(64*1024*1024+1),'example.org/module','v1.0.0',h1));
 }finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('exclusive snapshot binds actual copy reads and refuses restored substitution or existing output',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-copy-test-'));try{
  const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {writeBoundSnapshot as fixtureCopy};\n');const {fixtureCopy}=await import(new URL('file://'+module));const crypto=await import('node:crypto');const input=path.join(temp,'input');fs.writeFileSync(input,'authentic');const row={path:input,destination:'source/input',bytes:9,mode:0o400,sha256:crypto.createHash('sha256').update('authentic').digest('hex')};const out=path.join(temp,'snapshot');fixtureCopy(out,[row]);assert.equal(fs.readFileSync(path.join(out,'source/input'),'utf8'),'authentic');assert.throws(()=>fixtureCopy(out,[row]));fs.rmSync(out,{recursive:true,force:true});
  const read=fs.readFileSync;let substituted=false;fs.readFileSync=function(file,...args){if(file===input&&!substituted){substituted=true;return Buffer.from('malicious');}return read.call(this,file,...args);};try{assert.throws(()=>fixtureCopy(out,[row]),/input bytes/);}finally{fs.readFileSync=read;}assert.equal(fs.existsSync(out),false);assert.equal(read(input,'utf8'),'authentic');assert.throws(()=>fixtureCopy(out,[row,row]));assert.throws(()=>fixtureCopy(out,[{...row,destination:'../escape'}]));assert.equal(fs.existsSync(out),false);
 }finally{fs.rmSync(temp,{recursive:true,force:true});}
});

test('only three reviewed Python links admit exact targets and consumed regular bytes',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-python-test-'));try{
  const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {pythonTopology as fixturePython, treeFiles as fixtureTree};\n');const {fixturePython,fixtureTree}=await import(new URL('file://'+module));const topology=fixturePython();assert.equal(topology.links.length,3);assert.ok(topology.files.length>100);
  const link=topology.links[0],readlink=fs.readlinkSync;fs.readlinkSync=function(file,...args){return file===link.path?'foreign.py':readlink.call(this,file,...args);};try{assert.throws(()=>fixturePython(),/Python link topology/);}finally{fs.readlinkSync=readlink;}
  const read=fs.readFileSync;fs.readFileSync=function(file,...args){return file===link.resolved?Buffer.from('substituted'):read.call(this,file,...args);};try{assert.throws(()=>fixturePython(),/input bytes/);}finally{fs.readFileSync=read;}
  fs.symlinkSync(link.resolved,path.join(temp,'unknown'));assert.throws(()=>fixtureTree(temp),/tree symlink/);
 }finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('generated module go.mod is independently bound to trusted go.sum, not inferred from ZIP',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-mod-test-'));try{const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {trustedGoMod as fixtureMod};\n');const {fixtureMod}=await import(new URL('file://'+module));const crypto=await import('node:crypto'),raw=Buffer.from('module example.org/legacy\n'),h1='h1:'+crypto.createHash('sha256').update(crypto.createHash('sha256').update(raw).digest('hex')+'  go.mod\n').digest('base64');assert.equal(fixtureMod(raw,h1),h1);assert.throws(()=>fixtureMod(Buffer.from('module other\n'),h1));assert.throws(()=>fixtureMod(raw,undefined));}finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('owned Go env reports disabled GOENV as empty and refuses live roots or changed policy',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-env-test-'));try{const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {inspectOwnedGoEnvironment as fixtureEnv};\n');const {fixtureEnv}=await import(new URL('file://'+module));const base='/workspace/scratch/production-go-advisory-owned-inputs-v1',v={GOROOT:base+'/go',GOMODCACHE:base+'/module-cache',GOWORK:'off',GOENV:'',GOPROXY:'off',GOFLAGS:'-mod=readonly',GOTOOLCHAIN:'local',GOOS:'linux',GOARCH:'amd64',CGO_ENABLED:'0'};assert.doesNotThrow(()=>fixtureEnv(v));for(const change of [{GOROOT:'/workspace/scratch/toolchains/go'},{GOMODCACHE:'/home/agent/go/pkg/mod'},{GOENV:'/home/agent/.config/go/env'},{GOPROXY:'https://proxy.golang.org'},{CGO_ENABLED:'1'},{GOWORK:''}])assert.throws(()=>fixtureEnv({...v,...change}));}finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('owned snapshot refuses added, omitted, symlinked, changed or write-enabled members',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-drift-test-'));try{const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {writeBoundSnapshot as fixtureCopy,verifySnapshot as fixtureVerify};\n');const {fixtureCopy,fixtureVerify}=await import(new URL('file://'+module));const crypto=await import('node:crypto'),input=path.join(temp,'input');fs.writeFileSync(input,'authentic');const rows=[{path:input,destination:'repo/input',bytes:9,mode:0o400,sha256:crypto.createHash('sha256').update('authentic').digest('hex')}];for(const change of ['extra','missing','symlink','changed','mode']){const out=path.join(temp,change);fixtureCopy(out,rows);const file=path.join(out,'repo/input');if(change==='extra')fs.writeFileSync(path.join(out,'extra'),'unapproved');if(change==='missing')fs.rmSync(file);if(change==='symlink'){fs.rmSync(file);fs.symlinkSync(input,file);}if(change==='changed'){fs.chmodSync(file,0o600);fs.writeFileSync(file,'malicious');fs.chmodSync(file,0o400);}if(change==='mode')fs.chmodSync(file,0o600);assert.throws(()=>fixtureVerify(out,rows));}}finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('preflight catches ignored extra Go source before any metadata import',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-extra-go-test-'));try{const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {checkGoRoster as fixtureRoster};\n');const {fixtureRoster}=await import(new URL('file://'+module));const tree=path.join(temp,'repo');fs.mkdirSync(tree);fs.writeFileSync(path.join(tree,'main.go'),'package main');assert.doesNotThrow(()=>fixtureRoster(tree,['main.go']));fs.mkdirSync(path.join(tree,'.ignored'));fs.writeFileSync(path.join(tree,'.ignored','payload.go'),'package malicious');assert.throws(()=>fixtureRoster(tree,['main.go']),/extra or missing Go source/);}finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('patched-only runner receipts reject failure, future times, protocol and consumed-byte corruption',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-receipt-test-'));try{const crypto=await import('node:crypto'),library='/usr/bin/python3.13',bytes=fs.readFileSync(library);const base={format:'production-advisory-owned-runner-v1',mode:'fixture',childExit:0,stdoutBase64:Buffer.from('[]').toString('base64'),stdoutSHA256:crypto.createHash('sha256').update('[]').digest('hex'),stderrSHA256:crypto.createHash('sha256').update('').digest('hex'),timeout:false,overflow:false,terminated:false,preexistingZombies:[],newSurvivors:[],adoptedReaped:0,waitJoined:true,releaseAccepted:false,runtimeInputs:[{path:library,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}],preProcessIDs:[],postProcessIDs:[]};const runner=path.join(temp,'receipt.py');const fixture=path.join(temp,'receipt.json');fs.writeFileSync(runner,'import json,datetime\nr=json.load(open('+JSON.stringify(fixture)+'))\nn=datetime.datetime.now(datetime.timezone.utc).isoformat()\nr.setdefault("startedAt",n);r.setdefault("endedAt",n)\nprint(json.dumps(r))\n');let source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8').replace("const RUNNER=path.join(ROOT,'scripts/production-advisory-owned-runner-v1.py');",'const RUNNER='+JSON.stringify(runner)+';').replaceAll('assertTools();','void 0;');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {owned as fixtureOwned};\n');const {fixtureOwned}=await import(new URL('file://'+module));fs.writeFileSync(fixture,JSON.stringify(base));assert.equal(fixtureOwned('fixture').raw.toString(),'[]');for(const change of [{childExit:1},{timeout:true},{overflow:true},{terminated:true},{waitJoined:false},{releaseAccepted:true},{startedAt:'2099-01-01T00:00:00Z',endedAt:'2099-01-01T00:00:00Z'},{stdoutSHA256:'0'.repeat(64)},{stdoutBase64:'invalidbase64'},{mode:'unlisted'},{unknown:'caller'},{preProcessIDs:[{pid:-1,ppid:0,start:'1',state:'S'}]}]){fs.writeFileSync(fixture,JSON.stringify({...base,...change}));assert.throws(()=>fixtureOwned('fixture'),/advisory component refused/);}}finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('package closure authority ignores ephemeral Go cache report fields and binds source membership',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-graph-test-'));try{const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {packageClosureSHA as fixtureClosure};\n');const {fixtureClosure}=await import(new URL('file://'+module));const p={ImportPath:'example/pkg',Dir:'/example/pkg',GoFiles:['a.go'],EmbedFiles:[],Standard:false,Module:{Path:'example',Version:'v1.0.0'}};assert.equal(fixtureClosure([{...p,Export:'/first/cache',Stale:true}]),fixtureClosure([{...p,Export:'/second/cache',Stale:false}]));assert.notEqual(fixtureClosure([p]),fixtureClosure([{...p,GoFiles:['a.go','extra.go']}]));assert.notEqual(fixtureClosure([p]),fixtureClosure([{...p,Module:{...p.Module,Version:'v1.0.1'}}]));}finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('fixed Git source authority ignores repository replacement-object overrides',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-git-test-'));try{const repo=path.join(temp,'repo');fs.mkdirSync(repo);const env={PATH:'/usr/bin:/bin',LANG:'C',LC_ALL:'C',GIT_AUTHOR_NAME:'Fixture',GIT_AUTHOR_EMAIL:'fixture@example.invalid',GIT_COMMITTER_NAME:'Fixture',GIT_COMMITTER_EMAIL:'fixture@example.invalid'};const git=args=>{const r=spawnSync('/usr/bin/git',args,{cwd:repo,env,encoding:'utf8'});assert.equal(r.status,0);return r.stdout.trim();};git(['init','-q']);fs.writeFileSync(path.join(repo,'input.go'),'original');git(['add','input.go']);git(['commit','-qm','fixture one']);const a=git(['rev-parse','HEAD']);fs.writeFileSync(path.join(repo,'input.go'),'replacement');git(['add','input.go']);git(['commit','-qm','fixture two']);const b=git(['rev-parse','HEAD']);git(['replace',a,b]);const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8').replace("const ROOT='/workspace/zasp-sec';",'const ROOT='+JSON.stringify(repo)+';');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {fixedCommand as fixtureGit};\n');const {fixtureGit}=await import(new URL('file://'+module));assert.equal(fixtureGit(['show',a+':input.go']).toString(),'original');}finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('every external consumed package file joins exact normal-ZIP authenticated member',async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-join-test-'));try{const source=fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8');const module=path.join(temp,'checker.mjs');fs.writeFileSync(module,source+'\nexport {bindExternalPackageInputs as fixtureJoin};\n');const {fixtureJoin}=await import(new URL('file://'+module));const row={path:'/home/agent/go/pkg/mod/example@v1.0.0/pkg/file.go',bytes:1,sha256:'a'.repeat(64)};assert.doesNotThrow(()=>fixtureJoin([row],[row]));assert.throws(()=>fixtureJoin([row],[]));assert.throws(()=>fixtureJoin([{...row,sha256:'b'.repeat(64)}],[row]));}finally{fs.rmSync(temp,{recursive:true,force:true});}
});

// Public OSV data copied into a self-contained unit fixture; no scan receipt authority.
const relatedPublicFixture={"schema_version":"1.3.1","id":"GO-2023-2102","modified":"2024-05-20T16:03:47Z","published":"2023-10-11T16:49:53Z","aliases":["CVE-2023-39325","GHSA-4374-p667-p6c8"],"related":["CVE-2023-44487"],"summary":"HTTP/2 rapid reset can cause excessive work in net/http","details":"A malicious HTTP/2 client which rapidly creates requests and immediately resets them can cause excessive server resource consumption. While the total number of requests is bounded by the http2.Server.MaxConcurrentStreams setting, resetting an in-progress request allows the attacker to create a new request while the existing one is still executing.\n\nWith the fix applied, HTTP/2 servers now bound the number of simultaneously executing handler goroutines to the stream concurrency limit (MaxConcurrentStreams). New requests arriving when at the limit (which can only happen after the client has reset an existing, in-flight request) will be queued until a handler exits. If the request queue grows too large, the server will terminate the connection.\n\nThis issue is also fixed in golang.org/x/net/http2 for users manually configuring HTTP/2.\n\nThe default stream concurrency limit is 250 streams (requests) per HTTP/2 connection. This value may be adjusted using the golang.org/x/net/http2 package; see the Server.MaxConcurrentStreams setting and the ConfigureServer function.","affected":[{"package":{"name":"stdlib","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"1.20.10"},{"introduced":"1.21.0-0"},{"fixed":"1.21.3"}]}],"ecosystem_specific":{"imports":[{"path":"net/http","symbols":["ListenAndServe","ListenAndServeTLS","Serve","ServeTLS","Server.ListenAndServe","Server.ListenAndServeTLS","Server.Serve","Server.ServeTLS","http2Server.ServeConn","http2serverConn.processHeaders","http2serverConn.runHandler","http2serverConn.serve","http2serverConn.upgradeRequest"]}]}},{"package":{"name":"golang.org/x/net","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"0.17.0"}]}],"ecosystem_specific":{"imports":[{"path":"golang.org/x/net/http2","symbols":["Server.ServeConn","serverConn.processHeaders","serverConn.runHandler","serverConn.serve","serverConn.upgradeRequest"]}]}}],"references":[{"type":"REPORT","url":"https://go.dev/issue/63417"},{"type":"FIX","url":"https://go.dev/cl/534215"},{"type":"FIX","url":"https://go.dev/cl/534235"},{"type":"WEB","url":"https://groups.google.com/g/golang-announce/c/iNNxDTCjZvo/m/UDd7VKQuAAAJ"}],"database_specific":{"url":"https://pkg.go.dev/vuln/GO-2023-2102","review_status":"REVIEWED"}};

async function relatedPrivateHelpers(){const temp=fs.mkdtempSync(path.join(os.tmpdir(),'advisory-related-unit-'));const module=path.join(temp,'fixture.mjs');fs.writeFileSync(module,fs.readFileSync(new URL('./collect-production-go-advisory-evidence-v1.mjs',import.meta.url),'utf8')+'\nexport {bindDatabaseAdvisory as fixtureBind,validateScannerModuleInventory as fixtureModules};\n');return {temp,api:await import(new URL('file://'+module))};}
async function relatedUnitRow(document){const crypto=await import('node:crypto');const raw=Buffer.from(JSON.stringify(document)+'\n');return {raw,row:{path:'ID/'+document.id+'.json',bytes:raw.length,sha256:crypto.createHash('sha256').update(raw).digest('hex')}};}
test('related omission retains exact authoritative DB bytes/full document and reported OSV',async()=>{const f=await relatedPrivateHelpers();try{const document=structuredClone(relatedPublicFixture),reported=structuredClone(document);delete reported.related;const {raw,row}=await relatedUnitRow(document);const binding=f.api.fixtureBind(reported,raw,row);assert.equal(binding.relatedOmittedByReporter,true);assert.equal(binding.rawBase64,raw.toString('base64'));assert.equal(binding.bytes,raw.length);assert.equal(binding.sha256,row.sha256);assert.deepEqual(binding.document,document);assert.deepEqual(binding.document.related,relatedPublicFixture.related);assert.deepEqual(binding.reportedOSV,reported);assert.equal(f.api.fixtureBind(document,raw,row).relatedOmittedByReporter,false);}finally{fs.rmSync(f.temp,{recursive:true,force:true});}});
test('related exception keeps aliases/ranges/severity/database_specific and unknown keys strictly equal',async()=>{const f=await relatedPrivateHelpers();try{const document={...structuredClone(relatedPublicFixture),aliases:['unit-A','unit-B'],severity:[{type:'CVSS_V3',score:'unit-fixture-only'}],unknown_metadata:{retained:['original']}};const reported=structuredClone(document);delete reported.related;const {raw,row}=await relatedUnitRow(document);assert.deepEqual(f.api.fixtureBind(reported,raw,row).document,document);for(const mutate of [x=>x.aliases.reverse(),x=>x.affected[0].ranges=[],x=>x.severity[0].score='changed',x=>x.database_specific={changed:true},x=>delete x.unknown_metadata,x=>x.related=['changed']]){const changed=structuredClone(reported);mutate(changed);assert.throws(()=>f.api.fixtureBind(changed,raw,row),/consumed advisory differs from pinned database/);}}finally{fs.rmSync(f.temp,{recursive:true,force:true});}});
test('related omission refuses invalid schema/array and wrong raw DB size/hash/member identity',async()=>{const f=await relatedPrivateHelpers();try{for(const related of [null,[],{},[''],[42]]){const document={...structuredClone(relatedPublicFixture),related};const reported=structuredClone(document);delete reported.related;const {raw,row}=await relatedUnitRow(document);assert.throws(()=>f.api.fixtureBind(reported,raw,row));}const document={...structuredClone(relatedPublicFixture),schema_version:'unknown'};const reported=structuredClone(document);delete reported.related;const invalid=await relatedUnitRow(document);assert.throws(()=>f.api.fixtureBind(reported,invalid.raw,invalid.row));const valid=structuredClone(relatedPublicFixture),report=structuredClone(valid);delete report.related;const {raw,row}=await relatedUnitRow(valid);for(const changed of [{...row,sha256:'0'.repeat(64)},{...row,bytes:row.bytes+1},{...row,path:'ID/GO-0000-0.json'}])assert.throws(()=>f.api.fixtureBind(report,raw,changed));}finally{fs.rmSync(f.temp,{recursive:true,force:true});}});
test('stdlib SBOM role is v1.25.13 with exact nonstdlib modules and compiler go1.25.13',async()=>{const f=await relatedPrivateHelpers();try{const sbom={go_version:'go1.25.13',modules:[{path:'stdlib',version:'v1.25.13'},{path:'example/module',version:'v1.0.0'}],roots:['example/module']};const before={modules:{'services/health':{packages:[{standard:true},{module:{Path:'example/module',Version:'v1.0.0'}}]}}};assert.doesNotThrow(()=>f.api.fixtureModules(sbom,before,'services/health'));for(const [modulePath,version]of [['stdlib','v1.25.12'],['stdlib','v1.25.14'],['stdlib','go1.25.13'],['wrong-stdlib','v1.25.13']]){const changed=structuredClone(sbom);Object.assign(changed.modules[0],{path:modulePath,version});assert.throws(()=>f.api.fixtureModules(changed,before,'services/health'));}const changed=structuredClone(sbom);changed.modules[1].version='v99.0.0';assert.throws(()=>f.api.fixtureModules(changed,before,'services/health'));const stream=messages();stream[1].SBOM=sbom;stream.splice(3,0,structuredClone(stream[2]));const a=await api(),inspection=a.inspectGoScanStream(wire(stream));assert.equal(inspection.config.go_version,'go1.25.13');assert.equal(inspection.messageCounts.osv,2);assert.equal(inspection.advisories.length,1);assert.equal(inspection.findings[0].severity,'UNKNOWN');assert.equal(inspection.releaseAccepted,false);assert.equal(inspection.fullMVSClearance,false);stream[0].config.go_version='go1.25.14';assert.throws(()=>a.inspectGoScanStream(wire(stream)),/scanner protocol\/config/);}finally{fs.rmSync(f.temp,{recursive:true,force:true});}});

test('replacement version role uses its own version or null while original requirements and exact local multiplicity remain',async()=>{const f=await relatedPrivateHelpers();try{const root='services/platform',module={Path:'original/health',Version:'v0.0.0',Replace:{Path:'../health'}};const before={modules:{[root]:{packages:[{module}]}}};assert.doesNotThrow(()=>f.api.fixtureModules({modules:[{path:'../health'}]},before,root));assert.equal(module.Version,'v0.0.0');for(const row of [{path:'../health',version:'v0.0.0'},{path:'original/health',version:'v0.0.0'},{path:'../wrong'}])assert.throws(()=>f.api.fixtureModules({modules:[row]},before,root));const versioned={modules:{[root]:{packages:[{module:{Path:'original/module',Version:'v9.0.0',Replace:{Path:'replacement/module',Version:'v1.2.3'}}}]}}};assert.doesNotThrow(()=>f.api.fixtureModules({modules:[{path:'replacement/module',version:'v1.2.3'}]},versioned,root));for(const version of [undefined,'v9.0.0','v1.2.4'])assert.throws(()=>f.api.fixtureModules({modules:[{path:'replacement/module',version}]},versioned,root));const original={modules:{[root]:{packages:[{module:{Path:'original/module',Version:'v9.0.0'}}]}}};assert.doesNotThrow(()=>f.api.fixtureModules({modules:[{path:'original/module',version:'v9.0.0'}]},original,root));assert.throws(()=>f.api.fixtureModules({modules:[{path:'original/module'}]},original,root));const stream=messages();stream[1].SBOM={go_version:'go1.25.13',roots:['github.com/zasp-ai/zasp-sec/services/platform'],modules:[{path:'stdlib',version:'v1.25.13'},{path:'../health'},{path:'../health'}]};const a=await api();assert.equal(a.inspectGoScanStream(wire(stream)).sbom.modules.filter(m=>m.path==='../health').length,2);for(const count of [1,3]){const changed=structuredClone(stream);changed[1].SBOM.modules=[{path:'stdlib',version:'v1.25.13'},...Array.from({length:count},()=>({path:'../health'}))];assert.throws(()=>a.inspectGoScanStream(wire(changed)),count===1?/closed local replacement multiplicity/:/SBOM module inventory/);}}finally{fs.rmSync(f.temp,{recursive:true,force:true});}});
