import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
const file=new URL('./collect-production-go-advisory-evidence-v2.mjs',import.meta.url);
const fixture=new URL('./.private-pure-fixture.mjs',import.meta.url);
fs.writeFileSync(fixture,fs.readFileSync(file,'utf8')+'\nexport {bindDatabaseAdvisory,validateScannerModuleInventory,helperBufferArgs};\n',{flag:'wx'});
let api;try {api=await import(fixture);} finally {fs.unlinkSync(fixture);}
const wire=x=>Buffer.from(x.map(x=>JSON.stringify(x)).join('\n')+'\n');
const config={protocol_version:'v1.0.0',scanner_name:'govulncheck',scanner_version:'v1.7.0',db:'file:///workspace/scratch/official-go-vulndb-generated',db_last_modified:'2026-10-01T20:24:15Z',go_version:'go1.26.8',scan_level:'package',scan_mode:'source'};
const messages=()=>[{config:{...config}},{SBOM:{go_version:'go1.26.8',modules:[{path:'stdlib',version:'v1.26.8'}],roots:['synthetic/root']}},{osv:{id:'GO-2026-5932',schema_version:'1.3.1',modified:'2026-10-01T20:24:15Z',affected:[]}},{finding:{osv:'GO-2026-5932',trace:[{module:'stdlib',version:'v1.26.8'}]}}];
test('V2 exact compiler stream keeps UNKNOWN and component-only findings/multiplicity',()=>{const m=messages();m.push(structuredClone(m[2]),structuredClone(m[3]));const r=api.inspectGoScanStream(wire(m));assert.equal(r.config.go_version,'go1.26.8');assert.equal(r.findings[0].severity,'UNKNOWN');assert.equal(r.findings.length,2);assert.equal(r.advisories.length,1);assert.equal(r.messageCounts.osv,2);assert.equal(r.releaseAccepted,false);assert.equal(r.fullMVSClearance,false);assert.equal(api.inspectGoScanStream(wire(messages().slice(0,2))).releaseAccepted,false);});
test('V2 rejects old/nearby/development compiler in config and SBOM',()=>{for(const v of ['go1.25.13','go1.26.5','go1.26.7','go1.26.9','devel go1.26'])for(const i of [0,1]){const m=messages();m[i][i===0?'config':'SBOM'].go_version=v;assert.throws(()=>api.inspectGoScanStream(wire(m)),/refused/);}});
test('stdlib module exact semver role stays distinct from compiler',()=>{const before={modules:{'services/health':{packages:[{standard:true}]}}};api.validateScannerModuleInventory({modules:[{path:'stdlib',version:'v1.26.8'}]},before,'services/health');for(const version of ['go1.26.8','v1.25.13','v1.26.5','v1.26.9',null])assert.throws(()=>api.validateScannerModuleInventory({modules:[{path:'stdlib',version}]},before,'services/health'),/inventory mismatch/);});
test('strict OSV-related omission retains full authoritative bytes and all security fields',()=>{const db={id:'GO-2026-5932',schema_version:'1.3.1',modified:'2026-10-01T20:24:15Z',related:['CVE-2026-0001'],aliases:['GHSA-synthetic'],affected:[{ranges:[{type:'SEMVER',events:[{introduced:'0'}]}]}],severity:[],database_specific:{review_status:'REVIEWED'}};const raw=Buffer.from(JSON.stringify(db)),row={path:'ID/'+db.id+'.json',bytes:raw.length,sha256:crypto.createHash('sha256').update(raw).digest('hex')},reported={...db};delete reported.related;const r=api.bindDatabaseAdvisory(reported,raw,row);assert.deepEqual(r.document,db);assert.equal(r.rawBase64,raw.toString('base64'));assert.equal(r.relatedOmittedByReporter,true);for(const key of ['aliases','affected','severity','database_specific']){const changed={...reported,[key]:[]};if(JSON.stringify(changed)===JSON.stringify(reported))changed[key]=['changed'];assert.throws(()=>api.bindDatabaseAdvisory(changed,raw,row),/differs/);}assert.throws(()=>api.bindDatabaseAdvisory({...reported,unknown:'extra'},raw,row),/differs/);assert.throws(()=>api.bindDatabaseAdvisory(reported,Buffer.concat([raw,Buffer.from(' ')]),row),/differs/);});
test('local replacement null, versioned replacement and original version roles remain exact',()=>{const root='services/platform';for(const [module,expected]of [[{Path:'original',Version:'v0.0.0',Replace:{Path:'../health'}},['../health',null]],[{Path:'original',Version:'v1.0.0',Replace:{Path:'replacement',Version:'v2.0.0'}},['replacement','v2.0.0']],[{Path:'original',Version:'v1.0.0'},['original','v1.0.0']]]){const before={modules:{[root]:{packages:[{module}]}}};api.validateScannerModuleInventory({modules:[{path:expected[0],...(expected[1]===null?{}:{version:expected[1]})}]},before,root);assert.throws(()=>api.validateScannerModuleInventory({modules:[{path:expected[0],version:'v9.0.0'}]},before,root),/inventory mismatch/);}});
test('strict malformed/protocol/unknown-field stream refuses without child execution',()=>{for(const change of [m=>m[0].config.extra='x',m=>m[0].config.scan_level='symbol',m=>m[1].SBOM.modules.push({...m[1].SBOM.modules[0]}),m=>m[3].finding.osv='GO-UNKNOWN',m=>m.push({error:{message:'synthetic'}})]){const m=messages();change(m);assert.throws(()=>api.inspectGoScanStream(wire(m)),/refused/);}assert.throws(()=>api.inspectGoScanStream(Buffer.from('{"config":{},"config":{}}')),/refused/);assert.throws(()=>api.inspectGoScanStream(wire(messages()).subarray(0,-3)),/refused/);});
test('fixed reviewed source and manifest refuse caller authority before tools',()=>{assert.throws(()=>api.deriveProductionGoAdvisoryManifestV2(),/owned Node tool authority/);assert.throws(()=>api.collectProductionGoAdvisoryEvidenceV2({commit:'caller-selected'}),/caller authority/);const s=fs.readFileSync(file,'utf8');assert.match(s,/const SOURCE_COMMIT='142a52bcf5fa7752d5a0cd73c1b94d37332c5a89';/);assert.match(s,/const APPROVED_INPUT_MANIFEST_SHA256='070327bd3de4c86a6dd4579c570df8aa2ff929dbb720c058306ef3f5a8370811';/);assert.match(s,/production-go-advisory-owned-inputs-v2/);assert.match(s,/production-go-advisory-guarded-code-v2/);});

test('consumed helper buffer survives later file substitution and refuses changed bytes before launch',()=>{const raw=Buffer.from('# synthetic helper fixture\n'),pin=crypto.createHash('sha256').update(raw).digest('hex'),runner='/fixed/synthetic/runner.py';const args=api.helperBufferArgs(runner,'graph-health',raw,pin);assert.deepEqual(args.slice(0,4),['-I','-S','-B','-c']);assert.equal(args[5],raw.toString('base64'));assert.equal(args[6],runner);assert.equal(args[7],'graph-health');assert.match(args[4],/sys.argv=\[sys.argv\[2\],sys.argv\[3\]\]/);assert.match(args[4],/__file__/);assert.doesNotMatch(args[4],/open\(|read_bytes|read_text/);assert.throws(()=>api.helperBufferArgs(runner,'graph-health',Buffer.from('changed'),pin),/helper buffer/);assert.throws(()=>api.helperBufferArgs(runner,'arbitrary',raw,pin),/helper mode/);const source=fs.readFileSync(file,'utf8');assert.match(source,/const RUNNER=OWNED_CODE_PREFIX\+'\/runner.py';/);assert.match(source,/helperBufferArgs\(runner,mode,pinnedRead\(runner,TOOL_PINS\[RUNNER\]\),TOOL_PINS\[RUNNER\]\)/);});
