import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync}from 'node:fs';import {createRequire}from 'node:module';
import {closedOwnedAmbientEnvironment,OwnedProjectionCleanupIncomplete}from './owned-current80-composition.mjs';
const require=createRequire(new URL('../package.json',import.meta.url)),ts=require('typescript');
const source=readFileSync(new URL('./production-combined-e2e.mjs',import.meta.url),'utf8');
const ast=ts.createSourceFile('production-combined-e2e.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
function declaration(name){let result;function visit(node){if(ts.isFunctionDeclaration(node)&&node.name?.text===name)result=node;ts.forEachChild(node,visit);}visit(ast);assert.ok(result);return result;}
function variable(parent,name){let result;function visit(node){if(ts.isVariableDeclaration(node)&&node.name.getText(ast)===name)result=node.initializer;ts.forEachChild(node,visit);}visit(parent);assert.ok(result);return result.getText(ast);}
function builder(){return new Function('auditBrowserEnvironment','auditBrowserMode','auditBrowserAPISettings','stytchWebhookSecret',`return (${declaration('combinedAPIEnvironment').getText(ast)});`)(value=>value,false,()=>({}),'fixture-binding');}
test('actual parsed environment builder receives closed owned ambient inputs',()=>{const build=builder();const value=build({apiDSN:'postgres://zasp_e2e_api@127.0.0.1:32100/postgres?sslmode=disable',postgresPort:32100,identityPort:32101,policyHistoryPort:32102,apiPort:32103,healthPort:32104,publicOrigin:'https://fixture.invalid:32105',ownedAmbient:closedOwnedAmbientEnvironment({PATH:'/usr/bin',ZASP_COMPLIANCE_EXPORT_ROLE_ARN:'ambient',ZASP_ORGANIZATION_ID:'ambient'})});assert.equal(Object.hasOwn(value,'ZASP_COMPLIANCE_EXPORT_ROLE_ARN'),false);assert.equal(value.ZASP_ORGANIZATION_ID,'');assert.match(value.ZASP_SECURITY_AGENT_POSTGRES_DSN,/:32100\/postgres\?/);});
test('actual parsed initial legacy and enabled restart preserve same real runtime/model and both database identities',async()=>{
 const body=declaration('exerciseComplianceBrowser'),envExpression=variable(body,'apiEnvironment'),startExpression=variable(body,'startAPI');
 const launches=[],runtime={ZASP_RUNTIME_SERVICES_ENABLED:'true',ZASP_TEMPORAL_NAMESPACE:'owned-current',ZASP_OPENFGA_STORE_ID:'owned-store',ZASP_OPENFGA_MODEL_ID:'owned-model'};
 const config={apiDSN:'postgres://zasp_e2e_api@127.0.0.1:32100/postgres?sslmode=disable',postgresPort:32100,identityPort:32101,policyHistoryPort:32102,apiPort:32103,healthPort:32104,currentRuntimeEnvironment:runtime};
 const execute=new Function('configuration','combinedAPIEnvironment','closedOwnedAmbientEnvironment','startChild','waitForHTTP','emitComplianceAPIChildFailure',`let compliancePhase='fixture',api;const complianceBrowserMode=true,publicOrigin='https://fixture.invalid:32105',postgresPort=32100,healthPort=32104,apiBinary='/owned/api',object='/tmp/zasp-compliance-browser-control/object';const apiEnvironment=${envExpression};const startAPI=${startExpression};return startAPI;`);
 const start=execute(config,builder(),closedOwnedAmbientEnvironment,(_binary,_args,options)=>{launches.push(options.env);return {output:()=>''};},async()=>{},()=>assert.fail('no failure expected'));
 await start(false);await start(true);await start(true);assert.equal(launches.length,3);
 for(const env of launches){assert.equal(env.ZASP_RUNTIME_SERVICES_ENABLED,'true');assert.equal(env.ZASP_TEMPORAL_NAMESPACE,'owned-current');assert.equal(env.ZASP_OPENFGA_STORE_ID,'owned-store');assert.equal(env.ZASP_OPENFGA_MODEL_ID,'owned-model');assert.equal(env.ZASP_POSTGRES_DSN,config.apiDSN);assert.match(env.ZASP_SECURITY_AGENT_POSTGRES_DSN,/:32100\/postgres\?/);}
 assert.equal(Object.keys(launches[0]).some(key=>key.startsWith('ZASP_COMPLIANCE_EXPORT_')),false);assert.equal(launches[0].ZASP_COMPLIANCE_BROWSER_LEGACY,'true');assert.equal(Object.hasOwn(launches[1],'ZASP_COMPLIANCE_BROWSER_LEGACY'),false);assert.ok(Object.hasOwn(launches[1],'ZASP_COMPLIANCE_EXPORT_BUCKET'));
});
test('actual command cancellation awaits stop finalization after early child completion',async()=>{
 let resolveResult,finishStop,called;const completed=new Promise(resolve=>{resolveResult=resolve;}),ready=new Promise(resolve=>{called=resolve;});
 const owner={child:{},completed,stop:()=>{called();return new Promise(resolve=>{finishStop=resolve;});}};
 const command=new Function('spawnOwnedCommand','OwnedProjectionCleanupIncomplete',`const existingTestMountedMode=false,currentComplianceFailure=undefined,currentComplianceClosing=false,currentComplianceServices=undefined,root='/owned',temporaryRoot='/owned',children=[],ownedCommands=new Map();const auditBrowserEnvironment=()=>({}),browserCommandFailureAnnotation=()=>'';return (${declaration('command').getText(ast)});`)(()=>owner,OwnedProjectionCleanupIncomplete);
 const controller=new AbortController();let settled=false;const running=command('/owned/reconcile',[],{signal:controller.signal}).then(()=>{settled=true;});controller.abort();await ready;resolveResult({status:0,signal:null,stdout:'',stderr:''});await new Promise(resolve=>setImmediate(resolve));assert.equal(settled,false);finishStop();await running;assert.equal(settled,true);
});
test('current fixture is actually consumed before either API lifetime and reverse close precedes current PG deletion',()=>{const exercise=declaration('exerciseComplianceBrowser').getText(ast),cleanup=declaration('cleanupOwnedResources').getText(ast);assert.ok(exercise.indexOf('prepareOwnedCurrentComplianceRuntime(')<exercise.indexOf('await startAPI(false)'));assert.match(exercise,/currentRuntimeEnvironment/);assert.ok(cleanup.indexOf('currentComplianceProjectionLoop')<cleanup.indexOf('currentComplianceServices.close'));assert.ok(cleanup.indexOf('currentComplianceServices.close')<cleanup.indexOf('currentCompliancePostgres.stop'));assert.ok(cleanup.indexOf('currentCompliancePostgres.stop')<cleanup.indexOf('rm(currentComplianceStateRoot'));});
test('actual runner command preserves rejection identity unless cancellation join is incomplete',async()=>{const build=owner=>new Function('spawnOwnedCommand','OwnedProjectionCleanupIncomplete',`const existingTestMountedMode=false,currentComplianceFailure=undefined,currentComplianceClosing=false,currentComplianceServices=undefined,root='/owned',temporaryRoot='/owned',children=[],ownedCommands=new Map();const auditBrowserEnvironment=()=>({}),browserCommandFailureAnnotation=()=>'';return (${declaration('command').getText(ast)});`)(()=>owner,OwnedProjectionCleanupIncomplete);const original=Error('owned producer refusal');for(const reason of [original,undefined]){const command=build({child:{},completed:Promise.reject(reason),stop:async()=>{}});await command('/owned/reconcile',[]).then(()=>assert.fail('producer refusal must not become success'),error=>assert.equal(error,reason));}let finish,enter;const ready=new Promise(r=>enter=r),command=build({child:{},completed:Promise.resolve({status:0,signal:null,stdout:'',stderr:''}),stop:()=>{enter();return new Promise((_,reject)=>finish=()=>reject(original));}});const controller=new AbortController();let settled=false;const pending=command('/owned/reconcile',[],{signal:controller.signal}).catch(error=>{settled=true;return error;});controller.abort();await ready;await new Promise(r=>setImmediate(r));assert.equal(settled,false);finish();assert.ok((await pending)instanceof OwnedProjectionCleanupIncomplete);});
