import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, rm, chmod } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';
import os from 'node:os';import path from 'node:path';import { pathToFileURL } from 'node:url';
import { heldToolName } from './official-held-tools.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
function tar(){const body=Buffer.alloc(64);Buffer.from([127,69,76,70,2,1]).copy(body);body.writeUInt16LE(2,16);body.writeUInt16LE(62,18);const header=Buffer.alloc(512);header.write('temporal');for(const [start,length,value]of [[100,8,0o500],[108,8,0],[116,8,0],[124,12,body.length],[136,12,0]])header.write(value.toString(8).padStart(length-1,'0')+'\0',start);header.fill(32,148,156);header.write('0',156);header.write('ustar\0',257);header.write('00',263);header.write([...header].reduce((a,b)=>a+b,0).toString(8).padStart(6,'0')+'\0 ',148);const license=Buffer.from(header);license.fill(0,0,100);license.write('LICENSE');license.fill(0,124,136);license.write('00000000001\0',124);license.fill(32,148,156);license.write([...license].reduce((a,b)=>a+b,0).toString(8).padStart(6,'0')+'\0 ',148);return {archive:gzipSync(Buffer.concat([license,Buffer.from('x'),Buffer.alloc(511),header,body,Buffer.alloc(448),Buffer.alloc(1024)])),body};}
async function fixture(mutant){
 const root=await mkdtemp(path.join(os.tmpdir(),'zasp-held-custody-test-'));const {archive,body}=tar();let source=await readFile(new URL('./official-held-tools.mjs',import.meta.url),'utf8');
 // Isolated test-only source fixture. Production official pins are never edited.
 source=source.replace("sha:'09a0326a51db84d02735e53542b9ebd8c4758daf47482a9ab0abce15844e60d5',compressed:45298806",`sha:'${hash(archive)}',compressed:${archive.length}`);
 if(mutant==='hash')source=source.replace('||digest(read.bytes)!==state.sha','');
 await writeFile(path.join(root,'official-held-tools.mjs'),source);
 let owned=await readFile(new URL('./owned-fixed-fd-command.mjs',import.meta.url),'utf8');owned=owned.replace('from "node:child_process"','from "./finite-spawn.mjs"');if(mutant==='path')owned=owned.replace('"/proc/self/fd/3"','"/unowned/caller/tool"');await writeFile(path.join(root,'owned-fixed-fd-command.mjs'),owned);
 await writeFile(path.join(root,'finite-spawn.mjs'),`import {EventEmitter} from 'node:events';import {fstatSync}from'node:fs';export const observations=[];export function spawn(executable,args,options){const child=new EventEmitter();child.stdin=new EventEmitter();child.stdin.end=()=>{};child.stdout=new EventEmitter();child.stderr=new EventEmitter();observations.push({executable,stdio:options.stdio,inode:fstatSync(options.stdio[3]).ino});setImmediate(()=>{child.emit('spawn');child.emit('close',0,null);});return child;}`);
 await writeFile(path.join(root,'archive.tar.gz'),archive,{mode:0o400});const module=await import(pathToFileURL(path.join(root,'official-held-tools.mjs')).href);const spawn=await import(pathToFileURL(path.join(root,'finite-spawn.mjs')).href);
 return {root,body,module,spawn,load:()=>module.loadOfficialHeldTool('temporal',path.join(root,'archive.tar.gz'),path.join(root,'extracted')),cleanup:()=>rm(root,{recursive:true,force:true})};
}
test('caller descriptor cannot mint held official capability',()=>assert.throws(()=>heldToolName({name:'temporal',sha256:'a'.repeat(64),fd:3})));
test('consumed archive member is linked to held inode and fixed fd3 execution path',async()=>{const f=await fixture();let tool;try{tool=await f.load();const receipt=await f.module.verifyHeldTool(tool);assert.equal(receipt.memberSHA256,hash(f.body));assert.equal(receipt.member,'temporal');assert.equal(receipt.protectedNativeAuthority,false);const owner=await f.module.spawnHeldTool(tool,[],{env:{PATH:'/usr/bin:/bin'}});await owner.completed;await owner.stop();assert.equal(f.spawn.observations[0].executable,'/proc/self/fd/3');assert.equal(f.spawn.observations[0].stdio.length,4);assert.equal(f.spawn.observations[0].inode,receipt.inode);await f.module.closeHeldTool(tool);assert.throws(()=>f.module.heldToolName(tool));}finally{if(tool)await f.module.closeHeldTool(tool).catch(()=>{});await f.cleanup();}});
test('consumed byte mutation refuses before any spawn',async()=>{const f=await fixture();try{const tool=await f.load();const file=path.join(f.root,'extracted','temporal');await chmod(file,0o700);const changed=Buffer.from(f.body);changed[60]=1;await writeFile(file,changed);await chmod(file,0o500);await assert.rejects(f.module.spawnHeldTool(tool,[]));assert.equal(f.spawn.observations.length,0);await assert.rejects(f.module.closeHeldTool(tool));}finally{await f.cleanup();}});
for(const mutant of ['hash','path'])test('substantive '+mutant+' guard mutant fails its boundary',async()=>{const f=await fixture(mutant);try{const tool=await f.load();if(mutant==='hash'){const file=path.join(f.root,'extracted','temporal');await chmod(file,0o700);const changed=Buffer.from(f.body);changed[60]=1;await writeFile(file,changed);await chmod(file,0o500);await assert.rejects(async()=>{await assert.rejects(f.module.spawnHeldTool(tool,[]));});}else{const owner=await f.module.spawnHeldTool(tool,[]);await owner.completed;await assert.rejects(async()=>assert.equal(f.spawn.observations[0].executable,'/proc/self/fd/3'));}await f.module.closeHeldTool(tool);}finally{await f.cleanup();}});
