import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm}from 'node:fs/promises';
import {createHash}from 'node:crypto';
const actualVersions=JSON.parse(await readFile(new URL('./official-runtime-version-output.json',import.meta.url),'utf8'));
const decodedVersion=name=>{const row=actualVersions[name],stdout=Buffer.from(row.stdoutBase64,'base64'),stderr=Buffer.from(row.stderrBase64,'base64');assert.equal(stdout.length,row.stdoutBytes);assert.equal(stderr.length,row.stderrBytes);assert.equal(createHash('sha256').update(stdout).digest('hex'),row.stdoutSHA256);assert.equal(createHash('sha256').update(stderr).digest('hex'),row.stderrSHA256);return {status:row.exit,signal:row.signal,outputLimitExceeded:row.outputLimitExceeded,stdout:stdout.toString(),stderr:stderr.toString()};};import os from 'node:os';import path from 'node:path';import {createRequire}from 'node:module';
const implementation=await import('./hosted-runtime-tool-intake.mjs').catch(error=>{if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;return {};});
const require=createRequire(new URL('../package.json',import.meta.url)),yaml=require('js-yaml');

function canonicalWorkflowValue(value){if(Array.isArray(value))return value.map(canonicalWorkflowValue);if(value!==null&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonicalWorkflowValue(value[key])]));return value;}
function predecessorStepsSHA(steps){return createHash('sha256').update(JSON.stringify(canonicalWorkflowValue(steps))).digest('hex');}
function validatedNotificationDeliveryStep(steps){
 const name='Verify approval maintenance signed notification delivery';
 const matches=steps.map((step,index)=>step.name===name?index:-1).filter(index=>index>=0);
 assert.equal(matches.length,1);const index=matches[0];
 assert.deepEqual(steps[index],{name,'timeout-minutes':10,run:"go test -C services/platform -race -p 1 -count=1 -timeout=5m -json -run '^TestMaintenanceBoundary(DeliversOriginalSignedPayloadOverTLS|UnsafeDeliveryDoesNotReachHTTP|RetainsActualProviderFailure)$' ./apiserver\n"});
 const prime=steps.findIndex(step=>step.name==='Prime platform full-MVS metadata for offline release contracts');
 const verify=steps.findIndex(step=>step.name==='Verify runnable UI');
 assert.ok(prime>=0&&index===prime+1&&verify===index+1);return index;
}
function validatedInnerDiagnosticStep(steps){
 const matches=steps.map((step,index)=>step.name==='Verify current runtime profile inner diagnostic tests'?index:-1).filter(index=>index>=0);assert.equal(matches.length,1);const index=matches[0];
 assert.deepEqual(steps[index],{name:'Verify current runtime profile inner diagnostic tests','timeout-minutes':5,run:'node --test scripts/observe-current-profile-inner-diagnostics.test.mjs\nnode scripts/observe-current-profile-inner-diagnostics.mjs\n'});
 const prime=steps.findIndex(step=>step.name==='Prime native migration compilation cache for compliance browser'),intake=steps.findIndex(step=>step.name==='Provision pinned owned authorization runtime tools'),browser=steps.findIndex(step=>step.name==='Verify current compliance browser acceptance');
 assert.ok(prime>=0&&prime<index&&index<intake&&intake<browser);return index;
}
async function fixture(t,options={}){const parent=await mkdtemp(path.join(os.tmpdir(),'zasp-ci-intake-test-'));t.after(()=>rm(parent,{recursive:true,force:true}));const env=path.join(parent,'github-env');await writeFile(env,'',{mode:0o600});const calls=[];let tick,closed=0;
 const adapters={create:async base=>{const root=path.join(base,'owned-intake');await mkdir(root,{mode:0o700});const archives=path.join(root,'archives'),raw=path.join(root,'raw');await mkdir(archives,{mode:0o700});await mkdir(raw,{mode:0o700});return {root,archives,raw};},observe:async()=>({free:10n*1024n**3n,allocated:100n}),run:async(exe,args,settings,signal)=>{calls.push({type:'download',exe,args,settings});assert.equal(signal.aborted,false);if(options.downloadFailure)throw Error('CANARY_TRANSPORT');await writeFile(args[args.indexOf('--output')+1],'fixture-boundary',{mode:0o400});},load:async(name,archive,directory)=>{calls.push({type:'load',name,archive,directory});if(options.loadFailure)throw Error('CANARY_ARCHIVE');return Object.freeze({name});},version:async(tool,args,settings,signal)=>{calls.push({type:'version',name:tool.name,args,settings});if(options.versionDeferred)return options.versionDeferred(signal);return {...decodedVersion(tool.name),status:options.nonzero?7:0};},close:async tool=>{calls.push({type:'close',name:tool.name});closed++;if(options.closeFailure)throw Error('CANARY_JOIN');},publish:async(file,bytes)=>{calls.push({type:'publish'});assert.equal(closed,2);await writeFile(file,bytes);},setTimer:cb=>{tick=cb;return 1;},clearTimer:()=>calls.push({type:'clear'})};
 return {parent,env,calls,adapters,tick:()=>tick()};}
const invoke=f=>implementation.prepareHostedRuntimeTools({runnerTemp:f.parent,githubEnv:f.env},f.adapters);
test('hosted workflow actually provisions pinned owned runtime inputs before original acceptance',async()=>{const workflow=yaml.load(await readFile(new URL('../.github/workflows/runnable-ui.yml',import.meta.url),'utf8'));const steps=workflow.jobs.verify.steps;const intake=steps.findIndex(x=>x.name==='Provision pinned owned authorization runtime tools');const browser=steps.findIndex(x=>x.name==='Verify current compliance browser acceptance');assert.ok(intake>=0&&intake<browser);assert.deepEqual(steps[intake],{name:'Provision pinned owned authorization runtime tools','timeout-minutes':5,run:'node scripts/hosted-runtime-tool-intake.mjs\n'});validatedInnerDiagnosticStep(steps);validatedNotificationDeliveryStep(steps);assert.equal(steps.length,37);});
test('real intake consumer orders fixed downloads, official capability loads, version joins then only two owned exports',async t=>{assert.equal(typeof implementation.prepareHostedRuntimeTools,'function');const f=await fixture(t);await invoke(f);const kinds=f.calls.map(x=>x.type);assert.deepEqual(kinds,['download','load','version','download','load','version','clear','close','close','publish']);const downloads=f.calls.filter(x=>x.type==='download');assert.deepEqual(downloads.map(x=>x.exe),['/usr/bin/curl','/usr/bin/curl']);assert.deepEqual(downloads.map(x=>x.args.at(-1)),['https://github.com/temporalio/cli/releases/download/v1.9.1/temporal_cli_1.9.1_linux_amd64.tar.gz','https://github.com/openfga/openfga/releases/download/v1.21.0/openfga_1.21.0_linux_amd64.tar.gz']);assert.deepEqual(downloads.map(x=>x.args[x.args.indexOf('--max-filesize')+1]),['45298806','21232870']);for(const x of downloads){assert.ok(x.args.includes('--proto-redir'));assert.ok(!x.args.some(a=>/authorization|header|user|netrc/i.test(a)));assert.equal(x.settings.timeout,95000);}const versions=f.calls.filter(x=>x.type==='version');assert.deepEqual(versions.map(x=>x.args),[['--version'],['version']]);for(const x of versions){assert.equal(x.settings.timeout,5000);assert.equal(x.settings.maxOutputBytes,16384);}assert.equal(await readFile(f.env,'utf8'),`ZASP_BROWSER_RUNTIME_ARCHIVE_ROOT=${f.parent}/owned-intake/archives\nZASP_BROWSER_RUNTIME_RAW_ROOT=${f.parent}/owned-intake/raw\n`);});
for(const [name,options]of [['download',{downloadFailure:true}],['archive',{loadFailure:true}],['version',{nonzero:true}],['close',{closeFailure:true}]])test(`intake ${name} refusal cannot publish retained paths or start services`,async t=>{assert.equal(typeof implementation.prepareHostedRuntimeTools,'function');const f=await fixture(t,options);await assert.rejects(invoke(f),{message:'hosted runtime tool intake unavailable'});assert.equal(await readFile(f.env,'utf8'),'');assert.ok(!f.calls.some(x=>x.type==='publish'));});
test('sampled resource failure aborts and awaits delayed version finalization before close and publication refusal',async t=>{assert.equal(typeof implementation.prepareHostedRuntimeTools,'function');let finalize,aborted,entered;const ready=new Promise(r=>entered=r),seenAbort=new Promise(r=>aborted=r);const f=await fixture(t,{versionDeferred:signal=>{entered();return new Promise(resolve=>{finalize=()=>resolve({status:0,signal:null,stdout:'temporal version 1.9.1\n',stderr:''});signal.addEventListener('abort',aborted,{once:true});});}});let observed=0;f.adapters.observe=async()=>({free:++observed===1?10n*1024n**3n:1n,allocated:100n});let settled=false;const running=invoke(f).catch(error=>{settled=true;return error;});await ready;f.tick();await seenAbort;await new Promise(r=>setImmediate(r));assert.equal(settled,false);assert.ok(!f.calls.some(x=>x.type==='close'||x.type==='publish'));finalize();assert.equal((await running).message,'hosted runtime tool intake unavailable');assert.ok(f.calls.some(x=>x.type==='close'));assert.ok(!f.calls.some(x=>x.type==='publish'));});
test('versions must match exact fixed service versions before environment export',async t=>{assert.equal(typeof implementation.prepareHostedRuntimeTools,'function');const f=await fixture(t);f.adapters.version=async()=>({status:0,signal:null,stdout:'temporal version 9.9.9 CANARY\n',stderr:''});await assert.rejects(invoke(f));assert.equal(await readFile(f.env,'utf8'),'');});
test('actual finite producer deadline awaits delayed stop finalization before returning refusal',async()=>{const ts=require('typescript'),source=await readFile(new URL('./hosted-runtime-tool-intake.mjs',import.meta.url),'utf8');const ast=ts.createSourceFile('intake.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);const node=ast.statements.find(x=>ts.isFunctionDeclaration(x)&&x.name.text==='finite');assert.ok(node);let timer,finishStop,complete;const completed=new Promise(r=>complete=r),events=[];const owner={completed,stop:()=>{events.push('stop');complete({status:null,signal:'SIGTERM'});return new Promise(r=>finishStop=r);}};const finite=new Function('refuse','setTimeout','clearTimeout',`return (${node.getText(ast)});`)(()=>{throw Error('fixed-refusal');},cb=>{timer=cb;return 1;},()=>{});let settled=false;const pending=finite(owner,{timeout:5000},new AbortController().signal).catch(e=>{settled=true;return e;});timer();await new Promise(r=>setImmediate(r));assert.equal(settled,false);assert.deepEqual(events,['stop']);finishStop();assert.equal((await pending).message,'fixed-refusal');});
test('workflow successor preserves all34 predecessor step objects and original acceptance bytes',async()=>{const current=yaml.load(await readFile(new URL('../.github/workflows/runnable-ui.yml',import.meta.url),'utf8'));const steps=current.jobs.verify.steps;const intake=steps.findIndex(x=>x.name==='Provision pinned owned authorization runtime tools');assert.ok(intake>=0);const diagnostic=validatedInnerDiagnosticStep(steps);validatedNotificationDeliveryStep(steps);assert.equal(steps.length,37);const notification=validatedNotificationDeliveryStep(steps);const original=steps.filter((_,i)=>i!==intake&&i!==diagnostic&&i!==notification);assert.equal(original.length,34);assert.equal(predecessorStepsSHA(original),'f6f95021c07f605176460b70065c985eda5fe82e14f3793cef7173236efb9fcb');const acceptance=original.find(x=>x.name==='Verify current compliance browser acceptance');assert.equal(acceptance['timeout-minutes'],15);assert.deepEqual(acceptance.env,{ZASP_COMBINED_E2E_COMPLIANCE:'true'});assert.equal(acceptance.run,'node --test scripts/browser-prerequisites.test.mjs scripts/browser-e2e-helpers.test.mjs scripts/owned-browser-postgres.test.mjs scripts/compliance-browser-bytes.test.mjs || { status=$?; printf \'::error::Compliance browser unit prerequisites failed (exit %s)\\n\' "$status"; exit "$status"; }\nnode scripts/production-combined-e2e.mjs || { status=$?; printf \'::error::Compliance browser runtime acceptance failed (exit %s)\\n\' "$status"; exit "$status"; }\n');});
test('startup capacity reserves whole fixed intake budget and resource excess refuses before export',async t=>{for(const initial of [{free:2684354560n+536870912n+33554431n,allocated:0n},{free:10n*1024n**3n,allocated:536870913n}]){const f=await fixture(t);f.adapters.observe=async()=>initial;await assert.rejects(invoke(f));assert.ok(!f.calls.some(x=>x.type==='download'||x.type==='load'||x.type==='publish'));}});

test('approved retained official version bytes are accepted and closed malformed variants refuse export',async t=>{for(const mutate of [value=>({...value,stderr:value.stderr.replaceAll('`','')}),value=>({...value,stderr:value.stderr.replace('v1.21.0','v1.21.1')}),value=>({...value,stderr:value.stderr.replace('ab557','xx557')}),value=>({...value,stderr:'OpenFGA version `v1.21.0` nonsense\n'}),value=>({...value,stdout:'unexpected-output'})]){const f=await fixture(t);f.adapters.version=async tool=>tool.name==='openfga'?mutate(decodedVersion('openfga')):decodedVersion('temporal');await assert.rejects(invoke(f));assert.equal(await readFile(f.env,'utf8'),'');}const f=await fixture(t);await invoke(f);assert.match(await readFile(f.env,'utf8'),/^ZASP_BROWSER_RUNTIME_ARCHIVE_ROOT=/);});

test('only canonical valid invocation timestamp varies while complete official version payload stays fixed',async t=>{const f=await fixture(t);f.adapters.version=async tool=>{const value=decodedVersion(tool.name);return tool.name==='openfga'?{...value,stderr:'2026/11/04 17:25:43'+value.stderr.slice(19)}:value;};await invoke(f);for(const timestamp of ['2026/02/30 17:25:43','2026/13/04 17:25:43','2026/11/04 24:25:43','2026/11/04 17:60:43','2026/11/04 17:25:60','0000/11/04 17:25:43','2026-11-04 17:25:43','2026/1/004 17:25:43','CANARY_RAW_FAILURE']){const bad=await fixture(t);bad.adapters.version=async tool=>{const value=decodedVersion(tool.name);return tool.name==='openfga'?{...value,stderr:timestamp+value.stderr.slice(19)}:value;};await assert.rejects(invoke(bad));assert.equal(await readFile(bad.env,'utf8'),'');}});

for(const condition of ['omitted','duplicate','skipped','allowed failure','timeout','command','environment','order','shell'])test(`signed notification verification refuses ${condition}`,async()=>{
 const workflow=yaml.load(await readFile(new URL('../.github/workflows/runnable-ui.yml',import.meta.url),'utf8'));
 const steps=workflow.jobs.verify.steps,index=validatedNotificationDeliveryStep(steps),step=steps[index];
 if(condition==='omitted')steps.splice(index,1);
 if(condition==='duplicate')steps.push(structuredClone(step));
 if(condition==='skipped')step.if=false;
 if(condition==='allowed failure')step['continue-on-error']=true;
 if(condition==='timeout')step['timeout-minutes']=11;
 if(condition==='command')step.run=step.run.replace('-race ','');
 if(condition==='environment')step.env={GOFLAGS:'-short'};
 if(condition==='order')steps.push(steps.splice(index,1)[0]);
 if(condition==='shell')step.shell='bash';
 assert.throws(()=>validatedNotificationDeliveryStep(steps));
});
