import test from 'node:test';import assert from 'node:assert/strict';
import {installOwnedCurrent80,closedOwnedAmbientEnvironment,runOwnedProjectionLoop,OwnedProjectionCleanupIncomplete}from './owned-current80-composition.mjs';
function fixture(){const calls=[],organization='pid_10000001-0000-4000-8000-000000000001';const environment={ZASP_RUNTIME_SERVICES_ENABLED:'true',ZASP_ENVIRONMENT:'test',ZASP_RUNTIME_SERVICES_TIMEOUT:'5s',ZASP_TEMPORAL_ADDRESS:'127.0.0.1:32101',ZASP_TEMPORAL_NAMESPACE:'owned',ZASP_TEMPORAL_TASK_QUEUE:'owned-main',ZASP_TEMPORAL_DISCOVERY_TASK_QUEUE:'owned-discovery',ZASP_OPENFGA_URL:'http://127.0.0.1:32102',ZASP_OPENFGA_STORE_ID:'01K00000000000000000000001',ZASP_OPENFGA_MODEL_ID:'01K00000000000000000000002',ZASP_OPENFGA_TOKEN_FILE:'/owned/token'};const revision={organization_id:organization,desired:4,applied:4,generation:2,store_id:environment.ZASP_OPENFGA_STORE_ID,model_id:environment.ZASP_OPENFGA_MODEL_ID};const config={migrate:'/owned/migrate',reconcile:'/owned/reconcile',psql:'/owned/psql',port:32100,organization,runtimeEnvironment:environment,identityEnvironment:{PATH:'/usr/bin:/bin',ZASP_PUBLIC_ORIGIN:'https://fixture.invalid:32103',ZASP_STYTCH_BASE_URL:'http://127.0.0.1:32104',ZASP_STYTCH_PROJECT_ID:'owned-project',ZASP_STYTCH_ORGANIZATION_ID:'owned-org',ZASP_DEPLOYMENT_MODE:'saas',ZASP_ORGANIZATION_ID:'',ZASP_WORKFLOW_SIGNING_KEY:'fixture-input'},keyFiles:{forward:'/owned/forward',compensation:'/owned/compensation'}};config.command=async(executable,args,options)=>{calls.push({executable,args,options});return {status:0,signal:null,stdout:executable===config.psql?JSON.stringify(revision):args[1]==='reconcile'?JSON.stringify({organization_id:organization,status:'applied',receipt:{Revision:revision,TupleCount:12,Applied:true}}):'{}'};};return {config,calls,revision};}
test('installs existing closed runtime profile and genuine configure/reconcile before returning read-bound projection',async()=>{const f=fixture();const value=await installOwnedCurrent80(f.config);assert.deepEqual(f.calls.slice(0,8).map(call=>call.args[0]),['up-to-60','up-authorization-runtime-profile','register-temporal-executor-principals','register-authorization-verifier','register-identity-session-verifier','register-identity-webhook-verifier','register-worker-authorization-verifier','register-compensation-authorization-verifier']);assert.match(f.calls[8].options.env.ZASP_POSTGRES_DSN,/zasp_e2e@/);assert.match(f.calls[9].options.env.ZASP_POSTGRES_DSN,/zasp_e2e_outbox@/);assert.match(f.calls[10].args[0],/zasp_e2e_api@/);assert.equal(value.applied.desired,value.applied.applied);assert.equal(value.acceptance,false);});
test('missing real runtime model refuses before any installation',async()=>{const f=fixture();delete f.config.runtimeEnvironment.ZASP_OPENFGA_MODEL_ID;await assert.rejects(installOwnedCurrent80(f.config));assert.deepEqual(f.calls,[]);});
for(const field of ['applied','model_id','generation'])test('receipt '+field+' drift refuses instead of claiming acknowledgement',async()=>{const f=fixture();const command=f.config.command;f.config.command=async(...args)=>{const result=await command(...args);if(args[0]===f.config.psql){const value=JSON.parse(result.stdout);value[field]=field==='model_id'?'01K00000000000000000000003':value[field]+1;result.stdout=JSON.stringify(value);}return result;};await assert.rejects(installOwnedCurrent80(f.config));});
test('original installer failure stops before verifier or projector invocation',async()=>{const f=fixture();f.config.command=async(...args)=>{f.calls.push(args);return {status:1,signal:null,stdout:''};};await assert.rejects(installOwnedCurrent80(f.config));assert.equal(f.calls.length,1);});
test('closed owner environment removes ambient product settings without suppressing inherited tool metadata',()=>{assert.deepEqual(closedOwnedAmbientEnvironment({PATH:'/usr/bin',ZASP_COMPLIANCE_EXPORT_ROLE_ARN:'ambient',ZASP_RUNTIME_SERVICES_ENABLED:'false',LANG:'C'}),{PATH:'/usr/bin',LANG:'C'});});
test('later projection loop consumes fresh native revisions and stops only after pending pass finalizes',async()=>{const controller=new AbortController(),events=[];let finish,started;const ready=new Promise(resolve=>{started=resolve;});const loop=runOwnedProjectionLoop({refresh:async signal=>{events.push('pass-start');assert.equal(signal,controller.signal);started();await new Promise(resolve=>{finish=resolve;});events.push('pass-finalized');}},controller.signal,()=>assert.fail('unexpected refusal'));await ready;let settled=false;void loop.then(()=>{settled=true;});controller.abort();await new Promise(resolve=>setImmediate(resolve));assert.equal(settled,false);finish();await loop;assert.deepEqual(events,['pass-start','pass-finalized']);});
test('actual projection failure is reported without publishing a fake applied revision',async()=>{const controller=new AbortController();let refusals=0;await assert.rejects(runOwnedProjectionLoop({refresh:async()=>{throw Error('private');}},controller.signal,()=>{refusals++;}),/^Error: owned authorization projection unavailable$/);assert.equal(refusals,1);});
test('canceled projection cleanup failure remains a refusal and retains failed join',async()=>{const controller=new AbortController();let refusals=0;const failure=new OwnedProjectionCleanupIncomplete();await assert.rejects(runOwnedProjectionLoop({refresh:async()=>{controller.abort();throw failure;}},controller.signal,()=>{refusals++;}),error=>error===failure);assert.equal(refusals,1);});
test('inline grant barriers and owned polling serialize real projection passes',async()=>{const f=fixture(),command=f.config.command;let passes=0,finish;f.config.command=async(...args)=>{if(args[0]===f.config.reconcile&&args[1][1]==='reconcile'){passes++;if(passes===2)await new Promise(resolve=>{finish=resolve;});}return command(...args);};const projector=await installOwnedCurrent80(f.config);const first=projector.refresh(),second=projector.refresh();await new Promise(resolve=>setImmediate(resolve));const started=passes;finish();await Promise.all([first,second]);assert.equal(started,2);assert.equal(passes,3);});
