import test from 'node:test';import assert from 'node:assert/strict';
import {startRetainedOwnedRuntimeLifetime,observeRetainedAllocation}from './owned-runtime-lifetime.mjs';
function fixture(){const calls=[];let sample,finish;return {calls,config:{stateRoot:'/owned/state',archiveRoot:'/owned/archives',rawRoot:'/owned/raw',run:'0123456789abcdef'},adapters:{observe:async roots=>{assert.deepEqual(roots,['/owned/state','/owned/archives','/owned/raw']);return {free:2991226880n,allocated:290000000n};},reopen:async(name,archive,raw)=>{calls.push(['reopen',name,archive,raw]);return {name};},closeTool:async tool=>calls.push('close-'+tool.name),setTimer:fn=>{sample=fn;return 1;},clearTimer:()=>{},start:async(config,_default,signal)=>{assert.equal(config.rootParent,'/owned/state');assert.ok(signal instanceof AbortSignal);return {environment:{owned:'fixture'},completed:new Promise(()=>{}),close:async()=>{calls.push('joining');await new Promise(resolve=>{finish=resolve;});calls.push('joined');}};}},sample:()=>sample(),finish:()=>finish()};}
test('retained startup counts all existing allocation and spends only its unallocated budget',async()=>{const f=fixture();const owner=await startRetainedOwnedRuntimeLifetime(f.config,f.adapters);assert.deepEqual(f.calls.slice(0,2),[['reopen','temporal','/owned/archives/temporal.tar.gz','/owned/raw/temporal-held'],['reopen','openfga','/owned/archives/openfga.tar.gz','/owned/raw/openfga-held']]);const stopped=owner.close();await new Promise(resolve=>setImmediate(resolve));f.finish();await stopped;});
test('retained startup refuses overbudget inventory before reopening any descriptor',async()=>{const f=fixture();f.adapters.observe=async()=>({free:4000000000n,allocated:536870913n});await assert.rejects(startRetainedOwnedRuntimeLifetime(f.config,f.adapters));assert.deepEqual(f.calls,[]);});
test('overlapping retained roots refuse instead of hiding or double-counting consumption',async()=>{const f=fixture();f.config.rawRoot='/owned/archives/raw';await assert.rejects(startRetainedOwnedRuntimeLifetime(f.config,f.adapters));assert.deepEqual(f.calls,[]);});
test('later retained resource refusal finalizes service join before settling completion',async()=>{const f=fixture();const owner=await startRetainedOwnedRuntimeLifetime(f.config,f.adapters);let settled=false;const completion=owner.completed.catch(()=>{settled=true;});f.adapters.observe=async()=>({free:1n,allocated:290000000n});f.sample();await new Promise(resolve=>setImmediate(resolve));assert.equal(settled,false);assert.ok(f.calls.includes('joining'));assert.ok(!f.calls.includes('close-temporal'));f.finish();await completion;assert.equal(settled,true);assert.deepEqual(f.calls.slice(-3),['joined','close-temporal','close-openfga']);});

test('retained resource observer rejects hardlinked aliases across actual private roots',async()=>{const{mkdtemp,mkdir,writeFile,link,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path');const root=await mkdtemp(join(tmpdir(),'zasp-retained-alias-'));try{const roots=['state','archive','raw'].map(name=>join(root,name));for(const name of roots)await mkdir(name,{mode:0o700});await writeFile(join(roots[0],'owned'),Buffer.alloc(4096),{mode:0o600});const before=await observeRetainedAllocation(roots);assert.ok(before.allocated>0n);await link(join(roots[0],'owned'),join(roots[2],'alias'));await assert.rejects(observeRetainedAllocation(roots));}finally{await rm(root,{recursive:true});}});
test('retained observer refuses repeated actual root inode',async()=>{const{mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path');const root=await mkdtemp(join(tmpdir(),'zasp-retained-root-'));try{await assert.rejects(observeRetainedAllocation([root,root,root]));}finally{await rm(root,{recursive:true});}});
