log: { stdout: true, level: warn }
persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 4
  datastores:
    default:
      sql:
        pluginName: postgres12
        databaseName: temporal
        connectAddr: temporal-db:5432
        connectProtocol: tcp
        user: temporal
        password: local-temporal-only
        maxConns: 10
        maxIdleConns: 5
    visibility:
      sql:
        pluginName: postgres12
        databaseName: temporal_visibility
        connectAddr: visibility-db:5432
        connectProtocol: tcp
        user: visibility
        password: local-visibility-only
        maxConns: 10
        maxIdleConns: 5
global:
  membership: { maxJoinDuration: 30s, broadcastAddress: 127.0.0.1 }
  metrics: { prometheus: { timerType: histogram, listenAddress: '0.0.0.0:9090' } }
services:
  frontend: { rpc: { grpcPort: 7233, membershipPort: 6933, bindOnIP: '0.0.0.0' } }
  history: { rpc: { grpcPort: 7234, membershipPort: 6934, bindOnIP: '0.0.0.0' } }
  matching: { rpc: { grpcPort: 7235, membershipPort: 6935, bindOnIP: '0.0.0.0' } }
  worker: { rpc: { grpcPort: 7239, membershipPort: 6939, bindOnIP: '0.0.0.0' } }
clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: active
  currentClusterName: active
  clusterInformation:
    active: { enabled: true, initialFailoverVersion: 1, rpcName: temporal-frontend, rpcAddress: '127.0.0.1:7233', httpAddress: '127.0.0.1:7243' }
dcRedirectionPolicy: { policy: noop }
publicClient: { hostPort: '127.0.0.1:7233' }
