DO $release_guard$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM public.zasp_schema_versions WHERE version=22 AND name='security_agent_temporary_policy')
     OR EXISTS(SELECT 1 FROM public.zasp_schema_versions WHERE version>22)
     OR NOT EXISTS(SELECT 1 FROM public.zasp_schema_metadata WHERE key='production_core_schema' AND value='security-agent-temporary-policy-v1') THEN
    RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='security agent connector revocation release drift';
  END IF;
END
$release_guard$;

DO $product_release_evolution$
DECLARE definition text;original_definition text;
BEGIN
  SELECT pg_get_functiondef('public.zasp_workflow_mutate(text,text,text,text,text,text,text,text,text,bigint,jsonb,jsonb,text,text,text)'::regprocedure) INTO STRICT definition;
  original_definition:=definition;
  definition:=replace(definition,'security-agent-temporary-policy-v1','security-agent-connector-revocation-v1');
  definition:=replace(definition,'release."version" = 22','release."version" = 23');
  definition:=replace(definition,'release."name" = ''security_agent_temporary_policy''','release."name" = ''security_agent_connector_revocation''');
  definition:=replace(definition,'later_release."version" > 22','later_release."version" > 23');
  IF definition=original_definition OR position('security-agent-connector-revocation-v1' IN definition)=0 OR position('release."version" = 23' IN definition)=0 OR position('security_agent_connector_revocation' IN definition)=0 OR position('later_release."version" > 23' IN definition)=0 THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='workflow v23 compatibility evolution failed';END IF;
  EXECUTE definition;

  SELECT pg_get_functiondef('public.zasp_risk_mutate(text,text,text,text,text,text,text,bigint,text,text,text,text,text)'::regprocedure) INTO STRICT definition;
  original_definition:=definition;
  definition:=replace(definition,'security-agent-temporary-policy-v1','security-agent-connector-revocation-v1');
  definition:=replace(replace(definition,'release."version"=22','release."version"=23'),'release."version" = 22','release."version" = 23');
  definition:=replace(replace(definition,'release."name"=''security_agent_temporary_policy''','release."name"=''security_agent_connector_revocation'''),'release."name" = ''security_agent_temporary_policy''','release."name" = ''security_agent_connector_revocation''');
  definition:=replace(replace(definition,'later."version">22','later."version">23'),'later."version" > 22','later."version" > 23');
  IF definition=original_definition OR position('security-agent-connector-revocation-v1' IN definition)=0 OR position('security_agent_connector_revocation' IN definition)=0 OR position('release."version"=23' IN definition)=0 AND position('release."version" = 23' IN definition)=0 OR position('later."version">23' IN definition)=0 AND position('later."version" > 23' IN definition)=0 THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='risk v23 compatibility evolution failed';END IF;
  EXECUTE definition;
END
$product_release_evolution$;

DO $connector_restore$
DECLARE definition text;helper text;
BEGIN
  SELECT pg_get_functiondef('public.zasp_connector_complete_revocation(text,text,text,text,text,text)'::regprocedure) INTO STRICT definition;
  helper:=replace(definition,'CREATE OR REPLACE FUNCTION public.zasp_connector_complete_revocation','CREATE FUNCTION public.zasp_connector_complete_revocation_v22');
  IF helper=definition THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='connector revocation helper creation failed';END IF;
  EXECUTE helper;
  ALTER FUNCTION public.zasp_connector_complete_revocation_v22(text,text,text,text,text,text) OWNER TO zasp_discovery_authority;
  REVOKE ALL ON FUNCTION public.zasp_connector_complete_revocation_v22(text,text,text,text,text,text) FROM PUBLIC,zasp_discovery_api,zasp_discovery_worker,zasp_security_agent_worker,zasp_security_agent_action_worker;
END
$connector_restore$;

DO $controls_restore$
DECLARE definition text;helper text;
BEGIN
  SELECT pg_get_functiondef('public.zasp_security_agent_execution_control_detail(text,text,text)'::regprocedure) INTO STRICT definition;
  helper:=replace(definition,'CREATE OR REPLACE FUNCTION public.zasp_security_agent_execution_control_detail','CREATE FUNCTION public.zasp_security_agent_execution_control_detail_v22_restore');
  IF helper=definition THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='execution control detail helper creation failed';END IF;
  EXECUTE helper;
  ALTER FUNCTION public.zasp_security_agent_execution_control_detail_v22_restore(text,text,text) OWNER TO zasp_discovery_authority;
  REVOKE ALL ON FUNCTION public.zasp_security_agent_execution_control_detail_v22_restore(text,text,text) FROM PUBLIC,zasp_security_agent_api,zasp_security_agent_worker,zasp_security_agent_action_worker,zasp_discovery_api,zasp_discovery_worker;

  SELECT pg_get_functiondef('public.zasp_security_agent_mutate_execution_control(text,text,text,text,text,text,text,boolean,bigint,timestamptz,text,text,text)'::regprocedure) INTO STRICT definition;
  helper:=replace(definition,'CREATE OR REPLACE FUNCTION public.zasp_security_agent_mutate_execution_control','CREATE FUNCTION public.zasp_security_agent_mutate_execution_control_v22_restore');
  IF helper=definition THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='execution control mutation helper creation failed';END IF;
  EXECUTE helper;
  ALTER FUNCTION public.zasp_security_agent_mutate_execution_control_v22_restore(text,text,text,text,text,text,text,boolean,bigint,timestamptz,text,text,text) OWNER TO zasp_discovery_authority;
  REVOKE ALL ON FUNCTION public.zasp_security_agent_mutate_execution_control_v22_restore(text,text,text,text,text,text,text,boolean,bigint,timestamptz,text,text,text) FROM PUBLIC,zasp_security_agent_api,zasp_security_agent_worker,zasp_security_agent_action_worker,zasp_discovery_api,zasp_discovery_worker;
END
$controls_restore$;

CREATE TABLE public.zasp_security_agent_connector_revocations(
  organization_id text NOT NULL,workspace_id text NOT NULL,environment_id text NOT NULL,
  run_id text NOT NULL,step_id text NOT NULL,action_key text NOT NULL DEFAULT 'revoke_integration_connection' CHECK(action_key='revoke_integration_connection'),
  connector_effect_id text NOT NULL,integration_id text NOT NULL,connection_id text NOT NULL,credential_id text NOT NULL,
  input_digest bytea NOT NULL CHECK(octet_length(input_digest)=32),state text NOT NULL DEFAULT 'pending' CHECK(state IN('pending','verified','needs_human')),
  created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),completed_at timestamptz,
  PRIMARY KEY(organization_id,workspace_id,environment_id,run_id,step_id),
  UNIQUE(organization_id,workspace_id,environment_id,connector_effect_id),
  FOREIGN KEY(organization_id,workspace_id,environment_id,run_id,step_id,action_key) REFERENCES public.zasp_security_agent_effects(organization_id,workspace_id,environment_id,run_id,step_id,action_key),
  FOREIGN KEY(organization_id,workspace_id,environment_id,integration_id,connector_effect_id) REFERENCES public.zasp_connector_effects(organization_id,workspace_id,environment_id,integration_id,id),
  FOREIGN KEY(organization_id,workspace_id,environment_id,connection_id) REFERENCES public.zasp_integration_connections(organization_id,workspace_id,environment_id,id),
  CHECK((state='pending' AND completed_at IS NULL) OR (state IN('verified','needs_human') AND completed_at IS NOT NULL))
);
ALTER TABLE public.zasp_security_agent_connector_revocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zasp_security_agent_connector_revocations FORCE ROW LEVEL SECURITY;
CREATE POLICY zasp_security_agent_connector_revocations_authority ON public.zasp_security_agent_connector_revocations FOR ALL TO zasp_discovery_authority USING(true) WITH CHECK(true);
ALTER TABLE public.zasp_security_agent_connector_revocations OWNER TO zasp_discovery_authority;
REVOKE ALL ON TABLE public.zasp_security_agent_connector_revocations FROM PUBLIC,zasp_security_agent_api,zasp_security_agent_worker,zasp_security_agent_action_worker,zasp_discovery_api,zasp_discovery_worker;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.zasp_security_agent_connector_revocations TO zasp_discovery_authority;

ALTER TABLE public.zasp_security_agent_definitions ADD CONSTRAINT zasp_security_agent_connector_revocation_supervised_check
  CHECK(NOT (body->'allowed_actions' ? 'revoke_integration_connection') OR activation<>'autonomous' AND body->>'autonomy'='supervised');

CREATE OR REPLACE FUNCTION public.zasp_security_agent_execution_control_detail(organization_value text,workspace_value text,environment_value text) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $detail$
DECLARE global_row zasp_security_agent_kill_switches%ROWTYPE;environment_row zasp_security_agent_kill_switches%ROWTYPE;temporary_row zasp_security_agent_kill_switches%ROWTYPE;revoke_row zasp_security_agent_kill_switches%ROWTYPE;finding_row zasp_security_agent_kill_switches%ROWTYPE;
BEGIN
  IF NOT zasp_security_agent_principal_ready('zasp_security_agent_api') OR NOT zasp_valid_product_id(organization_value) OR NOT zasp_valid_product_id(workspace_value) OR NOT zasp_valid_product_id(environment_value) THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='security agent execution control detail rejected';END IF;
  IF NOT EXISTS(SELECT 1 FROM zasp_environments environment WHERE (environment.organization_id,environment.workspace_id,environment.id)=(organization_value,workspace_value,environment_value)) THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='security agent execution control scope not found';END IF;
  SELECT * INTO STRICT global_row FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key)=('*','*','*','*');
  SELECT * INTO environment_row FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key)=(organization_value,workspace_value,environment_value,'*');
  SELECT * INTO temporary_row FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key)=(organization_value,workspace_value,environment_value,'create_temporary_policy');
  SELECT * INTO revoke_row FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key)=(organization_value,workspace_value,environment_value,'revoke_integration_connection');
  SELECT * INTO finding_row FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key)=(organization_value,workspace_value,environment_value,'update_finding_response');
  RETURN jsonb_build_object('global',jsonb_build_object('target','global','action_key','*','enabled',global_row.execution_enabled,'version',global_row.version),'environment',jsonb_build_object('target','environment','action_key','*','enabled',COALESCE(environment_row.execution_enabled,false),'version',COALESCE(environment_row.version,0)),'actions',jsonb_build_array(jsonb_build_object('target','action','action_key','create_temporary_policy','enabled',COALESCE(temporary_row.execution_enabled,false),'version',COALESCE(temporary_row.version,0)),jsonb_build_object('target','action','action_key','revoke_integration_connection','enabled',COALESCE(revoke_row.execution_enabled,false),'version',COALESCE(revoke_row.version,0)),jsonb_build_object('target','action','action_key','update_finding_response','enabled',COALESCE(finding_row.execution_enabled,false),'version',COALESCE(finding_row.version,0))));
END
$detail$;

CREATE OR REPLACE FUNCTION public.zasp_security_agent_mutate_execution_control(organization_value text,workspace_value text,environment_value text,actor_value text,idempotency_value text,target_value text,action_value text,enabled_value boolean,expected_version bigint,fresh_auth_expires_value timestamptz,audit_value text,correlation_value text,receipt_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $mutate$
DECLARE row_organization text;row_workspace text;row_environment text;row_action text;intent_value jsonb;intent_digest_value bytea;receipt_row zasp_security_agent_request_receipts%ROWTYPE;result_value jsonb;response_value jsonb;resource_value text;
BEGIN
  IF NOT zasp_security_agent_principal_ready('zasp_security_agent_api') OR NOT zasp_valid_product_id(organization_value) OR NOT zasp_valid_product_id(workspace_value) OR NOT zasp_valid_product_id(environment_value) OR NOT zasp_valid_product_id(actor_value) OR NOT zasp_valid_product_id(audit_value) OR NOT zasp_valid_product_id(correlation_value) OR NOT zasp_valid_product_id(receipt_value) OR length(idempotency_value) NOT BETWEEN 16 AND 128 OR idempotency_value!~'^[A-Za-z0-9][A-Za-z0-9._:-]*$' OR target_value NOT IN('environment','action') OR expected_version<0 OR fresh_auth_expires_value IS NULL OR fresh_auth_expires_value<=transaction_timestamp() OR fresh_auth_expires_value>transaction_timestamp()+interval '5 minutes 5 seconds' OR (target_value='action' AND action_value NOT IN('create_temporary_policy','revoke_integration_connection','update_finding_response')) OR (target_value<>'action' AND action_value<>'*') THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='security agent execution control mutation rejected';END IF;
  IF NOT EXISTS(SELECT 1 FROM zasp_environments environment WHERE (environment.organization_id,environment.workspace_id,environment.id)=(organization_value,workspace_value,environment_value)) THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='security agent execution control scope not found';END IF;
  IF target_value='environment' THEN row_organization:=organization_value;row_workspace:=workspace_value;row_environment:=environment_value;row_action:='*';ELSE row_organization:=organization_value;row_workspace:=workspace_value;row_environment:=environment_value;row_action:=action_value;END IF;
  resource_value:=target_value||':'||row_action;intent_value:=jsonb_build_object('target',target_value,'action_key',row_action,'enabled',enabled_value,'expected_version',expected_version);intent_digest_value:=digest(convert_to(intent_value::text,'UTF8'),'sha256');
  PERFORM pg_advisory_xact_lock(hashtextextended(concat_ws(chr(31),organization_value,workspace_value,environment_value,actor_value,'setSecurityAgentExecutionControl',idempotency_value),0));
  SELECT * INTO receipt_row FROM zasp_security_agent_request_receipts receipt WHERE (receipt.organization_id,receipt.workspace_id,receipt.environment_id,receipt.principal_id,receipt.operation,receipt.idempotency_key)=(organization_value,workspace_value,environment_value,actor_value,'setSecurityAgentExecutionControl',idempotency_value);
  IF FOUND THEN
    IF receipt_row.resource_id<>resource_value OR receipt_row.expected_version<>expected_version OR receipt_row.intent_digest<>intent_digest_value OR receipt_row.expires_at<=transaction_timestamp() OR NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches switch_row WHERE (switch_row.organization_id,switch_row.workspace_id,switch_row.environment_id,switch_row.action_key,switch_row.execution_enabled,switch_row.version)=(row_organization,row_workspace,row_environment,row_action,enabled_value,(receipt_row.response->>'version')::bigint)) THEN RAISE EXCEPTION USING ERRCODE='23505',MESSAGE='security agent execution control replay conflict';END IF;
    RETURN receipt_row.response||jsonb_build_object('replayed',true);
  END IF;
  IF enabled_value AND NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key,execution_enabled)=('*','*','*','*',true)) THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='security agent global execution disabled';END IF;
  IF enabled_value AND target_value='action' AND NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key,execution_enabled)=(organization_value,workspace_value,environment_value,'*',true)) THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='security agent environment execution disabled';END IF;
  result_value:=zasp_security_agent_set_kill_switch(row_organization,row_workspace,row_environment,row_action,enabled_value,expected_version,actor_value,audit_value,correlation_value);
  response_value:=result_value||jsonb_build_object('target',target_value,'audit_id',audit_value,'correlation_id',correlation_value,'receipt_id',receipt_value,'replayed',false);
  INSERT INTO zasp_security_agent_request_receipts(organization_id,workspace_id,environment_id,principal_id,operation,idempotency_key,resource_id,expected_version,intent,intent_digest,response,audit_id,correlation_id,receipt_id) VALUES(organization_value,workspace_value,environment_value,actor_value,'setSecurityAgentExecutionControl',idempotency_value,resource_value,expected_version,intent_value,intent_digest_value,response_value,audit_value,correlation_value,receipt_value);
  RETURN response_value;
END
$mutate$;

CREATE FUNCTION public.zasp_security_agent_schedule_connector_revocation_triggers(worker_value text,limit_value integer) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $schedule$
DECLARE candidate record;trigger_digest_value bytea;run_value text;audit_value text;correlation_value text;created_value integer:=0;
BEGIN
  IF NOT zasp_security_agent_principal_ready('zasp_security_agent_worker') OR length(worker_value) NOT BETWEEN 1 AND 128 OR limit_value NOT BETWEEN 1 AND 25 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='connector revocation scheduling rejected';END IF;
  FOR candidate IN
    WITH eligible AS (
    SELECT definition.organization_id,definition.workspace_id,definition.environment_id,definition.definition_id,definition.version definition_version,(definition.body->>'concurrency_limit')::integer concurrency_limit,finding.id trigger_id,finding.version trigger_version,finding.updated_at,
      row_number() OVER (PARTITION BY definition.organization_id,definition.workspace_id,definition.environment_id,definition.definition_id ORDER BY finding.updated_at,finding.id) definition_ordinal
    FROM zasp_security_agent_definitions definition JOIN zasp_risk_findings finding ON (finding.organization_id,finding.workspace_id,finding.environment_id)=(definition.organization_id,definition.workspace_id,definition.environment_id)
    WHERE definition.activation='supervised' AND definition.deleted_at IS NULL AND definition.body->>'enabled'='true' AND definition.body->>'trigger_kind'='finding' AND definition.body->'environment_ids' ? definition.environment_id AND COALESCE(finding.rule,finding.source)=definition.body->>'trigger_source' AND finding.status='open' AND definition.body->'allowed_actions'=jsonb_build_array('revoke_integration_connection') AND definition.body->>'verification_kind'='connection_state'
      AND EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key,execution_enabled)=('*','*','*','*',true)) AND EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key,execution_enabled)=(definition.organization_id,definition.workspace_id,definition.environment_id,'*',true)) AND EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key,execution_enabled)=(definition.organization_id,definition.workspace_id,definition.environment_id,'revoke_integration_connection',true))
      AND (SELECT count(DISTINCT evidence.integration_id) FROM zasp_risk_finding_evidence finding_evidence JOIN zasp_inventory_evidence evidence ON (evidence.organization_id,evidence.workspace_id,evidence.environment_id,evidence.id)=(finding_evidence.organization_id,finding_evidence.workspace_id,finding_evidence.environment_id,finding_evidence.evidence_id) WHERE (finding_evidence.organization_id,finding_evidence.workspace_id,finding_evidence.environment_id,finding_evidence.finding_id)=(finding.organization_id,finding.workspace_id,finding.environment_id,finding.id))=1
      AND EXISTS(
        SELECT 1
        FROM zasp_risk_finding_evidence finding_evidence
        JOIN zasp_inventory_evidence evidence ON (evidence.organization_id,evidence.workspace_id,evidence.environment_id,evidence.id)=(finding_evidence.organization_id,finding_evidence.workspace_id,finding_evidence.environment_id,finding_evidence.evidence_id)
        JOIN zasp_integration_connections connection ON (connection.organization_id,connection.workspace_id,connection.environment_id,connection.integration_id,connection.state)=(evidence.organization_id,evidence.workspace_id,evidence.environment_id,evidence.integration_id,'verified')
        JOIN zasp_integrations integration ON (integration.organization_id,integration.workspace_id,integration.environment_id,integration.id,integration.state)=(connection.organization_id,connection.workspace_id,connection.environment_id,connection.integration_id,'active')
        JOIN zasp_workflow_records workflow ON (workflow.organization_id,workflow.workspace_id,workflow.environment_id,workflow.kind,workflow.id)=(connection.organization_id,connection.workspace_id,connection.environment_id,'integration',connection.integration_id)
        WHERE (finding_evidence.organization_id,finding_evidence.workspace_id,finding_evidence.environment_id,finding_evidence.finding_id)=(finding.organization_id,finding.workspace_id,finding.environment_id,finding.id)
          AND workflow.deleted_at IS NULL AND workflow.body->>'status'='active' AND workflow.body->>'connector_key'=connection.provider AND integration.kind=connection.provider AND connection.provider IN('github','okta')
          AND (SELECT count(*) FROM zasp_integration_connections candidate_connection WHERE (candidate_connection.organization_id,candidate_connection.workspace_id,candidate_connection.environment_id,candidate_connection.integration_id,candidate_connection.state)=(evidence.organization_id,evidence.workspace_id,evidence.environment_id,evidence.integration_id,'verified'))=1
          AND (SELECT count(*) FROM zasp_connector_credentials candidate_credential WHERE (candidate_credential.organization_id,candidate_credential.workspace_id,candidate_credential.environment_id,candidate_credential.integration_id,candidate_credential.status)=(evidence.organization_id,evidence.workspace_id,evidence.environment_id,evidence.integration_id,'active'))=1
          AND EXISTS(SELECT 1 FROM zasp_connector_credentials credential WHERE (credential.organization_id,credential.workspace_id,credential.environment_id,credential.integration_id,credential.provider,credential.credential_reference,credential.status)=(connection.organization_id,connection.workspace_id,connection.environment_id,connection.integration_id,connection.provider,connection.connection_reference,'active') AND (connection.provider='github' AND credential.credential_class='github_installation_reference' AND CASE WHEN connection.connection_reference ~ '^ref:github/installation/[1-9][0-9]{0,19}$' THEN substring(connection.connection_reference FROM 25)::numeric<=9223372036854775807 ELSE false END OR connection.provider='okta' AND credential.credential_class='okta_refresh_reference' AND connection.connection_reference LIKE 'ref:okta/refresh/%' AND length(connection.connection_reference)>17))
      )
      AND NOT EXISTS(SELECT 1 FROM zasp_security_agent_trigger_receipts receipt WHERE (receipt.organization_id,receipt.workspace_id,receipt.environment_id,receipt.definition_id,receipt.trigger_id,receipt.trigger_version)=(definition.organization_id,definition.workspace_id,definition.environment_id,definition.definition_id,finding.id,finding.version))
      AND (SELECT count(*) FROM zasp_security_agent_runs run WHERE (run.organization_id,run.workspace_id,run.environment_id,run.definition_id)=(definition.organization_id,definition.workspace_id,definition.environment_id,definition.definition_id) AND run.state IN('queued','planning','waiting_approval','running','verifying','contained'))<(definition.body->>'concurrency_limit')::integer
    )
    SELECT organization_id,workspace_id,environment_id,definition_id,definition_version,concurrency_limit,trigger_id,trigger_version,updated_at FROM eligible WHERE definition_ordinal=1
    ORDER BY updated_at,organization_id,workspace_id,environment_id,definition_id,trigger_id LIMIT limit_value
  LOOP
    PERFORM pg_advisory_xact_lock(hashtextextended(concat_ws(chr(31),candidate.organization_id,candidate.workspace_id,candidate.environment_id,candidate.definition_id,'connector-revocation-trigger'),0));
    CONTINUE WHEN EXISTS(SELECT 1 FROM zasp_security_agent_trigger_receipts receipt WHERE (receipt.organization_id,receipt.workspace_id,receipt.environment_id,receipt.definition_id,receipt.trigger_id,receipt.trigger_version)=(candidate.organization_id,candidate.workspace_id,candidate.environment_id,candidate.definition_id,candidate.trigger_id,candidate.trigger_version));
    CONTINUE WHEN (SELECT count(*) FROM zasp_security_agent_runs run WHERE (run.organization_id,run.workspace_id,run.environment_id,run.definition_id)=(candidate.organization_id,candidate.workspace_id,candidate.environment_id,candidate.definition_id) AND run.state IN('queued','planning','waiting_approval','running','verifying','contained'))>=candidate.concurrency_limit;
    trigger_digest_value:=digest(convert_to(jsonb_build_object('kind','finding','id',candidate.trigger_id,'version',candidate.trigger_version)::text,'UTF8'),'sha256');
    run_value:=zasp_discovery_canonical_id(candidate.organization_id,candidate.workspace_id,candidate.environment_id,'security_agent_run',candidate.definition_id||chr(31)||candidate.trigger_id||chr(31)||candidate.trigger_version::text);
    INSERT INTO zasp_security_agent_trigger_receipts(organization_id,workspace_id,environment_id,definition_id,trigger_id,trigger_kind,trigger_version,trigger_digest,run_id) VALUES(candidate.organization_id,candidate.workspace_id,candidate.environment_id,candidate.definition_id,candidate.trigger_id,'finding',candidate.trigger_version,trigger_digest_value,run_value) ON CONFLICT DO NOTHING;CONTINUE WHEN NOT FOUND;
    INSERT INTO zasp_security_agent_runs(organization_id,workspace_id,environment_id,run_id,definition_id,definition_version,trigger_id,requested_by,state) VALUES(candidate.organization_id,candidate.workspace_id,candidate.environment_id,run_value,candidate.definition_id,candidate.definition_version,candidate.trigger_id,worker_value,'queued');
    audit_value:=zasp_discovery_canonical_id(candidate.organization_id,candidate.workspace_id,candidate.environment_id,'security_agent_audit',run_value||chr(31)||'connector-revocation-trigger');correlation_value:=zasp_discovery_canonical_id(candidate.organization_id,candidate.workspace_id,candidate.environment_id,'security_agent_correlation',run_value||chr(31)||'connector-revocation-trigger');
    INSERT INTO zasp_security_agent_audit(organization_id,workspace_id,environment_id,audit_id,correlation_id,run_id,actor_id,event_kind,event_digest,body) VALUES(candidate.organization_id,candidate.workspace_id,candidate.environment_id,audit_value,correlation_value,run_value,worker_value,'run_queued',trigger_digest_value,jsonb_build_object('run_id',run_value,'definition_id',candidate.definition_id,'definition_version',candidate.definition_version,'trigger_kind','finding','trigger_id',candidate.trigger_id,'trigger_version',candidate.trigger_version,'automatic',true,'action','revoke_integration_connection'));
    created_value:=created_value+1;
  END LOOP;
  IF created_value>0 THEN UPDATE zasp_security_agent_execution_state SET used_at=COALESCE(used_at,transaction_timestamp()) WHERE singleton;END IF;
  RETURN jsonb_build_object('created',created_value);
END
$schedule$;

CREATE FUNCTION public.zasp_security_agent_schedule_triggers_v23(worker_value text,limit_value integer) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $schedule_all$
DECLARE revoke_result jsonb;prior_result jsonb;revoke_created integer;prior_created integer:=0;
BEGIN
  IF limit_value NOT BETWEEN 1 AND 25 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='security agent scheduling rejected';END IF;
  revoke_result:=zasp_security_agent_schedule_connector_revocation_triggers(worker_value,greatest(1,(limit_value+2)/3));revoke_created:=(revoke_result->>'created')::integer;
  IF revoke_created<limit_value THEN prior_result:=zasp_security_agent_schedule_triggers_v22(worker_value,limit_value-revoke_created);prior_created:=(prior_result->>'created')::integer;END IF;
  RETURN jsonb_build_object('created',revoke_created+prior_created);
END
$schedule_all$;

CREATE FUNCTION public.zasp_security_agent_claim_runs_v23(worker_value text,lease_token_value text,lease_seconds integer,claim_limit integer) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path TO pg_catalog, public AS $claim$ SELECT zasp_security_agent_claim_runs_v22(worker_value,lease_token_value,lease_seconds,claim_limit) $claim$;

CREATE FUNCTION public.zasp_security_agent_prepare_connector_revocation_run(organization_value text,workspace_value text,environment_value text,run_value text,worker_value text,lease_token_value text,approval_value text,approval_expires_value timestamptz,audit_value text,correlation_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $prepare$
DECLARE run_row zasp_security_agent_runs%ROWTYPE;definition_row zasp_security_agent_definitions%ROWTYPE;trigger_row zasp_security_agent_trigger_receipts%ROWTYPE;finding_version bigint;integration_value text;connection_value text;step_value text;plan_value jsonb;plan_digest bytea;
BEGIN
  IF NOT zasp_security_agent_principal_ready('zasp_security_agent_worker') OR NOT zasp_valid_product_id(run_value) OR NOT zasp_valid_product_id(approval_value) OR NOT zasp_valid_product_id(audit_value) OR NOT zasp_valid_product_id(correlation_value) OR length(worker_value) NOT BETWEEN 1 AND 128 OR length(lease_token_value) NOT BETWEEN 16 AND 128 OR approval_expires_value<=transaction_timestamp() OR approval_expires_value>transaction_timestamp()+interval '16 minutes' THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='connector revocation plan rejected';END IF;
  SELECT * INTO run_row FROM zasp_security_agent_runs run WHERE (run.organization_id,run.workspace_id,run.environment_id,run.run_id,run.state,run.lease_owner,run.lease_token)=(organization_value,workspace_value,environment_value,run_value,'planning',worker_value,lease_token_value) AND run.lease_expires_at>transaction_timestamp() FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent lease lost';END IF;
  SELECT * INTO STRICT definition_row FROM zasp_security_agent_definitions definition WHERE (definition.organization_id,definition.workspace_id,definition.environment_id,definition.definition_id,definition.version)=(organization_value,workspace_value,environment_value,run_row.definition_id,run_row.definition_version) AND definition.activation='supervised' AND definition.deleted_at IS NULL AND definition.body->'allowed_actions'=jsonb_build_array('revoke_integration_connection') AND definition.body->>'verification_kind'='connection_state' FOR SHARE;
  SELECT * INTO STRICT trigger_row FROM zasp_security_agent_trigger_receipts receipt WHERE (receipt.organization_id,receipt.workspace_id,receipt.environment_id,receipt.run_id,receipt.trigger_kind)=(organization_value,workspace_value,environment_value,run_value,'finding');
  SELECT finding.version,min(evidence.integration_id) INTO finding_version,integration_value FROM zasp_risk_findings finding JOIN zasp_risk_finding_evidence finding_evidence ON (finding_evidence.organization_id,finding_evidence.workspace_id,finding_evidence.environment_id,finding_evidence.finding_id)=(finding.organization_id,finding.workspace_id,finding.environment_id,finding.id) JOIN zasp_inventory_evidence evidence ON (evidence.organization_id,evidence.workspace_id,evidence.environment_id,evidence.id)=(finding_evidence.organization_id,finding_evidence.workspace_id,finding_evidence.environment_id,finding_evidence.evidence_id) WHERE (finding.organization_id,finding.workspace_id,finding.environment_id,finding.id,finding.status)=(organization_value,workspace_value,environment_value,trigger_row.trigger_id,'open') GROUP BY finding.version HAVING count(DISTINCT evidence.integration_id)=1;
  IF NOT FOUND OR finding_version<>trigger_row.trigger_version THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent evidence changed';END IF;
  SELECT connection.id INTO STRICT connection_value FROM zasp_integration_connections connection JOIN zasp_integrations integration ON (integration.organization_id,integration.workspace_id,integration.environment_id,integration.id)=(connection.organization_id,connection.workspace_id,connection.environment_id,connection.integration_id) JOIN zasp_workflow_records workflow ON (workflow.organization_id,workflow.workspace_id,workflow.environment_id,workflow.kind,workflow.id)=(connection.organization_id,connection.workspace_id,connection.environment_id,'integration',connection.integration_id) WHERE (connection.organization_id,connection.workspace_id,connection.environment_id,connection.integration_id,connection.state)=(organization_value,workspace_value,environment_value,integration_value,'verified') AND connection.provider IN('github','okta') AND integration.state='active' AND integration.kind=connection.provider AND workflow.deleted_at IS NULL AND workflow.body->>'status'='active' AND workflow.body->>'connector_key'=connection.provider AND (SELECT count(*) FROM zasp_integration_connections candidate_connection WHERE (candidate_connection.organization_id,candidate_connection.workspace_id,candidate_connection.environment_id,candidate_connection.integration_id,candidate_connection.state)=(organization_value,workspace_value,environment_value,integration_value,'verified'))=1 AND (SELECT count(*) FROM zasp_connector_credentials candidate_credential WHERE (candidate_credential.organization_id,candidate_credential.workspace_id,candidate_credential.environment_id,candidate_credential.integration_id,candidate_credential.status)=(organization_value,workspace_value,environment_value,integration_value,'active'))=1 AND EXISTS(SELECT 1 FROM zasp_connector_credentials credential WHERE (credential.organization_id,credential.workspace_id,credential.environment_id,credential.integration_id,credential.provider,credential.credential_reference,credential.status)=(connection.organization_id,connection.workspace_id,connection.environment_id,connection.integration_id,connection.provider,connection.connection_reference,'active') AND (connection.provider='github' AND credential.credential_class='github_installation_reference' AND CASE WHEN connection.connection_reference ~ '^ref:github/installation/[1-9][0-9]{0,19}$' THEN substring(connection.connection_reference FROM 25)::numeric<=9223372036854775807 ELSE false END OR connection.provider='okta' AND credential.credential_class='okta_refresh_reference' AND connection.connection_reference LIKE 'ref:okta/refresh/%' AND length(connection.connection_reference)>17));
  step_value:=zasp_discovery_canonical_id(organization_value,workspace_value,environment_value,'security_agent_step',run_value||chr(31)||'0');
  plan_value:=jsonb_build_object('definition_id',run_row.definition_id,'definition_version',run_row.definition_version,'catalog_version','security-agent-actions-v1','evidence_ids',jsonb_build_array(trigger_row.trigger_id),'steps',jsonb_build_array(jsonb_build_object('index',0,'step_id',step_value,'action','revoke_integration_connection','target_id',connection_value,'integration_id',integration_value,'authorization','approval_required')),'verification',jsonb_build_object('kind','connection_state','expected_state','revoked'),'expires_at',to_char(approval_expires_value AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
  plan_digest:=digest(convert_to(plan_value::text,'UTF8'),'sha256');
  INSERT INTO zasp_security_agent_plans(organization_id,workspace_id,environment_id,run_id,definition_id,definition_version,trigger_digest,catalog_version,plan,plan_hash,expires_at) VALUES(organization_value,workspace_value,environment_value,run_value,run_row.definition_id,run_row.definition_version,trigger_row.trigger_digest,'security-agent-actions-v1',plan_value,plan_digest,approval_expires_value);
  INSERT INTO zasp_security_agent_steps(organization_id,workspace_id,environment_id,run_id,step_id,step_index,action_key,input_digest,authorization_result,state) VALUES(organization_value,workspace_value,environment_value,run_value,step_value,0,'revoke_integration_connection',digest(convert_to((plan_value->'steps'->0)::text,'UTF8'),'sha256'),'approval_required','waiting_approval');
  INSERT INTO zasp_security_agent_approvals(organization_id,workspace_id,environment_id,approval_id,run_id,step_id,plan_hash,state,requester_id,expires_at) VALUES(organization_value,workspace_value,environment_value,approval_value,run_value,step_value,plan_digest,'pending',run_row.requested_by,approval_expires_value);
  UPDATE zasp_security_agent_runs SET state='waiting_approval',plan_hash=plan_digest,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id)=(organization_value,workspace_value,environment_value,run_value);
  INSERT INTO zasp_security_agent_audit(organization_id,workspace_id,environment_id,audit_id,correlation_id,run_id,step_id,approval_id,actor_id,event_kind,event_digest,body) VALUES(organization_value,workspace_value,environment_value,audit_value,correlation_value,run_value,step_value,approval_value,worker_value,'approval_requested',plan_digest,jsonb_build_object('run_id',run_value,'step_id',step_value,'action','revoke_integration_connection','approval_id',approval_value,'plan_hash','sha256:'||encode(plan_digest,'hex')));
  RETURN jsonb_build_object('run_id',run_value,'state','waiting_approval','version',run_row.version+1,'approval_id',approval_value,'step_id',step_value,'plan_hash','sha256:'||encode(plan_digest,'hex'));
END
$prepare$;

CREATE FUNCTION public.zasp_security_agent_prepare_run_v23(organization_value text,workspace_value text,environment_value text,run_value text,worker_value text,lease_token_value text,approval_value text,approval_expires_value timestamptz,audit_value text,correlation_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $prepare_all$
DECLARE action_value text;
BEGIN
  SELECT definition.body->'allowed_actions'->>0 INTO action_value FROM zasp_security_agent_runs run JOIN zasp_security_agent_definitions definition ON (definition.organization_id,definition.workspace_id,definition.environment_id,definition.definition_id,definition.version)=(run.organization_id,run.workspace_id,run.environment_id,run.definition_id,run.definition_version) WHERE (run.organization_id,run.workspace_id,run.environment_id,run.run_id)=(organization_value,workspace_value,environment_value,run_value);
  IF action_value='revoke_integration_connection' THEN RETURN zasp_security_agent_prepare_connector_revocation_run(organization_value,workspace_value,environment_value,run_value,worker_value,lease_token_value,approval_value,approval_expires_value,audit_value,correlation_value);END IF;
  RETURN zasp_security_agent_prepare_run_v22(organization_value,workspace_value,environment_value,run_value,worker_value,lease_token_value,approval_value,approval_expires_value,audit_value,correlation_value);
END
$prepare_all$;

CREATE FUNCTION public.zasp_security_agent_dispatch_connector_revocation_run(organization_value text,workspace_value text,environment_value text,run_value text,worker_value text,lease_token_value text,audit_value text,correlation_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $dispatch$
DECLARE run_row zasp_security_agent_runs%ROWTYPE;plan_row zasp_security_agent_plans%ROWTYPE;step_row zasp_security_agent_steps%ROWTYPE;trigger_row zasp_security_agent_trigger_receipts%ROWTYPE;plan_step jsonb;finding_version bigint;evidence_integration text;connection_row zasp_integration_connections%ROWTYPE;credential_row zasp_connector_credentials%ROWTYPE;workflow_row zasp_workflow_records%ROWTYPE;effect_value text;idempotency_value text;request_digest_value bytea;outcome_value text;result_digest_value bytea;
BEGIN
  IF NOT zasp_security_agent_principal_ready('zasp_security_agent_worker') OR NOT zasp_valid_product_id(run_value) OR NOT zasp_valid_product_id(audit_value) OR NOT zasp_valid_product_id(correlation_value) OR length(worker_value) NOT BETWEEN 1 AND 128 OR length(lease_token_value) NOT BETWEEN 16 AND 128 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='connector revocation dispatch rejected';END IF;
  SELECT * INTO run_row FROM zasp_security_agent_runs run WHERE (run.organization_id,run.workspace_id,run.environment_id,run.run_id,run.state,run.lease_owner,run.lease_token)=(organization_value,workspace_value,environment_value,run_value,'planning',worker_value,lease_token_value) AND run.lease_expires_at>transaction_timestamp() FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent lease lost';END IF;
  SELECT * INTO STRICT plan_row FROM zasp_security_agent_plans plan WHERE (plan.organization_id,plan.workspace_id,plan.environment_id,plan.run_id,plan.plan_hash)=(organization_value,workspace_value,environment_value,run_value,run_row.plan_hash) AND plan.expires_at>transaction_timestamp() FOR SHARE;
  SELECT * INTO STRICT step_row FROM zasp_security_agent_steps step WHERE (step.organization_id,step.workspace_id,step.environment_id,step.run_id,step.action_key,step.state,step.authorization_result)=(organization_value,workspace_value,environment_value,run_value,'revoke_integration_connection','authorized','approval_required') FOR UPDATE;
  PERFORM 1 FROM zasp_security_agent_approvals approval WHERE (approval.organization_id,approval.workspace_id,approval.environment_id,approval.run_id,approval.step_id,approval.state,approval.plan_hash)=(organization_value,workspace_value,environment_value,run_value,step_row.step_id,'approved',run_row.plan_hash) AND approval.expires_at>transaction_timestamp() FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='connector revocation approval missing';END IF;
  IF NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key,execution_enabled)=('*','*','*','*',true)) OR NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key,execution_enabled)=(organization_value,workspace_value,environment_value,'*',true)) OR NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches WHERE (organization_id,workspace_id,environment_id,action_key,execution_enabled)=(organization_value,workspace_value,environment_value,'revoke_integration_connection',true)) THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='security agent execution disabled';END IF;
  SELECT item INTO STRICT plan_step FROM jsonb_array_elements(plan_row.plan->'steps') item WHERE item->>'step_id'=step_row.step_id AND item->>'action'='revoke_integration_connection';
  SELECT * INTO trigger_row FROM zasp_security_agent_trigger_receipts receipt WHERE (receipt.organization_id,receipt.workspace_id,receipt.environment_id,receipt.run_id,receipt.trigger_kind)=(organization_value,workspace_value,environment_value,run_value,'finding');IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent trigger changed';END IF;
  SELECT finding.version INTO finding_version FROM zasp_risk_findings finding WHERE (finding.organization_id,finding.workspace_id,finding.environment_id,finding.id,finding.status)=(organization_value,workspace_value,environment_value,trigger_row.trigger_id,'open') FOR SHARE;IF NOT FOUND OR finding_version<>trigger_row.trigger_version THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent finding changed';END IF;
  SELECT min(evidence.integration_id) INTO evidence_integration FROM zasp_risk_finding_evidence finding_evidence JOIN zasp_inventory_evidence evidence ON (evidence.organization_id,evidence.workspace_id,evidence.environment_id,evidence.id)=(finding_evidence.organization_id,finding_evidence.workspace_id,finding_evidence.environment_id,finding_evidence.evidence_id) WHERE (finding_evidence.organization_id,finding_evidence.workspace_id,finding_evidence.environment_id,finding_evidence.finding_id)=(organization_value,workspace_value,environment_value,trigger_row.trigger_id) HAVING count(DISTINCT evidence.integration_id)=1;IF NOT FOUND OR evidence_integration<>plan_step->>'integration_id' THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent evidence changed';END IF;
  SELECT * INTO STRICT workflow_row FROM zasp_workflow_records workflow WHERE (workflow.organization_id,workflow.workspace_id,workflow.environment_id,workflow.kind,workflow.id)=(organization_value,workspace_value,environment_value,'integration',plan_step->>'integration_id') AND workflow.deleted_at IS NULL AND workflow.body->>'status'='active' FOR UPDATE;
  SELECT * INTO STRICT connection_row FROM zasp_integration_connections connection WHERE (connection.organization_id,connection.workspace_id,connection.environment_id,connection.integration_id,connection.id,connection.state)=(organization_value,workspace_value,environment_value,plan_step->>'integration_id',plan_step->>'target_id','verified') AND connection.provider IN('github','okta') AND workflow_row.body->>'connector_key'=connection.provider AND EXISTS(SELECT 1 FROM zasp_integrations integration WHERE (integration.organization_id,integration.workspace_id,integration.environment_id,integration.id,integration.kind,integration.state)=(connection.organization_id,connection.workspace_id,connection.environment_id,connection.integration_id,connection.provider,'active')) AND (SELECT count(*) FROM zasp_integration_connections candidate_connection WHERE (candidate_connection.organization_id,candidate_connection.workspace_id,candidate_connection.environment_id,candidate_connection.integration_id,candidate_connection.state)=(organization_value,workspace_value,environment_value,plan_step->>'integration_id','verified'))=1 AND (SELECT count(*) FROM zasp_connector_credentials candidate_credential WHERE (candidate_credential.organization_id,candidate_credential.workspace_id,candidate_credential.environment_id,candidate_credential.integration_id,candidate_credential.status)=(organization_value,workspace_value,environment_value,plan_step->>'integration_id','active'))=1 FOR UPDATE;
  SELECT * INTO STRICT credential_row FROM zasp_connector_credentials credential WHERE (credential.organization_id,credential.workspace_id,credential.environment_id,credential.integration_id,credential.provider,credential.status)=(organization_value,workspace_value,environment_value,connection_row.integration_id,connection_row.provider,'active') AND credential.credential_reference=connection_row.connection_reference AND (connection_row.provider='github' AND credential.credential_class='github_installation_reference' AND CASE WHEN connection_row.connection_reference ~ '^ref:github/installation/[1-9][0-9]{0,19}$' THEN substring(connection_row.connection_reference FROM 25)::numeric<=9223372036854775807 ELSE false END OR connection_row.provider='okta' AND credential.credential_class='okta_refresh_reference' AND connection_row.connection_reference LIKE 'ref:okta/refresh/%' AND length(connection_row.connection_reference)>17) FOR UPDATE;
  IF EXISTS(SELECT 1 FROM zasp_connector_effects effect WHERE (effect.organization_id,effect.workspace_id,effect.environment_id,effect.integration_id,effect.operation)=(organization_value,workspace_value,environment_value,connection_row.integration_id,'revoke') AND effect.status IN('pending','unknown')) THEN RAISE EXCEPTION USING ERRCODE='23505',MESSAGE='connector revocation already active';END IF;
  effect_value:=zasp_discovery_canonical_id(organization_value,workspace_value,environment_value,'connector_effect','security-agent-revoke'||chr(31)||run_value||chr(31)||step_row.step_id);idempotency_value:='security-agent-revoke:'||run_value;
  request_digest_value:=digest(convert_to(jsonb_build_object('run_id',run_value,'step_id',step_row.step_id,'integration_id',connection_row.integration_id,'connection_id',connection_row.id,'connection_reference',connection_row.connection_reference,'credential_id',credential_row.id,'credential_version',credential_row.version,'input_digest','sha256:'||encode(step_row.input_digest,'hex'))::text,'UTF8'),'sha256');
  INSERT INTO zasp_security_agent_effects(organization_id,workspace_id,environment_id,run_id,step_id,action_key,input_digest,state) VALUES(organization_value,workspace_value,environment_value,run_value,step_row.step_id,'revoke_integration_connection',step_row.input_digest,'pending');
  INSERT INTO zasp_connector_effects(organization_id,workspace_id,environment_id,id,integration_id,provider,operation,idempotency_key,request_digest,status,connection_reference,last_error_code,updated_at) VALUES(organization_value,workspace_value,environment_value,effect_value,connection_row.integration_id,connection_row.provider,'revoke',idempotency_value,request_digest_value,'unknown',connection_row.connection_reference,'revocation_requested',transaction_timestamp()-interval '16 seconds');
  INSERT INTO zasp_security_agent_connector_revocations(organization_id,workspace_id,environment_id,run_id,step_id,connector_effect_id,integration_id,connection_id,credential_id,input_digest) VALUES(organization_value,workspace_value,environment_value,run_value,step_row.step_id,effect_value,connection_row.integration_id,connection_row.id,credential_row.id,step_row.input_digest);
  UPDATE zasp_workflow_records SET body=jsonb_set(jsonb_set(body,'{status}','"revoking"'::jsonb),'{updated_at}',to_jsonb(to_char(transaction_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))),version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,kind,id)=(organization_value,workspace_value,environment_value,'integration',connection_row.integration_id);
  UPDATE zasp_integrations SET state='degraded',version=greatest(version,workflow_row.version+1),updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,id,state)=(organization_value,workspace_value,environment_value,connection_row.integration_id,'active');
  UPDATE zasp_security_agent_steps SET state='executing',version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id,step_id)=(organization_value,workspace_value,environment_value,run_value,step_row.step_id);
  UPDATE zasp_security_agent_runs SET state='running',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id)=(organization_value,workspace_value,environment_value,run_value);
  outcome_value:=zasp_discovery_canonical_id(organization_value,workspace_value,environment_value,'security_agent_effect',run_value||chr(31)||step_row.step_id||chr(31)||'revoke_integration_connection');result_digest_value:=digest(convert_to(jsonb_build_object('run_id',run_value,'step_id',step_row.step_id,'action','revoke_integration_connection','state','pending','connector_effect_id',effect_value)::text,'UTF8'),'sha256');
  INSERT INTO zasp_security_agent_audit(organization_id,workspace_id,environment_id,audit_id,correlation_id,run_id,step_id,actor_id,event_kind,event_digest,body) VALUES(organization_value,workspace_value,environment_value,audit_value,correlation_value,run_value,step_row.step_id,worker_value,'effect_dispatched',result_digest_value,jsonb_build_object('run_id',run_value,'step_id',step_row.step_id,'action','revoke_integration_connection','target_id',connection_row.id,'integration_id',connection_row.integration_id,'outcome_id',outcome_value));
  RETURN jsonb_build_object('run_id',run_value,'state','running','version',run_row.version+1,'step_id',step_row.step_id,'effect_state','pending','outcome_id',outcome_value,'result_digest','sha256:'||encode(result_digest_value,'hex'));
END
$dispatch$;

CREATE FUNCTION public.zasp_security_agent_execute_run_v23(organization_value text,workspace_value text,environment_value text,run_value text,worker_value text,lease_token_value text,audit_value text,correlation_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $execute_all$
DECLARE action_value text;
BEGIN
  SELECT step.action_key INTO action_value FROM zasp_security_agent_steps step WHERE (step.organization_id,step.workspace_id,step.environment_id,step.run_id)=(organization_value,workspace_value,environment_value,run_value);
  IF action_value='revoke_integration_connection' THEN RETURN zasp_security_agent_dispatch_connector_revocation_run(organization_value,workspace_value,environment_value,run_value,worker_value,lease_token_value,audit_value,correlation_value);END IF;
  RETURN zasp_security_agent_execute_run_v22(organization_value,workspace_value,environment_value,run_value,worker_value,lease_token_value,audit_value,correlation_value);
END
$execute_all$;

CREATE OR REPLACE FUNCTION public.zasp_connector_complete_revocation(organization_value text,workspace_value text,environment_value text,effect_value text,owner_value text,token_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $complete$
DECLARE effect_row zasp_connector_effects%ROWTYPE;link_row zasp_security_agent_connector_revocations%ROWTYPE;credential_row zasp_connector_credentials%ROWTYPE;workflow_row zasp_workflow_records%ROWTYPE;
BEGIN
  SELECT * INTO link_row FROM zasp_security_agent_connector_revocations link WHERE (link.organization_id,link.workspace_id,link.environment_id,link.connector_effect_id)=(organization_value,workspace_value,environment_value,effect_value) FOR UPDATE;
  IF NOT FOUND THEN RETURN zasp_connector_complete_revocation_v22(organization_value,workspace_value,environment_value,effect_value,owner_value,token_value);END IF;
  SELECT * INTO effect_row FROM zasp_connector_effects effect WHERE (effect.organization_id,effect.workspace_id,effect.environment_id,effect.id,effect.operation)=(organization_value,workspace_value,environment_value,effect_value,'revoke') FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='connector revocation unavailable';END IF;
  IF effect_row.status='reconciled' THEN RETURN jsonb_build_object('id',effect_row.id,'status',effect_row.status,'attempt',effect_row.attempt,'updated_at',effect_row.updated_at);END IF;
  IF effect_row.status<>'unknown' OR effect_row.lease_owner IS DISTINCT FROM owner_value OR effect_row.lease_token IS DISTINCT FROM token_value OR effect_row.lease_expires_at IS NULL OR effect_row.lease_expires_at<=transaction_timestamp() THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='connector revocation lease unavailable';END IF;
  SELECT * INTO workflow_row FROM zasp_workflow_records workflow WHERE (workflow.organization_id,workflow.workspace_id,workflow.environment_id,workflow.kind,workflow.id)=(organization_value,workspace_value,environment_value,'integration',link_row.integration_id) AND workflow.deleted_at IS NULL AND workflow.body->>'status'='revoking' FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23505',MESSAGE='security agent public revocation conflict';END IF;
  PERFORM 1 FROM zasp_integration_connections connection WHERE (connection.organization_id,connection.workspace_id,connection.environment_id,connection.id,connection.integration_id,connection.state)=(organization_value,workspace_value,environment_value,link_row.connection_id,link_row.integration_id,'verified') FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23505',MESSAGE='security agent connection revocation conflict';END IF;
  SELECT * INTO credential_row FROM zasp_connector_credentials credential WHERE (credential.organization_id,credential.workspace_id,credential.environment_id,credential.id,credential.integration_id,credential.status)=(organization_value,workspace_value,environment_value,link_row.credential_id,link_row.integration_id,'active') FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23505',MESSAGE='security agent credential revocation conflict';END IF;
  UPDATE zasp_integration_connections SET state='revoked',revoked_at=transaction_timestamp(),version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,id,integration_id,state)=(organization_value,workspace_value,environment_value,link_row.connection_id,link_row.integration_id,'verified');
  UPDATE zasp_connector_credentials SET status='revoked',revoked_at=transaction_timestamp(),updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,id,integration_id,status)=(organization_value,workspace_value,environment_value,link_row.credential_id,link_row.integration_id,'active');
  UPDATE zasp_workflow_records SET body=jsonb_set(jsonb_set(body,'{status}','"pending_authorization"'::jsonb),'{updated_at}',to_jsonb(to_char(transaction_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))),version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,kind,id)=(organization_value,workspace_value,environment_value,'integration',link_row.integration_id) RETURNING * INTO workflow_row;
  UPDATE zasp_integrations SET state='pending',credential_reference=NULL,version=greatest(version,workflow_row.version),updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,id,state)=(organization_value,workspace_value,environment_value,link_row.integration_id,'degraded');IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23505',MESSAGE='security agent typed revocation conflict';END IF;
  UPDATE zasp_connector_effects SET status='reconciled',provider_subject='revoked',last_error_code=NULL,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,resolved_at=transaction_timestamp(),updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,id)=(organization_value,workspace_value,environment_value,effect_value) RETURNING * INTO effect_row;
  PERFORM zasp_connector_audit_event(organization_value,workspace_value,environment_value,effect_row.integration_id,'',effect_row.id,'effect_resolved','','','{}'::jsonb);PERFORM zasp_connector_audit_event(organization_value,workspace_value,environment_value,effect_row.integration_id,'',effect_row.id,'credential_revoked','','',jsonb_build_object('class',credential_row.credential_class));PERFORM zasp_connector_audit_event(organization_value,workspace_value,environment_value,effect_row.integration_id,'',effect_row.id,'revocation_completed','','','{}'::jsonb);
  RETURN jsonb_build_object('id',effect_row.id,'status',effect_row.status,'attempt',effect_row.attempt,'updated_at',effect_row.updated_at);
END
$complete$;

CREATE FUNCTION public.zasp_security_agent_reconcile_connector_revocations(worker_value text,limit_value integer) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $reconcile$
DECLARE item record;count_value integer:=0;outcome_value text;result_digest_value bytea;audit_value text;correlation_value text;verification_drift boolean;
BEGIN
  IF NOT zasp_security_agent_action_principal_ready() OR length(worker_value) NOT BETWEEN 1 AND 128 OR limit_value NOT BETWEEN 1 AND 25 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='connector revocation verification rejected';END IF;
  FOR item IN SELECT link.*,connector.status connector_status,connector.last_error_code FROM zasp_security_agent_connector_revocations link JOIN zasp_connector_effects connector ON (connector.organization_id,connector.workspace_id,connector.environment_id,connector.id)=(link.organization_id,link.workspace_id,link.environment_id,link.connector_effect_id) WHERE link.state='pending' AND (connector.status='reconciled' OR connector.status='failed' OR connector.status='unknown' AND connector.attempt=100 AND connector.last_error_code='provider_revocation_ambiguous') ORDER BY connector.updated_at,link.organization_id,link.workspace_id,link.environment_id,link.run_id FOR UPDATE OF link SKIP LOCKED LIMIT limit_value
  LOOP
    verification_drift:=false;
    IF item.connector_status='reconciled' THEN
      PERFORM 1 FROM zasp_workflow_records workflow WHERE (workflow.organization_id,workflow.workspace_id,workflow.environment_id,workflow.kind,workflow.id)=(item.organization_id,item.workspace_id,item.environment_id,'integration',item.integration_id) FOR UPDATE;
      verification_drift:=NOT FOUND OR NOT EXISTS(SELECT 1 FROM zasp_workflow_records workflow WHERE (workflow.organization_id,workflow.workspace_id,workflow.environment_id,workflow.kind,workflow.id)=(item.organization_id,item.workspace_id,item.environment_id,'integration',item.integration_id) AND workflow.deleted_at IS NULL AND workflow.body->>'status'='pending_authorization') OR NOT EXISTS(SELECT 1 FROM zasp_integration_connections connection WHERE (connection.organization_id,connection.workspace_id,connection.environment_id,connection.id,connection.integration_id,connection.state)=(item.organization_id,item.workspace_id,item.environment_id,item.connection_id,item.integration_id,'revoked')) OR EXISTS(SELECT 1 FROM zasp_connector_credentials credential WHERE (credential.organization_id,credential.workspace_id,credential.environment_id,credential.integration_id,credential.status)=(item.organization_id,item.workspace_id,item.environment_id,item.integration_id,'active'));
    END IF;
    IF item.connector_status='reconciled' AND NOT verification_drift THEN
      outcome_value:=zasp_discovery_canonical_id(item.organization_id,item.workspace_id,item.environment_id,'security_agent_effect',item.run_id||chr(31)||item.step_id||chr(31)||'revoke_integration_connection');result_digest_value:=digest(convert_to(jsonb_build_object('integration_id',item.integration_id,'connection_id',item.connection_id,'state','revoked','connector_effect_id',item.connector_effect_id)::text,'UTF8'),'sha256');
      UPDATE zasp_security_agent_connector_revocations SET state='verified',completed_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id,step_id)=(item.organization_id,item.workspace_id,item.environment_id,item.run_id,item.step_id);
      UPDATE zasp_security_agent_effects SET state='verified',outcome_id=outcome_value,result_digest=result_digest_value,version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id,step_id,action_key,state)=(item.organization_id,item.workspace_id,item.environment_id,item.run_id,item.step_id,'revoke_integration_connection','pending');
      UPDATE zasp_security_agent_steps SET state='succeeded',version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id,step_id,state)=(item.organization_id,item.workspace_id,item.environment_id,item.run_id,item.step_id,'executing');
      UPDATE zasp_security_agent_runs SET state='remediated',version=version+1,updated_at=transaction_timestamp(),completed_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id,state)=(item.organization_id,item.workspace_id,item.environment_id,item.run_id,'running');
      audit_value:=zasp_discovery_canonical_id(item.organization_id,item.workspace_id,item.environment_id,'security_agent_audit',item.run_id||chr(31)||'connector-revocation-verified');correlation_value:=zasp_discovery_canonical_id(item.organization_id,item.workspace_id,item.environment_id,'security_agent_correlation',item.run_id||chr(31)||'connector-revocation-verified');
      INSERT INTO zasp_security_agent_audit(organization_id,workspace_id,environment_id,audit_id,correlation_id,run_id,step_id,actor_id,event_kind,event_digest,body) VALUES(item.organization_id,item.workspace_id,item.environment_id,audit_value,correlation_value,item.run_id,item.step_id,worker_value,'effect_verified',result_digest_value,jsonb_build_object('run_id',item.run_id,'step_id',item.step_id,'action','revoke_integration_connection','integration_id',item.integration_id,'connection_id',item.connection_id,'outcome_id',outcome_value,'result_digest','sha256:'||encode(result_digest_value,'hex')));
    ELSE
      UPDATE zasp_security_agent_connector_revocations SET state='needs_human',completed_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id,step_id)=(item.organization_id,item.workspace_id,item.environment_id,item.run_id,item.step_id);
      UPDATE zasp_security_agent_effects SET state='unknown_outcome',version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id,step_id,action_key,state)=(item.organization_id,item.workspace_id,item.environment_id,item.run_id,item.step_id,'revoke_integration_connection','pending');
      UPDATE zasp_security_agent_steps SET state='inconclusive',version=version+1,updated_at=transaction_timestamp() WHERE (organization_id,workspace_id,environment_id,run_id,step_id,state)=(item.organization_id,item.workspace_id,item.environment_id,item.run_id,item.step_id,'executing');
      UPDATE zasp_security_agent_runs SET state='needs_human',version=version+1,updated_at=transaction_timestamp(),completed_at=transaction_timestamp(),last_error_code=CASE WHEN verification_drift THEN 'connector_state_drift' ELSE 'provider_revocation_ambiguous' END WHERE (organization_id,workspace_id,environment_id,run_id,state)=(item.organization_id,item.workspace_id,item.environment_id,item.run_id,'running');
    END IF;
    count_value:=count_value+1;
  END LOOP;
  RETURN jsonb_build_object('reconciled',count_value);
END
$reconcile$;

CREATE FUNCTION public.zasp_security_agent_approval_value_v23(organization_value text,workspace_value text,environment_value text,approval_value text) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $approval_value$
DECLARE prior jsonb;step_action text;
BEGIN
  SELECT step.action_key INTO STRICT step_action FROM zasp_security_agent_approvals approval JOIN zasp_security_agent_steps step ON (step.organization_id,step.workspace_id,step.environment_id,step.run_id,step.step_id)=(approval.organization_id,approval.workspace_id,approval.environment_id,approval.run_id,approval.step_id) WHERE (approval.organization_id,approval.workspace_id,approval.environment_id,approval.approval_id)=(organization_value,workspace_value,environment_value,approval_value);
  IF step_action<>'revoke_integration_connection' THEN RETURN zasp_security_agent_approval_value_v22(organization_value,workspace_value,environment_value,approval_value);END IF;
  SELECT jsonb_build_object('id',approval.approval_id,'run_id',approval.run_id,'step_id',approval.step_id,'state',approval.state,'expires_at',to_char(approval.expires_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'version',approval.version,'expected_effect','Revoke integration connection','reversible',false,'ttl_seconds',0,'evidence_summary',jsonb_build_array(run.trigger_id)) INTO STRICT prior FROM zasp_security_agent_approvals approval JOIN zasp_security_agent_runs run ON (run.organization_id,run.workspace_id,run.environment_id,run.run_id)=(approval.organization_id,approval.workspace_id,approval.environment_id,approval.run_id) WHERE (approval.organization_id,approval.workspace_id,approval.environment_id,approval.approval_id)=(organization_value,workspace_value,environment_value,approval_value);
  RETURN prior;
END
$approval_value$;
CREATE FUNCTION public.zasp_security_agent_run_detail_v23(organization_value text,workspace_value text,environment_value text,run_value text) RETURNS SETOF jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $detail$ SELECT value||jsonb_build_object('approvals',COALESCE((SELECT jsonb_agg(zasp_security_agent_approval_value_v23(approval.organization_id,approval.workspace_id,approval.environment_id,approval.approval_id) ORDER BY approval.created_at,approval.approval_id) FROM zasp_security_agent_approvals approval WHERE (approval.organization_id,approval.workspace_id,approval.environment_id,approval.run_id)=(organization_value,workspace_value,environment_value,run_value)),'[]'::jsonb)) FROM zasp_security_agent_run_detail(organization_value,workspace_value,environment_value,run_value) detail(value) $detail$;
CREATE FUNCTION public.zasp_security_agent_approval_page_v23(organization_value text,workspace_value text,environment_value text,state_value text,run_value text,before_created_value timestamptz,before_id_value text,limit_value integer) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $page$ DECLARE page_value jsonb;items_value jsonb;BEGIN page_value:=zasp_security_agent_approval_page(organization_value,workspace_value,environment_value,state_value,run_value,before_created_value,before_id_value,limit_value);SELECT COALESCE(jsonb_agg(zasp_security_agent_approval_value_v23(organization_value,workspace_value,environment_value,item.value->>'id') ORDER BY item.ordinality),'[]'::jsonb) INTO items_value FROM jsonb_array_elements(page_value->'items') WITH ORDINALITY item(value,ordinality);RETURN jsonb_set(page_value,'{items}',items_value,false);END $page$;
CREATE FUNCTION public.zasp_security_agent_approval_detail_v23(organization_value text,workspace_value text,environment_value text,approval_value text) RETURNS SETOF jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $detail$ SELECT zasp_security_agent_approval_value_v23(organization_value,workspace_value,environment_value,approval_value) WHERE EXISTS(SELECT 1 FROM zasp_security_agent_approval_detail(organization_value,workspace_value,environment_value,approval_value)) $detail$;
CREATE FUNCTION public.zasp_security_agent_decide_approval_v23(organization_value text,workspace_value text,environment_value text,approval_value text,actor_value text,idempotency_value text,expected_version bigint,decision_value text,fresh_auth_value timestamptz,audit_value text,correlation_value text,receipt_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $decide$
DECLARE response_value jsonb;
BEGIN
  IF decision_value='approved'
     AND EXISTS(
       SELECT 1
       FROM zasp_security_agent_approvals approval
       JOIN zasp_security_agent_steps step ON (step.organization_id,step.workspace_id,step.environment_id,step.run_id,step.step_id)=(approval.organization_id,approval.workspace_id,approval.environment_id,approval.run_id,approval.step_id)
       WHERE (approval.organization_id,approval.workspace_id,approval.environment_id,approval.approval_id)=(organization_value,workspace_value,environment_value,approval_value)
         AND step.action_key='revoke_integration_connection'
     )
     AND NOT zasp_identity_admin_authorized(organization_value,actor_value) THEN
    RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='security agent irreversible approval rejected';
  END IF;
  response_value:=zasp_security_agent_decide_approval(organization_value,workspace_value,environment_value,approval_value,actor_value,idempotency_value,expected_version,decision_value,fresh_auth_value,audit_value,correlation_value,receipt_value);
  RETURN response_value||zasp_security_agent_approval_value_v23(organization_value,workspace_value,environment_value,approval_value);
END
$decide$;

DO $functions$ DECLARE procedure_oid oid;BEGIN
  FOR procedure_oid IN SELECT procedure.oid FROM pg_proc procedure JOIN pg_namespace namespace ON namespace.oid=procedure.pronamespace WHERE namespace.nspname='public' AND procedure.proname=ANY(ARRAY['zasp_security_agent_schedule_connector_revocation_triggers','zasp_security_agent_schedule_triggers_v23','zasp_security_agent_claim_runs_v23','zasp_security_agent_prepare_connector_revocation_run','zasp_security_agent_prepare_run_v23','zasp_security_agent_dispatch_connector_revocation_run','zasp_security_agent_execute_run_v23','zasp_security_agent_reconcile_connector_revocations','zasp_security_agent_approval_value_v23','zasp_security_agent_run_detail_v23','zasp_security_agent_approval_page_v23','zasp_security_agent_approval_detail_v23','zasp_security_agent_decide_approval_v23']) LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO zasp_discovery_authority',procedure_oid::regprocedure);EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,zasp_security_agent_api,zasp_security_agent_worker,zasp_security_agent_action_worker,zasp_discovery_api,zasp_discovery_worker',procedure_oid::regprocedure);END LOOP;
END
$functions$;
GRANT EXECUTE ON FUNCTION public.zasp_security_agent_schedule_triggers_v23(text,integer),public.zasp_security_agent_claim_runs_v23(text,text,integer,integer),public.zasp_security_agent_prepare_run_v23(text,text,text,text,text,text,text,timestamptz,text,text),public.zasp_security_agent_execute_run_v23(text,text,text,text,text,text,text,text) TO zasp_security_agent_worker;
GRANT EXECUTE ON FUNCTION public.zasp_security_agent_run_detail_v23(text,text,text,text),public.zasp_security_agent_approval_page_v23(text,text,text,text,text,timestamptz,text,integer),public.zasp_security_agent_approval_detail_v23(text,text,text,text),public.zasp_security_agent_decide_approval_v23(text,text,text,text,text,text,bigint,text,timestamptz,text,text,text) TO zasp_security_agent_api;
GRANT EXECUTE ON FUNCTION public.zasp_security_agent_reconcile_connector_revocations(text,integer) TO zasp_security_agent_action_worker;

CREATE FUNCTION public.zasp_security_agent_connector_revocation_security_ready() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $security$
  SELECT zasp_security_agent_temporary_policy_security_ready()
    AND EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.zasp_security_agent_definitions'::regclass AND conname='zasp_security_agent_connector_revocation_supervised_check' AND convalidated)
    AND has_function_privilege('zasp_security_agent_worker','public.zasp_security_agent_schedule_triggers_v23(text,integer)','EXECUTE') AND has_function_privilege('zasp_security_agent_worker','public.zasp_security_agent_prepare_run_v23(text,text,text,text,text,text,text,timestamptz,text,text)','EXECUTE') AND has_function_privilege('zasp_security_agent_worker','public.zasp_security_agent_execute_run_v23(text,text,text,text,text,text,text,text)','EXECUTE')
    AND has_function_privilege('zasp_security_agent_action_worker','public.zasp_security_agent_reconcile_connector_revocations(text,integer)','EXECUTE') AND NOT has_function_privilege('zasp_security_agent_action_worker','public.zasp_connector_complete_revocation(text,text,text,text,text,text)','EXECUTE')
    AND has_function_privilege('zasp_security_agent_api','public.zasp_security_agent_run_detail_v23(text,text,text,text)','EXECUTE') AND has_function_privilege('zasp_security_agent_api','public.zasp_security_agent_decide_approval_v23(text,text,text,text,text,text,bigint,text,timestamptz,text,text,text)','EXECUTE')
    AND to_regprocedure('public.zasp_connector_complete_revocation_v22(text,text,text,text,text,text)') IS NOT NULL
    AND to_regprocedure('public.zasp_security_agent_execution_control_detail_v22_restore(text,text,text)') IS NOT NULL
    AND to_regprocedure('public.zasp_security_agent_mutate_execution_control_v22_restore(text,text,text,text,text,text,text,boolean,bigint,timestamptz,text,text,text)') IS NOT NULL
$security$;

CREATE FUNCTION public.zasp_security_agent_connector_revocation_live_fingerprint() RETURNS text LANGUAGE sql STABLE SET search_path TO pg_catalog, public AS $fingerprint$
  WITH identities(value) AS (
    SELECT concat_ws('|','table',class.relname,owner.rolname,class.relrowsecurity,class.relforcerowsecurity,COALESCE(class.relacl::text,'')) FROM pg_class class JOIN pg_namespace namespace ON namespace.oid=class.relnamespace JOIN pg_roles owner ON owner.oid=class.relowner WHERE namespace.nspname='public' AND class.relname='zasp_security_agent_connector_revocations' AND class.relkind IN('r','i')
    UNION ALL SELECT concat_ws('|','column',attribute.attname,attribute.atttypid::regtype::text,attribute.attnotnull,attribute.attidentity,attribute.attgenerated,COALESCE(pg_get_expr(default_value.adbin,default_value.adrelid),'')) FROM pg_attribute attribute LEFT JOIN pg_attrdef default_value ON default_value.adrelid=attribute.attrelid AND default_value.adnum=attribute.attnum WHERE attribute.attrelid='public.zasp_security_agent_connector_revocations'::regclass AND attribute.attnum>0 AND NOT attribute.attisdropped
    UNION ALL SELECT concat_ws('|','table_constraint',constraint_value.conname,constraint_value.contype,constraint_value.convalidated,constraint_value.condeferrable,constraint_value.condeferred,pg_get_constraintdef(constraint_value.oid,true)) FROM pg_constraint constraint_value WHERE constraint_value.conrelid='public.zasp_security_agent_connector_revocations'::regclass
    UNION ALL SELECT concat_ws('|','index',index_class.relname,index_value.indisvalid,index_value.indisready,index_value.indisunique,index_value.indisprimary,pg_get_indexdef(index_value.indexrelid)) FROM pg_index index_value JOIN pg_class index_class ON index_class.oid=index_value.indexrelid WHERE index_value.indrelid='public.zasp_security_agent_connector_revocations'::regclass
    UNION ALL SELECT concat_ws('|','policy',policy.polname,policy.polcmd,policy.polpermissive,COALESCE((SELECT string_agg(CASE WHEN role_oid=0 THEN 'PUBLIC' ELSE role_value.rolname END,',' ORDER BY CASE WHEN role_oid=0 THEN 'PUBLIC' ELSE role_value.rolname END) FROM unnest(policy.polroles) role_oid LEFT JOIN pg_roles role_value ON role_value.oid=role_oid),''),COALESCE(pg_get_expr(policy.polqual,policy.polrelid),''),COALESCE(pg_get_expr(policy.polwithcheck,policy.polrelid),'')) FROM pg_policy policy WHERE policy.polrelid='public.zasp_security_agent_connector_revocations'::regclass
    UNION ALL SELECT concat_ws('|','function',procedure.proname,pg_get_function_identity_arguments(procedure.oid),owner.rolname,procedure.prosecdef,COALESCE(procedure.proconfig::text,''),COALESCE(procedure.proacl::text,''),pg_get_functiondef(procedure.oid)) FROM pg_proc procedure JOIN pg_namespace namespace ON namespace.oid=procedure.pronamespace JOIN pg_roles owner ON owner.oid=procedure.proowner WHERE namespace.nspname='public' AND procedure.proname=ANY(ARRAY['zasp_security_agent_execution_control_detail','zasp_security_agent_execution_control_detail_v22_restore','zasp_security_agent_mutate_execution_control','zasp_security_agent_mutate_execution_control_v22_restore','zasp_security_agent_schedule_connector_revocation_triggers','zasp_security_agent_schedule_triggers_v23','zasp_security_agent_claim_runs_v23','zasp_security_agent_prepare_connector_revocation_run','zasp_security_agent_prepare_run_v23','zasp_security_agent_dispatch_connector_revocation_run','zasp_security_agent_execute_run_v23','zasp_security_agent_reconcile_connector_revocations','zasp_security_agent_approval_value_v23','zasp_security_agent_run_detail_v23','zasp_security_agent_approval_page_v23','zasp_security_agent_approval_detail_v23','zasp_security_agent_decide_approval_v23','zasp_connector_complete_revocation','zasp_connector_complete_revocation_v22','zasp_security_agent_connector_revocation_security_ready','zasp_workflow_mutate','zasp_risk_mutate'])
    UNION ALL SELECT concat_ws('|','constraint',conname,convalidated,pg_get_constraintdef(oid,true)) FROM pg_constraint WHERE conrelid='public.zasp_security_agent_definitions'::regclass AND conname='zasp_security_agent_connector_revocation_supervised_check'
  ) SELECT encode(digest(convert_to(string_agg(value,E'\n' ORDER BY value),'UTF8'),'sha256'),'hex') FROM identities
$fingerprint$;

CREATE FUNCTION public.zasp_security_agent_connector_revocation_readiness(expected_checksum text,expected_fingerprint text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $readiness$
  SELECT length(expected_checksum)=64 AND expected_checksum~'^[a-f0-9]{64}$' AND length(expected_fingerprint)=64 AND expected_fingerprint~'^[a-f0-9]{64}$'
    AND EXISTS(SELECT 1 FROM zasp_schema_versions WHERE version=23 AND name='security_agent_connector_revocation' AND checksum=expected_checksum)
    AND EXISTS(SELECT 1 FROM zasp_schema_metadata WHERE key='production_core_schema' AND value='security-agent-connector-revocation-v1') AND NOT EXISTS(SELECT 1 FROM zasp_schema_versions WHERE version>23)
    AND zasp_security_agent_connector_revocation_security_ready() AND zasp_security_agent_connector_revocation_live_fingerprint()=expected_fingerprint
$readiness$;
ALTER FUNCTION public.zasp_security_agent_connector_revocation_security_ready() OWNER TO zasp_discovery_authority;
ALTER FUNCTION public.zasp_security_agent_connector_revocation_live_fingerprint() OWNER TO zasp_discovery_authority;
ALTER FUNCTION public.zasp_security_agent_connector_revocation_readiness(text,text) OWNER TO zasp_discovery_authority;
REVOKE ALL ON FUNCTION public.zasp_security_agent_connector_revocation_security_ready(),public.zasp_security_agent_connector_revocation_live_fingerprint(),public.zasp_security_agent_connector_revocation_readiness(text,text) FROM PUBLIC,zasp_discovery_api,zasp_discovery_worker,zasp_security_agent_api,zasp_security_agent_worker,zasp_security_agent_action_worker,zasp_runtime_ingest,zasp_runtime_worker,zasp_outbox_worker,zasp_runtime_gateway,zasp_discovery_scheduler,zasp_projection_risk_worker,zasp_projection_graph_worker,zasp_projection_search_worker,zasp_runtime_coordinator,zasp_runtime_archive_worker,zasp_runtime_index_worker,zasp_runtime_correlation_worker,zasp_runtime_projection_worker,zasp_gateway_control;
GRANT EXECUTE ON FUNCTION public.zasp_security_agent_connector_revocation_readiness(text,text) TO zasp_discovery_api,zasp_discovery_worker,zasp_security_agent_api,zasp_security_agent_worker,zasp_security_agent_action_worker,zasp_runtime_ingest,zasp_runtime_worker,zasp_outbox_worker,zasp_runtime_gateway,zasp_discovery_scheduler,zasp_projection_risk_worker,zasp_projection_graph_worker,zasp_projection_search_worker,zasp_runtime_coordinator,zasp_runtime_archive_worker,zasp_runtime_index_worker,zasp_runtime_correlation_worker,zasp_runtime_projection_worker,zasp_gateway_control;

UPDATE public.zasp_schema_metadata SET value='security-agent-connector-revocation-v1',applied_at=transaction_timestamp() WHERE key='production_core_schema' AND value='security-agent-temporary-policy-v1';
INSERT INTO public.zasp_schema_metadata(key,value) VALUES('security_agent_connector_revocation_fingerprint', '65cb411e946fa081b4c2ab7cf38e07ac0c9487af4d5a09d7fb55b8aa9bc066cc') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
