 WITH relations AS(
 SELECT c.oid FROM pg_class c WHERE c.relnamespace='zasp_authorization80_inventory'::regnamespace OR c.oid IN('public.zasp_inventory_entities'::regclass,'public.zasp_inventory_annotations'::regclass,'public.zasp_inventory_capability_evidence'::regclass,'public.zasp_inventory_relationships'::regclass,'public.zasp_inventory_source_observations'::regclass,'public.zasp_inventory_evidence'::regclass,'public.zasp_discovery_snapshots'::regclass,'public.zasp_runtime_session_events'::regclass,'public.zasp_runtime_session_summaries'::regclass,'public.zasp_inventory_cutover_state'::regclass,'public.zasp_workflow_idempotency'::regclass,'public.zasp_workflow_audit'::regclass)
 ),facts(v) AS(
 SELECT jsonb_build_array('schema',nspname,nspowner::regrole::text,nspacl::text) FROM pg_namespace WHERE nspname='zasp_authorization80_inventory'
 UNION ALL SELECT jsonb_build_array('function',p.oid::regprocedure::text,p.proowner::regrole::text,p.proacl::text,pg_get_functiondef(p.oid)) FROM pg_proc p WHERE p.pronamespace='zasp_authorization80_inventory'::regnamespace OR(p.pronamespace='public'::regnamespace AND p.proname LIKE 'zasp_inventory_%')
 UNION ALL SELECT jsonb_build_array('relation',c.oid::regclass::text,c.relkind,c.relowner::regrole::text,c.relacl::text,c.relrowsecurity,c.relforcerowsecurity) FROM pg_class c JOIN relations r ON r.oid=c.oid
 UNION ALL SELECT jsonb_build_array('column',a.attrelid::regclass::text,a.attnum,a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attacl::text,a.attidentity,a.attgenerated,a.attcollation::regcollation::text,pg_get_expr(d.adbin,d.adrelid)) FROM pg_attribute a JOIN relations r ON r.oid=a.attrelid LEFT JOIN pg_attrdef d ON(d.adrelid,d.adnum)=(a.attrelid,a.attnum) WHERE a.attnum>0 AND NOT a.attisdropped
 UNION ALL SELECT jsonb_build_array('constraint',k.conrelid::regclass::text,k.conname,pg_get_constraintdef(k.oid),k.convalidated) FROM pg_constraint k JOIN relations r ON r.oid=k.conrelid
 UNION ALL SELECT jsonb_build_array('policy',p.polrelid::regclass::text,p.polname,p.polpermissive,p.polcmd,p.polroles::regrole[]::text,pg_get_expr(p.polqual,p.polrelid),pg_get_expr(p.polwithcheck,p.polrelid)) FROM pg_policy p JOIN relations r ON r.oid=p.polrelid
 UNION ALL SELECT jsonb_build_array('index',i.indrelid::regclass::text,pg_get_indexdef(i.indexrelid),i.indisvalid,i.indisready,i.indislive) FROM pg_index i JOIN relations r ON r.oid=i.indrelid
 UNION ALL SELECT jsonb_build_array('trigger',t.tgrelid::regclass::text,t.tgname,t.tgenabled,pg_get_triggerdef(t.oid),t.tgfoid::regprocedure::text) FROM pg_trigger t JOIN relations r ON r.oid=t.tgrelid WHERE NOT t.tgisinternal
 ) SELECT jsonb_agg(v ORDER BY v::text) FROM facts
