SELECT COALESCE((SELECT count(*)=1 FROM zasp_authorization80_identity.registration)
 AND zasp_authorization80_identity.projected19()='-- identity19 fingerprint'
 AND EXISTS(SELECT 1 FROM zasp_authorization80_identity.registration r WHERE r.catalog=(
 WITH facts(v) AS (
 SELECT jsonb_build_array('predecessor',definition,owner_name,acl) FROM zasp_authorization80_identity.predecessor
 UNION ALL
 SELECT jsonb_build_array('schema',nspname,nspowner::regrole::text,nspacl::text) FROM pg_namespace WHERE nspname='zasp_authorization80_identity'
 UNION ALL SELECT jsonb_build_array('function',p.oid::regprocedure::text,p.proowner::regrole::text,p.proacl::text,pg_get_functiondef(p.oid)) FROM pg_proc p WHERE p.pronamespace='zasp_authorization80_identity'::regnamespace OR p.oid IN('public.zasp_identity_admin_resolve_session(text,text,jsonb)'::regprocedure,'public.zasp_identity_admin_reconcile_deprovision(text,text,text,text,bytea,text)'::regprocedure,'public.zasp_identity_admin_effective_scopes(text,text)'::regprocedure,'public.zasp_create_product_session(text,text,text,text,text,text,jsonb,timestamp with time zone)'::regprocedure,'zasp_authorization80.unique_json(json,integer)'::regprocedure)
 UNION ALL SELECT jsonb_build_array('relation',c.oid::regclass::text,c.relkind,c.relowner::regrole::text,c.relacl::text,c.relrowsecurity,c.relforcerowsecurity) FROM pg_class c WHERE c.relnamespace='zasp_authorization80_identity'::regnamespace OR c.oid IN('public.zasp_identity_states'::regclass,'public.zasp_identity_memberships'::regclass,'public.zasp_identity_member_groups'::regclass,'public.zasp_product_sessions'::regclass,'public.zasp_product_api_tokens'::regclass,'public.zasp_group_mappings'::regclass,'public.zasp_admin_idempotency'::regclass,'public.zasp_api_token_reveal_grants'::regclass)
 UNION ALL SELECT jsonb_build_array('column',c.oid::regclass::text,a.attnum,a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attacl::text,a.attidentity,a.attgenerated,a.attcollation::regcollation::text,pg_get_expr(d.adbin,d.adrelid)) FROM pg_class c JOIN pg_attribute a ON a.attrelid=c.oid LEFT JOIN pg_attrdef d ON(d.adrelid,d.adnum)=(a.attrelid,a.attnum) WHERE(c.relnamespace='zasp_authorization80_identity'::regnamespace OR c.oid IN('public.zasp_identity_states'::regclass,'public.zasp_identity_memberships'::regclass,'public.zasp_identity_member_groups'::regclass,'public.zasp_product_sessions'::regclass,'public.zasp_product_api_tokens'::regclass,'public.zasp_group_mappings'::regclass,'public.zasp_admin_idempotency'::regclass,'public.zasp_api_token_reveal_grants'::regclass)) AND a.attnum>0 AND NOT a.attisdropped
 UNION ALL SELECT jsonb_build_array('constraint',c.oid::regclass::text,k.conname,pg_get_constraintdef(k.oid),k.convalidated) FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid WHERE c.relnamespace='zasp_authorization80_identity'::regnamespace OR c.oid IN('public.zasp_identity_states'::regclass,'public.zasp_identity_memberships'::regclass,'public.zasp_identity_member_groups'::regclass,'public.zasp_product_sessions'::regclass,'public.zasp_product_api_tokens'::regclass,'public.zasp_group_mappings'::regclass,'public.zasp_admin_idempotency'::regclass,'public.zasp_api_token_reveal_grants'::regclass)
 UNION ALL SELECT jsonb_build_array('index',c.oid::regclass::text,pg_get_indexdef(i.indexrelid),i.indisvalid,i.indisready,i.indislive) FROM pg_index i JOIN pg_class c ON c.oid=i.indrelid WHERE c.relnamespace='zasp_authorization80_identity'::regnamespace OR c.oid IN('public.zasp_identity_states'::regclass,'public.zasp_identity_memberships'::regclass,'public.zasp_identity_member_groups'::regclass,'public.zasp_product_sessions'::regclass,'public.zasp_product_api_tokens'::regclass,'public.zasp_group_mappings'::regclass,'public.zasp_admin_idempotency'::regclass,'public.zasp_api_token_reveal_grants'::regclass)
 UNION ALL SELECT jsonb_build_array('policy',p.polrelid::regclass::text,p.polname,p.polpermissive,p.polcmd,p.polroles::regrole[]::text,pg_get_expr(p.polqual,p.polrelid),pg_get_expr(p.polwithcheck,p.polrelid)) FROM pg_policy p JOIN pg_class c ON c.oid=p.polrelid WHERE c.relnamespace='zasp_authorization80_identity'::regnamespace OR c.oid IN('public.zasp_identity_states'::regclass,'public.zasp_identity_memberships'::regclass,'public.zasp_identity_member_groups'::regclass,'public.zasp_product_sessions'::regclass,'public.zasp_product_api_tokens'::regclass,'public.zasp_group_mappings'::regclass,'public.zasp_admin_idempotency'::regclass,'public.zasp_api_token_reveal_grants'::regclass)
 UNION ALL SELECT jsonb_build_array('trigger',t.tgrelid::regclass::text,t.tgname,t.tgenabled,pg_get_triggerdef(t.oid),t.tgfoid::regprocedure::text) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid WHERE NOT t.tgisinternal AND(c.relnamespace='zasp_authorization80_identity'::regnamespace OR c.oid IN('public.zasp_identity_states'::regclass,'public.zasp_identity_memberships'::regclass,'public.zasp_identity_member_groups'::regclass,'public.zasp_product_sessions'::regclass,'public.zasp_product_api_tokens'::regclass,'public.zasp_group_mappings'::regclass,'public.zasp_admin_idempotency'::regclass,'public.zasp_api_token_reveal_grants'::regclass))
 ) SELECT jsonb_agg(v ORDER BY v::text) FROM facts)),false)
