-- New source-only routines derived from immutable22; no old routine replaced.

CREATE FUNCTION zasp_sa_temporary81.prepare_run(organization_value text,workspace_value text,environment_value text,run_value text,worker_value text,lease_token_value text,approval_value text,approval_expires_value timestamptz,audit_value text,correlation_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $prepare$
DECLARE run_row zasp_security_agent_runs%ROWTYPE;definition_row zasp_security_agent_definitions%ROWTYPE;trigger_row zasp_security_agent_trigger_receipts%ROWTYPE;finding_version bigint;step_value text;plan_value jsonb;plan_digest bytea;
BEGIN
  IF NOT zasp_security_agent_principal_ready('zasp_security_agent_worker') OR NOT zasp_valid_product_id(run_value) OR NOT zasp_valid_product_id(approval_value) OR NOT zasp_valid_product_id(audit_value) OR NOT zasp_valid_product_id(correlation_value) OR length(worker_value) NOT BETWEEN 1 AND 128 OR length(lease_token_value) NOT BETWEEN 16 AND 128 OR approval_expires_value<=transaction_timestamp() OR approval_expires_value>transaction_timestamp()+interval '16 minutes' THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='temporary policy plan rejected';END IF;
  SELECT * INTO run_row FROM zasp_security_agent_runs run WHERE (run.organization_id,run.workspace_id,run.environment_id,run.run_id,run.state,run.lease_owner,run.lease_token)=(organization_value,workspace_value,environment_value,run_value,'planning',worker_value,lease_token_value) AND run.lease_expires_at>transaction_timestamp() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent lease lost';END IF;
  SELECT * INTO STRICT definition_row FROM zasp_security_agent_definitions definition WHERE (definition.organization_id,definition.workspace_id,definition.environment_id,definition.definition_id,definition.version)=(organization_value,workspace_value,environment_value,run_row.definition_id,run_row.definition_version) AND definition.activation='supervised' AND definition.deleted_at IS NULL AND definition.body->'allowed_actions'=jsonb_build_array('create_temporary_policy') AND definition.body->>'verification_kind'='policy_state' AND (definition.body->>'temporary_policy_seconds')::integer BETWEEN 60 AND 3600 FOR SHARE;
  SELECT * INTO STRICT trigger_row FROM zasp_security_agent_trigger_receipts receipt WHERE (receipt.organization_id,receipt.workspace_id,receipt.environment_id,receipt.run_id,receipt.trigger_kind)=(organization_value,workspace_value,environment_value,run_value,'finding');
  SELECT finding.version INTO finding_version FROM zasp_risk_findings finding WHERE (finding.organization_id,finding.workspace_id,finding.environment_id,finding.id,finding.status)=(organization_value,workspace_value,environment_value,trigger_row.trigger_id,'open') FOR SHARE;
  IF NOT FOUND OR finding_version<>trigger_row.trigger_version THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent evidence changed';END IF;
  PERFORM 1 FROM zasp_security_agent_definition_versions v WHERE (v.organization_id,v.workspace_id,v.environment_id,v.definition_id,v.version,v.definition)=(organization_value,workspace_value,environment_value,run_row.definition_id,run_row.definition_version,definition_row.body) AND v.definition_digest=digest(convert_to(v.definition::text,'UTF8'),'sha256');
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='temporary saved definition version unavailable';END IF;
  step_value:=zasp_discovery_canonical_id(organization_value,workspace_value,environment_value,'security_agent_step',run_value||chr(31)||'0');
  plan_value:=jsonb_build_object('definition_id',run_row.definition_id,'definition_version',run_row.definition_version,'catalog_version','security-agent-actions-v1','evidence_ids',jsonb_build_array(trigger_row.trigger_id),'steps',jsonb_build_array(jsonb_build_object('index',0,'step_id',step_value,'action','create_temporary_policy','target_id',environment_value,'mode',zasp_sa_temporary81.definition_mode(definition_row.body),'scope',environment_value,'ttl_seconds',(definition_row.body->>'temporary_policy_seconds')::integer,'authorization','approval_required')),'verification',jsonb_build_object('kind','policy_state','expected_state','active'),'expires_at',to_char(approval_expires_value AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
  plan_digest:=digest(convert_to(plan_value::text,'UTF8'),'sha256');
  INSERT INTO zasp_security_agent_plans(organization_id,workspace_id,environment_id,run_id,definition_id,definition_version,trigger_digest,catalog_version,plan,plan_hash,expires_at) VALUES(organization_value,workspace_value,environment_value,run_value,run_row.definition_id,run_row.definition_version,trigger_row.trigger_digest,'security-agent-actions-v1',plan_value,plan_digest,approval_expires_value);
  INSERT INTO zasp_security_agent_steps(organization_id,workspace_id,environment_id,run_id,step_id,step_index,action_key,input_digest,authorization_result,state) VALUES(organization_value,workspace_value,environment_value,run_value,step_value,0,'create_temporary_policy',digest(convert_to((plan_value->'steps'->0)::text,'UTF8'),'sha256'),'approval_required','waiting_approval');
  INSERT INTO zasp_security_agent_approvals(organization_id,workspace_id,environment_id,approval_id,run_id,step_id,plan_hash,state,requester_id,expires_at) VALUES(organization_value,workspace_value,environment_value,approval_value,run_value,step_value,plan_digest,'pending',run_row.requested_by,approval_expires_value);
  UPDATE zasp_security_agent_runs run SET state='waiting_approval',plan_hash=plan_digest,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,version=run.version+1,updated_at=transaction_timestamp() WHERE (run.organization_id,run.workspace_id,run.environment_id,run.run_id)=(organization_value,workspace_value,environment_value,run_value);
  INSERT INTO zasp_security_agent_audit(organization_id,workspace_id,environment_id,audit_id,correlation_id,run_id,step_id,approval_id,actor_id,event_kind,event_digest,body) VALUES(organization_value,workspace_value,environment_value,audit_value,correlation_value,run_value,step_value,approval_value,worker_value,'approval_requested',plan_digest,jsonb_build_object('run_id',run_value,'step_id',step_value,'action','create_temporary_policy','approval_id',approval_value,'plan_hash','sha256:'||encode(plan_digest,'hex')));
  RETURN jsonb_build_object('run_id',run_value,'state','waiting_approval','version',run_row.version+1,'approval_id',approval_value,'step_id',step_value,'plan_hash','sha256:'||encode(plan_digest,'hex'));
END
$prepare$;

CREATE FUNCTION zasp_sa_temporary81.dispatch_run(organization_value text,workspace_value text,environment_value text,run_value text,worker_value text,lease_token_value text,audit_value text,correlation_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $dispatch$
DECLARE run_row zasp_security_agent_runs%ROWTYPE;plan_row zasp_security_agent_plans%ROWTYPE;step_row zasp_security_agent_steps%ROWTYPE;outcome_value text;result_digest_value bytea;
BEGIN
  IF NOT zasp_security_agent_principal_ready('zasp_security_agent_worker') OR NOT zasp_valid_product_id(run_value) OR NOT zasp_valid_product_id(audit_value) OR NOT zasp_valid_product_id(correlation_value) OR length(worker_value) NOT BETWEEN 1 AND 128 OR length(lease_token_value) NOT BETWEEN 16 AND 128 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='temporary policy dispatch rejected';END IF;
  SELECT * INTO run_row FROM zasp_security_agent_runs run WHERE (run.organization_id,run.workspace_id,run.environment_id,run.run_id,run.state,run.lease_owner,run.lease_token)=(organization_value,workspace_value,environment_value,run_value,'planning',worker_value,lease_token_value) AND run.lease_expires_at>transaction_timestamp() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='security agent lease lost';END IF;
  SELECT * INTO STRICT plan_row FROM zasp_security_agent_plans plan WHERE (plan.organization_id,plan.workspace_id,plan.environment_id,plan.run_id,plan.plan_hash)=(organization_value,workspace_value,environment_value,run_value,run_row.plan_hash) AND plan.expires_at>transaction_timestamp() FOR SHARE;
  SELECT * INTO STRICT step_row FROM zasp_security_agent_steps step WHERE (step.organization_id,step.workspace_id,step.environment_id,step.run_id,step.action_key,step.state,step.authorization_result)=(organization_value,workspace_value,environment_value,run_value,'create_temporary_policy','authorized','approval_required') FOR UPDATE;
  PERFORM 1 FROM zasp_security_agent_approvals approval WHERE (approval.organization_id,approval.workspace_id,approval.environment_id,approval.run_id,approval.step_id,approval.state,approval.plan_hash)=(organization_value,workspace_value,environment_value,run_value,step_row.step_id,'approved',run_row.plan_hash) AND approval.expires_at>transaction_timestamp() FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='temporary policy approval missing';END IF;
  IF NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches switch WHERE (switch.organization_id,switch.workspace_id,switch.environment_id,switch.action_key,switch.execution_enabled)=('*','*','*','*',true)) OR NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches switch WHERE (switch.organization_id,switch.workspace_id,switch.environment_id,switch.action_key,switch.execution_enabled)=(organization_value,workspace_value,environment_value,'*',true)) OR NOT EXISTS(SELECT 1 FROM zasp_security_agent_kill_switches switch WHERE (switch.organization_id,switch.workspace_id,switch.environment_id,switch.action_key,switch.execution_enabled)=(organization_value,workspace_value,environment_value,'create_temporary_policy',true)) THEN RAISE EXCEPTION USING ERRCODE='55000',MESSAGE='security agent execution disabled';END IF;
  PERFORM zasp_sa_temporary81.plan_mode(organization_value,workspace_value,environment_value,run_value,step_row.step_id);
  INSERT INTO zasp_security_agent_effects(organization_id,workspace_id,environment_id,run_id,step_id,action_key,input_digest,state) VALUES(organization_value,workspace_value,environment_value,run_value,step_row.step_id,'create_temporary_policy',step_row.input_digest,'pending');
  UPDATE zasp_security_agent_steps step SET state='executing',version=step.version+1,updated_at=transaction_timestamp() WHERE (step.organization_id,step.workspace_id,step.environment_id,step.run_id,step.step_id)=(organization_value,workspace_value,environment_value,run_value,step_row.step_id);
  UPDATE zasp_security_agent_runs run SET state='running',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,version=run.version+1,updated_at=transaction_timestamp() WHERE (run.organization_id,run.workspace_id,run.environment_id,run.run_id)=(organization_value,workspace_value,environment_value,run_value);
  outcome_value:=zasp_discovery_canonical_id(organization_value,workspace_value,environment_value,'security_agent_effect',run_value||chr(31)||step_row.step_id||chr(31)||'create_temporary_policy');
  result_digest_value:=digest(convert_to(jsonb_build_object('run_id',run_value,'step_id',step_row.step_id,'action','create_temporary_policy','state','pending')::text,'UTF8'),'sha256');
  INSERT INTO zasp_security_agent_audit(organization_id,workspace_id,environment_id,audit_id,correlation_id,run_id,step_id,actor_id,event_kind,event_digest,body) VALUES(organization_value,workspace_value,environment_value,audit_value,correlation_value,run_value,step_row.step_id,worker_value,'effect_dispatched',result_digest_value,jsonb_build_object('run_id',run_value,'step_id',step_row.step_id,'action','create_temporary_policy','outcome_id',outcome_value));
  RETURN jsonb_build_object('run_id',run_value,'state','running','version',run_row.version+1,'step_id',step_row.step_id,'effect_state','pending','outcome_id',outcome_value,'result_digest','sha256:'||encode(result_digest_value,'hex'));
END
$dispatch$;

CREATE FUNCTION zasp_sa_temporary81.approval_value(organization_value text,workspace_value text,environment_value text,approval_value text) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $approval_value$
DECLARE approval_row zasp_security_agent_approvals%ROWTYPE;run_row zasp_security_agent_runs%ROWTYPE;step_row zasp_security_agent_steps%ROWTYPE;plan_row zasp_security_agent_plans%ROWTYPE;expected_effect_value text;ttl_seconds_value integer;
BEGIN
  SELECT * INTO STRICT approval_row FROM zasp_security_agent_approvals approval WHERE (approval.organization_id,approval.workspace_id,approval.environment_id,approval.approval_id)=(organization_value,workspace_value,environment_value,approval_value);
  SELECT * INTO STRICT run_row FROM zasp_security_agent_runs run WHERE (run.organization_id,run.workspace_id,run.environment_id,run.run_id)=(organization_value,workspace_value,environment_value,approval_row.run_id);
  SELECT * INTO STRICT step_row FROM zasp_security_agent_steps step WHERE (step.organization_id,step.workspace_id,step.environment_id,step.run_id,step.step_id)=(organization_value,workspace_value,environment_value,approval_row.run_id,approval_row.step_id);
  SELECT * INTO STRICT plan_row FROM zasp_security_agent_plans plan WHERE (plan.organization_id,plan.workspace_id,plan.environment_id,plan.run_id,plan.plan_hash)=(organization_value,workspace_value,environment_value,approval_row.run_id,approval_row.plan_hash);
  IF step_row.action_key='update_finding_response' THEN expected_effect_value:='Move finding to under review';ttl_seconds_value:=0;
  ELSIF step_row.action_key='create_temporary_policy' THEN
    expected_effect_value:=CASE zasp_sa_temporary81.plan_mode(organization_value,workspace_value,environment_value,approval_row.run_id,approval_row.step_id) WHEN 'monitor' THEN 'Apply temporary monitoring policy' ELSE 'Apply temporary containment policy' END;
    SELECT (item->>'ttl_seconds')::integer INTO STRICT ttl_seconds_value FROM jsonb_array_elements(plan_row.plan->'steps') item WHERE item->>'step_id'=approval_row.step_id AND item->>'action'='create_temporary_policy';
    IF ttl_seconds_value NOT BETWEEN 60 AND 3600 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='security agent approval ttl rejected';END IF;
  ELSE RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='security agent approval effect rejected';END IF;
  RETURN jsonb_build_object('id',approval_row.approval_id,'run_id',approval_row.run_id,'step_id',approval_row.step_id,'state',approval_row.state,'expires_at',to_char(approval_row.expires_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'version',approval_row.version,'expected_effect',expected_effect_value,'reversible',true,'ttl_seconds',ttl_seconds_value,'evidence_summary',jsonb_build_array(run_row.trigger_id));
END
$approval_value$;

CREATE FUNCTION zasp_sa_temporary81.approval_detail(organization_value text,workspace_value text,environment_value text,approval_value text) RETURNS SETOF jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO pg_catalog, public AS $approval_detail$
  SELECT zasp_sa_temporary81.approval_value(organization_value,workspace_value,environment_value,approval_value)
  WHERE EXISTS(SELECT 1 FROM zasp_security_agent_approval_detail(organization_value,workspace_value,environment_value,approval_value))
$approval_detail$;

CREATE FUNCTION zasp_sa_temporary81.decide_approval(organization_value text,workspace_value text,environment_value text,approval_value text,actor_value text,idempotency_value text,expected_version bigint,decision_value text,fresh_auth_value timestamptz,audit_value text,correlation_value text,receipt_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO pg_catalog, public AS $decide$
DECLARE response_value jsonb;
BEGIN
  response_value:=zasp_security_agent_decide_approval(organization_value,workspace_value,environment_value,approval_value,actor_value,idempotency_value,expected_version,decision_value,fresh_auth_value,audit_value,correlation_value,receipt_value);
  RETURN response_value||zasp_sa_temporary81.approval_value(organization_value,workspace_value,environment_value,approval_value);
END
$decide$;
