WITH direct_class_index AS MATERIALIZED (SELECT c.oid::regclass::text AS identity, n.nspname::text AS namespace, c.relname::text AS selector_name, c.relkind::text AS selector_relation_kind, pg_catalog.jsonb_build_object('definition',pg_catalog.pg_get_indexdef(c.oid),'name',c.relname::text) AS fact FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE (((n.nspname::text='public') AND ((c.relname::text LIKE 'zasp_recovery_%') AND (c.relkind::text='i'))) OR ((n.nspname::text='public') AND ((c.relname::text LIKE 'zasp_policy_deployment_%') AND (c.relkind::text='i'))))),
direct_column_all AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(a.attname::text)::text||']' AS identity, n.nspname::text AS namespace, a.attname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('default_text_or_empty',COALESCE(pg_catalog.pg_get_expr(d.adbin,d.adrelid),''),'name',a.attname::text,'not_null',a.attnotnull,'relation_name',c.relname::text,'type_identity',a.atttypid::regtype::text) AS fact FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_catalog.pg_attrdef d ON (d.adrelid,d.adnum)=(a.attrelid,a.attnum) WHERE (((n.nspname::text='public') AND ((c.relname::text='zasp_runtime_gateway_events') AND (a.attname::text='policy_ids')))) AND (NOT a.attisdropped)),
direct_column_name AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(a.attname::text)::text||']' AS identity, n.nspname::text AS namespace, a.attname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('acl_text_or_empty',COALESCE(a.attacl::text,''),'default_text_or_empty',COALESCE(pg_catalog.pg_get_expr(d.adbin,d.adrelid),''),'generated',a.attgenerated::text,'identity',a.attidentity::text,'name',a.attname::text,'not_null',a.attnotnull,'relation',c.oid::regclass::text,'relation_name',c.relname::text,'type',pg_catalog.format_type(a.atttypid,a.atttypmod),'type_identity',a.atttypid::regtype::text) AS fact FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_catalog.pg_attrdef d ON (d.adrelid,d.adnum)=(a.attrelid,a.attnum) WHERE ((c.oid::regclass::text='public.zasp_security_agent_temporary_policy_targets') OR ((n.nspname::text='public') AND (c.relname::text LIKE 'zasp_recovery_%')) OR ((n.nspname::text='public') AND ((c.relname::text LIKE 'zasp_policy_deployment_%') OR ((c.relname::text='zasp_security_agent_temporary_policy_targets') OR (c.relname::text='zasp_security_agent_session_policy_targets')))) OR ((c.oid::regclass::text='public.zasp_runtime_session_events') OR (c.oid::regclass::text='public.zasp_runtime_session_projection_receipts')) OR (c.oid::regclass::text='public.zasp_runtime_session_events') OR (c.oid::regclass::text='public.zasp_runtime_sandbox_search_outbox')) AND (a.attnum>0 AND NOT a.attisdropped)),
direct_constraint AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(k.conname::text)::text||']' AS identity, n.nspname::text AS namespace, k.conname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('constraint_type',k.contype::text,'deferrable',k.condeferrable,'deferred',k.condeferred,'definition',pg_catalog.pg_get_constraintdef(k.oid),'definition_pretty',pg_catalog.pg_get_constraintdef(k.oid,true),'name',k.conname::text,'relation_name',c.relname::text,'validated',k.convalidated) AS fact FROM pg_catalog.pg_constraint k JOIN pg_catalog.pg_class c ON c.oid=k.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE ((c.oid::regclass::text='public.zasp_security_agent_temporary_policy_targets') OR ((c.oid::regclass::text='public.zasp_security_agent_definitions') AND (k.conname::text='zasp_security_agent_session_isolation_supervised_check')) OR (c.relname::text LIKE 'zasp_recovery_%') OR ((c.relname::text='zasp_runtime_gateway_events') AND (k.conname::text='zasp_runtime_gateway_events_policy_ids_v27_ck')) OR (c.relname::text LIKE 'zasp_policy_deployment_%') OR ((c.oid::regclass::text='public.zasp_runtime_session_events') OR (c.oid::regclass::text='public.zasp_runtime_session_projection_receipts')) OR (c.oid::regclass::text='public.zasp_runtime_sandbox_search_outbox'))),
direct_foreign_key_trigger AS MATERIALIZED (SELECT '['||pg_catalog.to_json(k.conrelid::regclass::text)::text||','||pg_catalog.to_json(k.conname::text)::text||','||pg_catalog.to_json(t.tgrelid::regclass::text)::text||','||pg_catalog.to_json(t.tgfoid::regprocedure::text)::text||','||pg_catalog.to_json(t.tgtype)::text||']' AS identity, n.nspname::text AS namespace, k.conname::text AS selector_name, k.conrelid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('argument_count',t.tgnargs,'arguments',pg_catalog.encode(t.tgargs,'hex'),'columns_text',t.tgattr::text,'constraint_relation',t.tgconstrrelid::regclass::text,'deferrable',t.tgdeferrable,'deferred',t.tginitdeferred,'enabled',t.tgenabled::text,'event_bits',t.tgtype,'function',t.tgfoid::regprocedure::text,'name',k.conname::text,'referenced_relation',k.confrelid::regclass::text,'relation',k.conrelid::regclass::text,'trigger_relation',t.tgrelid::regclass::text,'when_text_or_empty',COALESCE(CASE WHEN t.tgqual IS NULL THEN NULL ELSE pg_catalog.pg_get_triggerdef(t.oid,true) END,'')) AS fact FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_constraint k ON k.oid=t.tgconstraint JOIN pg_catalog.pg_class c ON c.oid=k.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE (((n.nspname::text='public') AND ((c.relname::text='zasp_integrations') OR (c.relname::text='zasp_integration_connections') OR (c.relname::text='zasp_discovery_connection_subjects') OR (c.relname::text='zasp_connector_credentials') OR (c.relname::text='zasp_discovery_syncs') OR (c.relname::text='zasp_discovery_outbox') OR (c.relname::text='zasp_discovery_outbox_topic_fairness') OR (c.relname::text='zasp_discovery_generation_reservations') OR (c.relname::text='zasp_discovery_jobs') OR (c.relname::text='zasp_discovery_job_authorities') OR (c.relname::text='zasp_discovery_job_checkpoints') OR (c.relname::text='zasp_discovery_execution_quotas') OR (c.relname::text='zasp_discovery_snapshots') OR (c.relname::text='zasp_discovery_cursors') OR (c.relname::text='zasp_inventory_entities') OR (c.relname::text='zasp_inventory_evidence') OR (c.relname::text='zasp_inventory_source_observations') OR (c.relname::text='zasp_inventory_relationships') OR (c.relname::text='zasp_inventory_identity_rules') OR (c.relname::text='zasp_inventory_identity_bindings') OR (c.relname::text='zasp_projection_work') OR (c.relname::text='zasp_discovery_snapshot_inputs') OR (c.relname::text='zasp_discovery_snapshot_projection_items'))) OR (n.nspname::text='zasp_temporal68') OR (n.nspname::text='zasp_temporal69') OR (n.nspname::text='zasp_temporal72') OR (n.nspname::text='zasp_temporal78')) AND (t.tgisinternal AND k.contype='f')),
direct_index AS MATERIALIZED (SELECT i.indexrelid::regclass::text AS identity, n.nspname::text AS namespace, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, index_class.relname::text AS selector_name, pg_catalog.jsonb_build_object('definition',pg_catalog.pg_get_indexdef(i.indexrelid),'name',index_class.relname::text,'owner',index_class.relowner::regrole::text,'primary',i.indisprimary,'ready',i.indisready,'unique',i.indisunique,'valid',i.indisvalid) AS fact FROM pg_catalog.pg_index i JOIN pg_catalog.pg_class c ON c.oid=i.indrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_class index_class ON index_class.oid=i.indexrelid WHERE ((((c.oid::regclass::text='public.zasp_runtime_gateway_events') AND (index_class.relname::text='zasp_runtime_gateway_events_session_v24_idx')) OR (c.oid::regclass::text='public.zasp_security_agent_temporary_policy_targets')) OR ((c.oid::regclass::text='public.zasp_runtime_gateway_events') AND ((index_class.relname::text='zasp_runtime_gateway_events_policy_ids_v27_idx') OR (index_class.relname::text='zasp_runtime_gateway_events_policy_history_v27_idx'))))),
direct_index_view AS MATERIALIZED (SELECT '['||pg_catalog.to_json(v.schemaname::text)::text||','||pg_catalog.to_json(v.tablename::text)::text||','||pg_catalog.to_json(v.indexname::text)::text||']' AS identity, v.schemaname::text AS namespace, v.indexname::text AS selector_name, v.schemaname::text||'.'||v.tablename::text AS selector_relation, v.tablename::text AS selector_relation_name, v.tablename::text AS selector_table_name, pg_catalog.jsonb_build_object('definition',v.indexdef::text,'name',v.indexname::text) AS fact FROM pg_catalog.pg_indexes v WHERE (((v.schemaname::text='public') AND ((v.tablename::text='zasp_runtime_session_events') OR (v.tablename::text='zasp_runtime_session_projection_receipts'))) OR ((v.schemaname::text='public') AND (v.tablename::text='zasp_runtime_sandbox_search_outbox')))),
direct_policy AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(p.polname::text)::text||']' AS identity, n.nspname::text AS namespace, p.polname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('check',pg_catalog.pg_get_expr(p.polwithcheck,p.polrelid),'name',p.polname::text,'permissive',p.polpermissive,'relation_name',c.relname::text,'using',pg_catalog.pg_get_expr(p.polqual,p.polrelid)) AS fact FROM pg_catalog.pg_policy p JOIN pg_catalog.pg_class c ON c.oid=p.polrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE ((c.relname::text LIKE 'zasp_recovery_%') OR (c.relname::text LIKE 'zasp_policy_deployment_%'))),
direct_policy_view AS MATERIALIZED (SELECT '['||pg_catalog.to_json(v.schemaname::text)::text||','||pg_catalog.to_json(v.tablename::text)::text||','||pg_catalog.to_json(v.policyname::text)::text||']' AS identity, v.schemaname::text AS namespace, v.policyname::text AS selector_name, v.schemaname::text||'.'||v.tablename::text AS selector_relation, v.tablename::text AS selector_relation_name, v.tablename::text AS selector_table_name, pg_catalog.jsonb_build_object('check',v.with_check::text,'command',v.cmd::text,'name',v.policyname::text,'namespace_name',v.schemaname::text,'roles_text',v.roles::text,'table_name',v.tablename::text,'using',v.qual::text) AS fact FROM pg_catalog.pg_policies v WHERE (((v.schemaname::text='public') AND ((v.tablename::text='zasp_runtime_session_events') OR (v.tablename::text='zasp_runtime_session_projection_receipts'))) OR ((v.schemaname::text='public') AND (v.tablename::text='zasp_runtime_sandbox_search_outbox')))),
direct_relation AS MATERIALIZED (SELECT c.oid::regclass::text AS identity, n.nspname::text AS namespace, c.relname::text AS selector_name, c.relkind::text AS selector_relation_kind, pg_catalog.jsonb_build_object('acl_text_or_empty',COALESCE(c.relacl::text,''),'forced_row_security',c.relforcerowsecurity,'kind',c.relkind::text,'name',c.relname::text,'owner',c.relowner::regrole::text,'persistence',c.relpersistence::text,'row_security',c.relrowsecurity) AS fact FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE (((n.nspname::text='public') AND ((c.relname::text='zasp_integrations') OR (c.relname::text='zasp_integration_connections') OR (c.relname::text='zasp_discovery_connection_subjects') OR (c.relname::text='zasp_connector_credentials') OR (c.relname::text='zasp_discovery_syncs') OR (c.relname::text='zasp_discovery_outbox') OR (c.relname::text='zasp_discovery_outbox_topic_fairness') OR (c.relname::text='zasp_discovery_generation_reservations') OR (c.relname::text='zasp_discovery_jobs') OR (c.relname::text='zasp_discovery_job_authorities') OR (c.relname::text='zasp_discovery_job_checkpoints') OR (c.relname::text='zasp_discovery_execution_quotas') OR (c.relname::text='zasp_discovery_snapshots') OR (c.relname::text='zasp_discovery_cursors') OR (c.relname::text='zasp_inventory_entities') OR (c.relname::text='zasp_inventory_evidence') OR (c.relname::text='zasp_inventory_source_observations') OR (c.relname::text='zasp_inventory_relationships') OR (c.relname::text='zasp_inventory_identity_rules') OR (c.relname::text='zasp_inventory_identity_bindings') OR (c.relname::text='zasp_projection_work') OR (c.relname::text='zasp_discovery_snapshot_inputs') OR (c.relname::text='zasp_discovery_snapshot_projection_items'))) OR (n.nspname::text='zasp_ordered_public62') OR (n.nspname::text='zasp_temporal68') OR (n.nspname::text='zasp_temporal69') OR (n.nspname::text='zasp_temporal72') OR (n.nspname::text='zasp_temporal78') OR ((n.nspname::text='public') AND ((c.relname::text='zasp_security_agent_temporary_policy_targets') AND ((c.relkind::text='r') OR (c.relkind::text='i')))) OR ((n.nspname::text='public') AND ((c.relname::text LIKE 'zasp_recovery_%') AND ((c.relkind::text='r') OR (c.relkind::text='i')))) OR ((n.nspname::text='public') AND ((c.relname::text LIKE 'zasp_policy_deployment_%') AND ((c.relkind::text='r') OR (c.relkind::text='i')))) OR ((c.oid::regclass::text='public.zasp_runtime_session_events') OR (c.oid::regclass::text='public.zasp_runtime_session_projection_receipts')) OR (c.oid::regclass::text='public.zasp_runtime_sandbox_search_outbox'))),
direct_role AS MATERIALIZED (SELECT r.rolname::text AS identity, ''::text AS namespace, r.rolname::text AS selector_name, pg_catalog.jsonb_build_object('bypass_rls',r.rolbypassrls,'create_db',r.rolcreatedb,'create_role',r.rolcreaterole,'inherit',r.rolinherit,'login',r.rolcanlogin,'name',r.rolname::text,'replication',r.rolreplication,'superuser',r.rolsuper) AS fact FROM pg_catalog.pg_roles r WHERE (((r.rolname::text='zasp_recovery_worker') OR (r.rolname::text='zasp_recovery_outbox_worker')) OR (r.rolname::text='zasp_policy_deployment_worker'))),
direct_routine AS MATERIALIZED (SELECT p.oid::regprocedure::text AS identity, n.nspname::text AS namespace, p.proname::text AS selector_name, pg_catalog.jsonb_build_object('acl_text_or_empty',COALESCE(p.proacl::text,''),'config_text_or_empty',COALESCE(p.proconfig::text,''),'definition',CASE WHEN p.prokind<>'a' THEN pg_catalog.pg_get_functiondef(p.oid) ELSE NULL END,'identity_arguments',pg_catalog.pg_get_function_identity_arguments(p.oid),'name',p.proname::text,'owner',p.proowner::regrole::text,'security_definer',p.prosecdef) AS fact FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace JOIN pg_catalog.pg_language l ON l.oid=p.prolang WHERE (((n.nspname::text='public') AND ((p.proname::text='zasp_runtime_claim_session_stage_compatible') OR (p.proname::text='zasp_runtime_session_claim_version_guard') OR (p.proname::text='zasp_runtime_claim_projection_v2') OR (p.proname::text='zasp_runtime_claim_completion_v2'))) OR (p.oid::regprocedure::text='public.zasp_runtime_finish_sandbox_session_projection(text,text,text,text,bigint,text,text,integer,bytea,text,text,bytea,text,text,bytea,text,integer,bytea)') OR ((p.oid::regprocedure::text::regprocedure='public.zasp_runtime_sandbox_session_event_page(text,text,text,text,text,timestamptz,text,integer)'::regprocedure) OR (p.oid::regprocedure::text::regprocedure='public.zasp_runtime_sandbox_session_event_get(text,text,text,text,text,text)'::regprocedure)) OR ((n.nspname::text='public') AND ((p.proname::text='zasp_runtime_claim_stage_sandbox_compatible') OR (p.proname::text='zasp_runtime_claim_correlation_v3') OR (p.proname::text='zasp_runtime_freeze_sandbox_candidates') OR (p.proname::text='zasp_production_runtime_sandbox_binding_security_ready') OR (p.proname::text='zasp_production_runtime_sandbox_binding_readiness') OR (p.proname::text='zasp_production_runtime_correlation_routing_readiness_v49') OR (p.proname::text='zasp_production_runtime_candidate_authority_live_fingerprint'))))),
direct_trigger AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(t.tgname::text)::text||']' AS identity, n.nspname::text AS namespace, t.tgname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, t.tgfoid::regprocedure::text AS selector_function, t.tgisinternal AS internal, pg_catalog.jsonb_build_object('definition',pg_catalog.pg_get_triggerdef(t.oid),'definition_pretty',pg_catalog.pg_get_triggerdef(t.oid,true),'enabled',t.tgenabled::text,'name',t.tgname::text,'relation',c.oid::regclass::text,'relation_name',c.relname::text) AS fact FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE (((n.nspname::text='public') AND (t.tgname::text LIKE '%_recovery_hold')) OR ((t.tgname::text LIKE '%policy_deployment%') OR (t.tgname::text LIKE '%policy_sequence') OR (t.tgname::text LIKE '%policy_verify')) OR ((c.oid::regclass::text='public.zasp_runtime_stage_work') AND (t.tgname::text='zasp_runtime_session_claim_version')) OR ((c.oid::regclass::text='public.zasp_runtime_session_projection_receipts') OR (c.oid::regclass::text='public.zasp_runtime_sandbox_search_outbox') OR (c.oid::regclass::text='public.zasp_runtime_session_search_outbox'))))
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker:projected_domain:table'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','kind',fact->'kind','name',fact->'name','owner',fact->'owner','persistence',fact->'persistence','row_security',fact->'row_security') AS fact FROM direct_relation WHERE (((namespace='public') AND ((selector_name='zasp_integrations') OR (selector_name='zasp_integration_connections') OR (selector_name='zasp_discovery_connection_subjects') OR (selector_name='zasp_connector_credentials') OR (selector_name='zasp_discovery_syncs') OR (selector_name='zasp_discovery_outbox') OR (selector_name='zasp_discovery_outbox_topic_fairness') OR (selector_name='zasp_discovery_generation_reservations') OR (selector_name='zasp_discovery_jobs') OR (selector_name='zasp_discovery_job_authorities') OR (selector_name='zasp_discovery_job_checkpoints') OR (selector_name='zasp_discovery_execution_quotas') OR (selector_name='zasp_discovery_snapshots') OR (selector_name='zasp_discovery_cursors') OR (selector_name='zasp_inventory_entities') OR (selector_name='zasp_inventory_evidence') OR (selector_name='zasp_inventory_source_observations') OR (selector_name='zasp_inventory_relationships') OR (selector_name='zasp_inventory_identity_rules') OR (selector_name='zasp_inventory_identity_bindings') OR (selector_name='zasp_projection_work') OR (selector_name='zasp_discovery_snapshot_inputs') OR (selector_name='zasp_discovery_snapshot_projection_items'))))
UNION ALL
SELECT 'foreign_key_trigger'::text AS kind, '['||pg_catalog.to_json('worker:projected_domain:foreign-key-trigger'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('argument_count',fact->'argument_count','arguments',fact->'arguments','columns_text',fact->'columns_text','constraint_relation',fact->'constraint_relation','deferrable',fact->'deferrable','deferred',fact->'deferred','enabled',fact->'enabled','event_bits',fact->'event_bits','function',fact->'function','name',fact->'name','referenced_relation',fact->'referenced_relation','relation',fact->'relation','trigger_relation',fact->'trigger_relation','when_text_or_empty',fact->'when_text_or_empty') AS fact FROM direct_foreign_key_trigger WHERE (((namespace='public') AND ((selector_relation_name='zasp_integrations') OR (selector_relation_name='zasp_integration_connections') OR (selector_relation_name='zasp_discovery_connection_subjects') OR (selector_relation_name='zasp_connector_credentials') OR (selector_relation_name='zasp_discovery_syncs') OR (selector_relation_name='zasp_discovery_outbox') OR (selector_relation_name='zasp_discovery_outbox_topic_fairness') OR (selector_relation_name='zasp_discovery_generation_reservations') OR (selector_relation_name='zasp_discovery_jobs') OR (selector_relation_name='zasp_discovery_job_authorities') OR (selector_relation_name='zasp_discovery_job_checkpoints') OR (selector_relation_name='zasp_discovery_execution_quotas') OR (selector_relation_name='zasp_discovery_snapshots') OR (selector_relation_name='zasp_discovery_cursors') OR (selector_relation_name='zasp_inventory_entities') OR (selector_relation_name='zasp_inventory_evidence') OR (selector_relation_name='zasp_inventory_source_observations') OR (selector_relation_name='zasp_inventory_relationships') OR (selector_relation_name='zasp_inventory_identity_rules') OR (selector_relation_name='zasp_inventory_identity_bindings') OR (selector_relation_name='zasp_projection_work') OR (selector_relation_name='zasp_discovery_snapshot_inputs') OR (selector_relation_name='zasp_discovery_snapshot_projection_items'))))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker:projected62:table'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','kind',fact->'kind','name',fact->'name','owner',fact->'owner','persistence',fact->'persistence','row_security',fact->'row_security') AS fact FROM direct_relation WHERE ((namespace='zasp_ordered_public62'))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker:projected68:table'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','kind',fact->'kind','name',fact->'name','owner',fact->'owner','persistence',fact->'persistence','row_security',fact->'row_security') AS fact FROM direct_relation WHERE ((namespace='zasp_temporal68'))
UNION ALL
SELECT 'foreign_key_trigger'::text AS kind, '['||pg_catalog.to_json('worker:projected68:foreign-key-trigger'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('argument_count',fact->'argument_count','arguments',fact->'arguments','columns_text',fact->'columns_text','constraint_relation',fact->'constraint_relation','deferrable',fact->'deferrable','deferred',fact->'deferred','enabled',fact->'enabled','event_bits',fact->'event_bits','function',fact->'function','name',fact->'name','referenced_relation',fact->'referenced_relation','relation',fact->'relation','trigger_relation',fact->'trigger_relation','when_text_or_empty',fact->'when_text_or_empty') AS fact FROM direct_foreign_key_trigger WHERE ((namespace='zasp_temporal68'))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker:projected69:table'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','kind',fact->'kind','name',fact->'name','owner',fact->'owner','persistence',fact->'persistence','row_security',fact->'row_security') AS fact FROM direct_relation WHERE ((namespace='zasp_temporal69'))
UNION ALL
SELECT 'foreign_key_trigger'::text AS kind, '['||pg_catalog.to_json('worker:projected69:foreign-key-trigger'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('argument_count',fact->'argument_count','arguments',fact->'arguments','columns_text',fact->'columns_text','constraint_relation',fact->'constraint_relation','deferrable',fact->'deferrable','deferred',fact->'deferred','enabled',fact->'enabled','event_bits',fact->'event_bits','function',fact->'function','name',fact->'name','referenced_relation',fact->'referenced_relation','relation',fact->'relation','trigger_relation',fact->'trigger_relation','when_text_or_empty',fact->'when_text_or_empty') AS fact FROM direct_foreign_key_trigger WHERE ((namespace='zasp_temporal69'))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker:projected72:table'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','kind',fact->'kind','name',fact->'name','owner',fact->'owner','persistence',fact->'persistence','row_security',fact->'row_security') AS fact FROM direct_relation WHERE ((namespace='zasp_temporal72'))
UNION ALL
SELECT 'foreign_key_trigger'::text AS kind, '['||pg_catalog.to_json('worker:projected72:foreign-key-trigger'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('argument_count',fact->'argument_count','arguments',fact->'arguments','columns_text',fact->'columns_text','constraint_relation',fact->'constraint_relation','deferrable',fact->'deferrable','deferred',fact->'deferred','enabled',fact->'enabled','event_bits',fact->'event_bits','function',fact->'function','name',fact->'name','referenced_relation',fact->'referenced_relation','relation',fact->'relation','trigger_relation',fact->'trigger_relation','when_text_or_empty',fact->'when_text_or_empty') AS fact FROM direct_foreign_key_trigger WHERE ((namespace='zasp_temporal72'))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker:projected78:table'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','kind',fact->'kind','name',fact->'name','owner',fact->'owner','persistence',fact->'persistence','row_security',fact->'row_security') AS fact FROM direct_relation WHERE ((namespace='zasp_temporal78'))
UNION ALL
SELECT 'foreign_key_trigger'::text AS kind, '['||pg_catalog.to_json('worker:projected78:foreign-key-trigger'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('argument_count',fact->'argument_count','arguments',fact->'arguments','columns_text',fact->'columns_text','constraint_relation',fact->'constraint_relation','deferrable',fact->'deferrable','deferred',fact->'deferred','enabled',fact->'enabled','event_bits',fact->'event_bits','function',fact->'function','name',fact->'name','referenced_relation',fact->'referenced_relation','relation',fact->'relation','trigger_relation',fact->'trigger_relation','when_text_or_empty',fact->'when_text_or_empty') AS fact FROM direct_foreign_key_trigger WHERE ((namespace='zasp_temporal78'))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected24:2'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','name',fact->'name','owner',fact->'owner','row_security',fact->'row_security') AS fact FROM direct_relation WHERE (((namespace='public') AND ((selector_name='zasp_security_agent_temporary_policy_targets') AND ((selector_relation_kind='r') OR (selector_relation_kind='i')))))
UNION ALL
SELECT 'column_name'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected24:3'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('default_text_or_empty',fact->'default_text_or_empty','generated',fact->'generated','identity',fact->'identity','name',fact->'name','not_null',fact->'not_null','type_identity',fact->'type_identity') AS fact FROM direct_column_name WHERE ((selector_relation='public.zasp_security_agent_temporary_policy_targets'))
UNION ALL
SELECT 'constraint'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected24:4'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('constraint_type',fact->'constraint_type','deferrable',fact->'deferrable','deferred',fact->'deferred','definition_pretty',fact->'definition_pretty','name',fact->'name','validated',fact->'validated') AS fact FROM direct_constraint WHERE ((selector_relation='public.zasp_security_agent_temporary_policy_targets'))
UNION ALL
SELECT 'index'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected24:5'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','name',fact->'name','primary',fact->'primary','ready',fact->'ready','unique',fact->'unique','valid',fact->'valid') AS fact FROM direct_index WHERE ((((selector_relation='public.zasp_runtime_gateway_events') AND (selector_name='zasp_runtime_gateway_events_session_v24_idx')) OR (selector_relation='public.zasp_security_agent_temporary_policy_targets')))
UNION ALL
SELECT 'constraint'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected24:7'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition_pretty',fact->'definition_pretty','name',fact->'name','validated',fact->'validated') AS fact FROM direct_constraint WHERE (((selector_relation='public.zasp_security_agent_definitions') AND (selector_name='zasp_security_agent_session_isolation_supervised_check')))
UNION ALL
SELECT 'role'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:2'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('bypass_rls',fact->'bypass_rls','create_db',fact->'create_db','create_role',fact->'create_role','inherit',fact->'inherit','login',fact->'login','name',fact->'name','replication',fact->'replication','superuser',fact->'superuser') AS fact FROM direct_role WHERE (((selector_name='zasp_recovery_worker') OR (selector_name='zasp_recovery_outbox_worker')))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:4'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','name',fact->'name','owner',fact->'owner','row_security',fact->'row_security') AS fact FROM direct_relation WHERE (((namespace='public') AND ((selector_name LIKE 'zasp_recovery_%') AND ((selector_relation_kind='r') OR (selector_relation_kind='i')))))
UNION ALL
SELECT 'class_index'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:5'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','name',fact->'name') AS fact FROM direct_class_index WHERE (((namespace='public') AND ((selector_name LIKE 'zasp_recovery_%') AND (selector_relation_kind='i'))))
UNION ALL
SELECT 'column_name'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:6'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('default_text_or_empty',fact->'default_text_or_empty','name',fact->'name','not_null',fact->'not_null','relation_name',fact->'relation_name','type_identity',fact->'type_identity') AS fact FROM direct_column_name WHERE (((namespace='public') AND (selector_relation_name LIKE 'zasp_recovery_%')))
UNION ALL
SELECT 'constraint'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:7'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('constraint_type',fact->'constraint_type','definition_pretty',fact->'definition_pretty','name',fact->'name','relation_name',fact->'relation_name','validated',fact->'validated') AS fact FROM direct_constraint WHERE ((selector_relation_name LIKE 'zasp_recovery_%'))
UNION ALL
SELECT 'column_all'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:8'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('default_text_or_empty',fact->'default_text_or_empty','name',fact->'name','not_null',fact->'not_null','relation_name',fact->'relation_name','type_identity',fact->'type_identity') AS fact FROM direct_column_all WHERE (((namespace='public') AND ((selector_relation_name='zasp_runtime_gateway_events') AND (selector_name='policy_ids'))))
UNION ALL
SELECT 'constraint'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:9'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('constraint_type',fact->'constraint_type','definition_pretty',fact->'definition_pretty','name',fact->'name','relation_name',fact->'relation_name','validated',fact->'validated') AS fact FROM direct_constraint WHERE (((selector_relation_name='zasp_runtime_gateway_events') AND (selector_name='zasp_runtime_gateway_events_policy_ids_v27_ck')))
UNION ALL
SELECT 'index'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:10'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','name',fact->'name','owner',fact->'owner','primary',fact->'primary','ready',fact->'ready','unique',fact->'unique','valid',fact->'valid') AS fact FROM direct_index WHERE (((selector_relation='public.zasp_runtime_gateway_events') AND ((selector_name='zasp_runtime_gateway_events_policy_ids_v27_idx') OR (selector_name='zasp_runtime_gateway_events_policy_history_v27_idx'))))
UNION ALL
SELECT 'policy'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:11'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('check',fact->'check','name',fact->'name','permissive',fact->'permissive','relation_name',fact->'relation_name','using',fact->'using') AS fact FROM direct_policy WHERE ((selector_relation_name LIKE 'zasp_recovery_%'))
UNION ALL
SELECT 'trigger'::text AS kind, '['||pg_catalog.to_json('worker-edge:gateway_projected27:12'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition_pretty',fact->'definition_pretty','name',fact->'name','relation_name',fact->'relation_name') AS fact FROM direct_trigger WHERE (((namespace='public') AND (selector_name LIKE '%_recovery_hold'))) AND NOT internal
UNION ALL
SELECT 'role'::text AS kind, '['||pg_catalog.to_json('worker-edge:ordered_projected28:2'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('bypass_rls',fact->'bypass_rls','create_db',fact->'create_db','create_role',fact->'create_role','inherit',fact->'inherit','login',fact->'login','name',fact->'name','replication',fact->'replication','superuser',fact->'superuser') AS fact FROM direct_role WHERE ((selector_name='zasp_policy_deployment_worker'))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker-edge:ordered_projected28:4'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','name',fact->'name','owner',fact->'owner','row_security',fact->'row_security') AS fact FROM direct_relation WHERE (((namespace='public') AND ((selector_name LIKE 'zasp_policy_deployment_%') AND ((selector_relation_kind='r') OR (selector_relation_kind='i')))))
UNION ALL
SELECT 'column_name'::text AS kind, '['||pg_catalog.to_json('worker-edge:ordered_projected28:5'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('default_text_or_empty',fact->'default_text_or_empty','generated',fact->'generated','identity',fact->'identity','name',fact->'name','not_null',fact->'not_null','relation_name',fact->'relation_name','type_identity',fact->'type_identity') AS fact FROM direct_column_name WHERE (((namespace='public') AND ((selector_relation_name LIKE 'zasp_policy_deployment_%') OR ((selector_relation_name='zasp_security_agent_temporary_policy_targets') OR (selector_relation_name='zasp_security_agent_session_policy_targets')))))
UNION ALL
SELECT 'class_index'::text AS kind, '['||pg_catalog.to_json('worker-edge:ordered_projected28:6'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','name',fact->'name') AS fact FROM direct_class_index WHERE (((namespace='public') AND ((selector_name LIKE 'zasp_policy_deployment_%') AND (selector_relation_kind='i'))))
UNION ALL
SELECT 'constraint'::text AS kind, '['||pg_catalog.to_json('worker-edge:ordered_projected28:7'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('constraint_type',fact->'constraint_type','definition_pretty',fact->'definition_pretty','name',fact->'name','relation_name',fact->'relation_name','validated',fact->'validated') AS fact FROM direct_constraint WHERE ((selector_relation_name LIKE 'zasp_policy_deployment_%'))
UNION ALL
SELECT 'policy'::text AS kind, '['||pg_catalog.to_json('worker-edge:ordered_projected28:8'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('check',fact->'check','name',fact->'name','permissive',fact->'permissive','relation_name',fact->'relation_name','using',fact->'using') AS fact FROM direct_policy WHERE ((selector_relation_name LIKE 'zasp_policy_deployment_%'))
UNION ALL
SELECT 'trigger'::text AS kind, '['||pg_catalog.to_json('worker-edge:ordered_projected28:9'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition_pretty',fact->'definition_pretty','name',fact->'name','relation_name',fact->'relation_name') AS fact FROM direct_trigger WHERE (((selector_name LIKE '%policy_deployment%') OR (selector_name LIKE '%policy_sequence') OR (selector_name LIKE '%policy_verify')))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected40:3'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','name',fact->'name','owner',fact->'owner','row_security',fact->'row_security') AS fact FROM direct_relation WHERE (((identity='public.zasp_runtime_session_events') OR (identity='public.zasp_runtime_session_projection_receipts')))
UNION ALL
SELECT 'constraint'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected40:4'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','name',fact->'name','validated',fact->'validated') AS fact FROM direct_constraint WHERE (((selector_relation='public.zasp_runtime_session_events') OR (selector_relation='public.zasp_runtime_session_projection_receipts')))
UNION ALL
SELECT 'column_name'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected40:5'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('name',fact->'name','not_null',fact->'not_null','relation',fact->'relation','type',fact->'type') AS fact FROM direct_column_name WHERE (((selector_relation='public.zasp_runtime_session_events') OR (selector_relation='public.zasp_runtime_session_projection_receipts')))
UNION ALL
SELECT 'policy_view'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected40:6'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('check',fact->'check','command',fact->'command','name',fact->'name','namespace_name',fact->'namespace_name','roles_text',fact->'roles_text','table_name',fact->'table_name','using',fact->'using') AS fact FROM direct_policy_view WHERE (((namespace='public') AND ((selector_table_name='zasp_runtime_session_events') OR (selector_table_name='zasp_runtime_session_projection_receipts'))))
UNION ALL
SELECT 'index_view'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected40:7'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','name',fact->'name') AS fact FROM direct_index_view WHERE (((namespace='public') AND ((selector_table_name='zasp_runtime_session_events') OR (selector_table_name='zasp_runtime_session_projection_receipts'))))
UNION ALL
SELECT 'routine'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_binding:3'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','config_text_or_empty',fact->'config_text_or_empty','definition',fact->'definition','identity_arguments',fact->'identity_arguments','name',fact->'name','owner',fact->'owner','security_definer',fact->'security_definer') AS fact FROM direct_routine WHERE (((namespace='public') AND ((selector_name='zasp_runtime_claim_session_stage_compatible') OR (selector_name='zasp_runtime_session_claim_version_guard') OR (selector_name='zasp_runtime_claim_projection_v2') OR (selector_name='zasp_runtime_claim_completion_v2'))))
UNION ALL
SELECT 'trigger'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_binding:4'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition_pretty',fact->'definition_pretty','enabled',fact->'enabled','name',fact->'name') AS fact FROM direct_trigger WHERE (((selector_relation='public.zasp_runtime_stage_work') AND (selector_name='zasp_runtime_session_claim_version')))
UNION ALL
SELECT 'routine'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_binding:5'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','config_text_or_empty',fact->'config_text_or_empty','definition',fact->'definition','identity_arguments',fact->'identity_arguments','name',fact->'name','owner',fact->'owner','security_definer',fact->'security_definer') AS fact FROM direct_routine WHERE ((identity='public.zasp_runtime_finish_sandbox_session_projection(text,text,text,text,bigint,text,text,integer,bytea,text,text,bytea,text,text,bytea,text,integer,bytea)'))
UNION ALL
SELECT 'column_name'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_binding:6'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','name',fact->'name') AS fact FROM direct_column_name WHERE ((selector_relation='public.zasp_runtime_session_events'))
UNION ALL
SELECT 'routine'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_binding:7'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','config_text_or_empty',fact->'config_text_or_empty','definition',fact->'definition','identity_arguments',fact->'identity_arguments','name',fact->'name','owner',fact->'owner','security_definer',fact->'security_definer') AS fact FROM direct_routine WHERE (((identity::regprocedure='public.zasp_runtime_sandbox_session_event_page(text,text,text,text,text,timestamptz,text,integer)'::regprocedure) OR (identity::regprocedure='public.zasp_runtime_sandbox_session_event_get(text,text,text,text,text,text)'::regprocedure)))
UNION ALL
SELECT 'routine'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_binding:8'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','config_text_or_empty',fact->'config_text_or_empty','definition',fact->'definition','identity_arguments',fact->'identity_arguments','name',fact->'name','owner',fact->'owner','security_definer',fact->'security_definer') AS fact FROM direct_routine WHERE (((namespace='public') AND ((selector_name='zasp_runtime_claim_stage_sandbox_compatible') OR (selector_name='zasp_runtime_claim_correlation_v3') OR (selector_name='zasp_runtime_freeze_sandbox_candidates') OR (selector_name='zasp_production_runtime_sandbox_binding_security_ready') OR (selector_name='zasp_production_runtime_sandbox_binding_readiness') OR (selector_name='zasp_production_runtime_correlation_routing_readiness_v49') OR (selector_name='zasp_production_runtime_candidate_authority_live_fingerprint'))))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_search:4'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','forced_row_security',fact->'forced_row_security','name',fact->'name','owner',fact->'owner','row_security',fact->'row_security') AS fact FROM direct_relation WHERE ((identity='public.zasp_runtime_sandbox_search_outbox'))
UNION ALL
SELECT 'constraint'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_search:5'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','name',fact->'name','validated',fact->'validated') AS fact FROM direct_constraint WHERE ((selector_relation='public.zasp_runtime_sandbox_search_outbox'))
UNION ALL
SELECT 'column_name'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_search:6'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl_text_or_empty',fact->'acl_text_or_empty','default_text_or_empty',fact->'default_text_or_empty','name',fact->'name','not_null',fact->'not_null','type',fact->'type') AS fact FROM direct_column_name WHERE ((selector_relation='public.zasp_runtime_sandbox_search_outbox'))
UNION ALL
SELECT 'policy_view'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_search:7'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('check',fact->'check','command',fact->'command','name',fact->'name','roles_text',fact->'roles_text','using',fact->'using') AS fact FROM direct_policy_view WHERE (((namespace='public') AND (selector_table_name='zasp_runtime_sandbox_search_outbox')))
UNION ALL
SELECT 'index_view'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_search:8'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','name',fact->'name') AS fact FROM direct_index_view WHERE (((namespace='public') AND (selector_table_name='zasp_runtime_sandbox_search_outbox')))
UNION ALL
SELECT 'trigger'::text AS kind, '['||pg_catalog.to_json('worker-edge:runtime_projected50_search:9'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','enabled',fact->'enabled','name',fact->'name','relation',fact->'relation') AS fact FROM direct_trigger WHERE (((selector_relation='public.zasp_runtime_session_projection_receipts') OR (selector_relation='public.zasp_runtime_sandbox_search_outbox') OR (selector_relation='public.zasp_runtime_session_search_outbox'))) AND NOT internal
