WITH direct_column AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(a.attnum)::text||']' AS identity, n.nspname::text AS namespace, a.attname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('acl',a.attacl::text,'default',pg_catalog.pg_get_expr(d.adbin,d.adrelid),'generated',a.attgenerated::text,'identity',a.attidentity::text,'name',a.attname::text,'not_null',a.attnotnull,'position',a.attnum,'type',pg_catalog.format_type(a.atttypid,a.atttypmod)) AS fact FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_catalog.pg_attrdef d ON (d.adrelid,d.adnum)=(a.attrelid,a.attnum) WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false)) AND (a.attnum>0 AND NOT a.attisdropped)),
direct_constraint AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(k.conname::text)::text||']' AS identity, n.nspname::text AS namespace, k.conname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('constraint_type',k.contype::text,'deferrable',k.condeferrable,'deferred',k.condeferred,'definition',pg_catalog.pg_get_constraintdef(k.oid),'no_inherit',k.connoinherit,'validated',k.convalidated) AS fact FROM pg_catalog.pg_constraint k JOIN pg_catalog.pg_class c ON c.oid=k.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_index AS MATERIALIZED (SELECT i.indexrelid::regclass::text AS identity, n.nspname::text AS namespace, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('definition',pg_catalog.pg_get_indexdef(i.indexrelid),'exclusion',i.indisexclusion,'live',i.indislive,'primary',i.indisprimary,'ready',i.indisready,'unique',i.indisunique,'valid',i.indisvalid) AS fact FROM pg_catalog.pg_index i JOIN pg_catalog.pg_class c ON c.oid=i.indrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_class index_class ON index_class.oid=i.indexrelid WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_namespace AS MATERIALIZED (SELECT n.nspname::text AS identity, n.nspname::text AS namespace, n.nspname::text AS selector_name, pg_catalog.jsonb_build_object('acl',n.nspacl::text,'owner',n.nspowner::regrole::text) AS fact FROM pg_catalog.pg_namespace n WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_policy AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(p.polname::text)::text||']' AS identity, n.nspname::text AS namespace, p.polname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('check',pg_catalog.pg_get_expr(p.polwithcheck,p.polrelid),'command',p.polcmd::text,'permissive',p.polpermissive,'roles',p.polroles::regrole[]::text,'using',pg_catalog.pg_get_expr(p.polqual,p.polrelid)) AS fact FROM pg_catalog.pg_policy p JOIN pg_catalog.pg_class c ON c.oid=p.polrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_relation AS MATERIALIZED (SELECT c.oid::regclass::text AS identity, n.nspname::text AS namespace, c.relname::text AS selector_name, c.relkind::text AS selector_relation_kind, pg_catalog.jsonb_build_object('acl',c.relacl::text,'forced_row_security',c.relforcerowsecurity,'kind',c.relkind::text,'options',c.reloptions,'owner',c.relowner::regrole::text,'row_security',c.relrowsecurity) AS fact FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_rewrite AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(r.rulename::text)::text||']' AS identity, n.nspname::text AS namespace, r.rulename::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, pg_catalog.jsonb_build_object('definition',pg_catalog.pg_get_ruledef(r.oid),'enabled',r.ev_enabled::text,'event',r.ev_type::text,'instead',r.is_instead) AS fact FROM pg_catalog.pg_rewrite r JOIN pg_catalog.pg_class c ON c.oid=r.ev_class JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_routine AS MATERIALIZED (SELECT p.oid::regprocedure::text AS identity, n.nspname::text AS namespace, p.proname::text AS selector_name, pg_catalog.jsonb_build_object('acl',p.proacl::text,'all_types',p.proallargtypes::regtype[]::text[],'argument_defaults',p.proargdefaults::text,'argument_modes',p.proargmodes::text[],'argument_names',p.proargnames,'binary',p.probin,'config',p.proconfig,'cost',p.procost,'default_count',p.pronargdefaults,'input_types',ARRAY(SELECT args.unnest::regtype::text FROM pg_catalog.unnest(p.proargtypes) WITH ORDINALITY AS args ORDER BY args.ordinality),'kind',p.prokind::text,'language',l.lanname::text,'leakproof',p.proleakproof,'owner',p.proowner::regrole::text,'parallel',p.proparallel::text,'result_type',p.prorettype::regtype::text,'returns_set',p.proretset,'rows',p.prorows,'security_definer',p.prosecdef,'source',p.prosrc::text,'sql_body',p.prosqlbody::text,'strict',p.proisstrict,'support',CASE WHEN p.prosupport=0 THEN NULL ELSE p.prosupport::regprocedure::text END,'transforms',p.protrftypes::regtype[]::text[],'variadic_type',CASE WHEN p.provariadic=0 THEN NULL ELSE p.provariadic::regtype::text END,'volatility',p.provolatile::text) AS fact FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace JOIN pg_catalog.pg_language l ON l.oid=p.prolang WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_trigger AS MATERIALIZED (SELECT '['||pg_catalog.to_json(c.oid::regclass::text)::text||','||pg_catalog.to_json(t.tgname::text)::text||']' AS identity, n.nspname::text AS namespace, t.tgname::text AS selector_name, c.oid::regclass::text AS selector_relation, c.relname::text AS selector_relation_name, t.tgfoid::regprocedure::text AS selector_function, t.tgisinternal AS internal, pg_catalog.jsonb_build_object('arguments',pg_catalog.encode(t.tgargs,'hex'),'deferrable',t.tgdeferrable,'deferred',t.tginitdeferred,'definition',pg_catalog.pg_get_triggerdef(t.oid),'enabled',t.tgenabled::text,'event_bits',t.tgtype,'function',t.tgfoid::regprocedure::text,'internal',t.tgisinternal,'new_table',t.tgnewtable::text,'old_table',t.tgoldtable::text,'when',pg_catalog.pg_get_expr(t.tgqual,t.tgrelid)) AS fact FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_type AS MATERIALIZED (SELECT t.oid::regtype::text AS identity, n.nspname::text AS namespace, pg_catalog.jsonb_build_object('acl',t.typacl::text,'alignment',t.typalign::text,'analyze',CASE WHEN t.typanalyze=0 THEN NULL ELSE t.typanalyze::regprocedure::text END,'array',CASE WHEN t.typarray=0 THEN NULL ELSE t.typarray::regtype::text END,'base',CASE WHEN t.typbasetype=0 THEN NULL ELSE t.typbasetype::regtype::text END,'by_value',t.typbyval,'category',t.typcategory::text,'collation',CASE WHEN t.typcollation=0 THEN NULL ELSE t.typcollation::regcollation::text END,'default',t.typdefault::text,'defined',t.typisdefined,'delimiter',t.typdelim::text,'dimensions',t.typndims,'element',CASE WHEN t.typelem=0 THEN NULL ELSE t.typelem::regtype::text END,'input',t.typinput::regprocedure::text,'kind',t.typtype::text,'length',t.typlen,'not_null',t.typnotnull,'output',t.typoutput::regprocedure::text,'owner',t.typowner::regrole::text,'preferred',t.typispreferred,'receive',CASE WHEN t.typreceive=0 THEN NULL ELSE t.typreceive::regprocedure::text END,'relation',CASE WHEN t.typrelid=0 THEN NULL ELSE t.typrelid::regclass::text END,'send',CASE WHEN t.typsend=0 THEN NULL ELSE t.typsend::regprocedure::text END,'storage',t.typstorage::text,'subscript',CASE WHEN t.typsubscript=0 THEN NULL ELSE t.typsubscript::regprocedure::text END,'type_modifier',t.typtypmod) AS fact FROM pg_catalog.pg_type t JOIN pg_catalog.pg_namespace n ON n.oid=t.typnamespace WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false))),
direct_view AS MATERIALIZED (SELECT c.oid::regclass::text AS identity, n.nspname::text AS namespace, c.relname::text AS selector_name, c.relkind::text AS selector_relation_kind, pg_catalog.jsonb_build_object('acl',c.relacl::text,'definition',pg_catalog.pg_get_viewdef(c.oid),'options',c.reloptions,'owner',c.relowner::regrole::text) AS fact FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE ((n.nspname::text IN('zasp_authorization80_ordered_current') OR false)) AND (c.relkind IN('v','m')))
SELECT 'routine'::text AS kind, '['||pg_catalog.to_json('private-routines'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl',fact->'acl','all_types',fact->'all_types','argument_defaults',fact->'argument_defaults','argument_modes',fact->'argument_modes','argument_names',fact->'argument_names','binary',fact->'binary','config',fact->'config','cost',fact->'cost','default_count',fact->'default_count','input_types',fact->'input_types','kind',fact->'kind','language',fact->'language','leakproof',fact->'leakproof','owner',fact->'owner','parallel',fact->'parallel','result_type',fact->'result_type','returns_set',fact->'returns_set','rows',fact->'rows','security_definer',fact->'security_definer','source',fact->'source','sql_body',fact->'sql_body','strict',fact->'strict','support',fact->'support','transforms',fact->'transforms','variadic_type',fact->'variadic_type','volatility',fact->'volatility') AS fact FROM direct_routine WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'namespace'::text AS kind, '['||pg_catalog.to_json('private-namespace'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl',fact->'acl','owner',fact->'owner') AS fact FROM direct_namespace WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'relation'::text AS kind, '['||pg_catalog.to_json('private-relation'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl',fact->'acl','forced_row_security',fact->'forced_row_security','kind',fact->'kind','options',fact->'options','owner',fact->'owner','row_security',fact->'row_security') AS fact FROM direct_relation WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'column'::text AS kind, '['||pg_catalog.to_json('private-column'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl',fact->'acl','default',fact->'default','generated',fact->'generated','identity',fact->'identity','name',fact->'name','not_null',fact->'not_null','position',fact->'position','type',fact->'type') AS fact FROM direct_column WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'constraint'::text AS kind, '['||pg_catalog.to_json('private-constraint'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('constraint_type',fact->'constraint_type','deferrable',fact->'deferrable','deferred',fact->'deferred','definition',fact->'definition','no_inherit',fact->'no_inherit','validated',fact->'validated') AS fact FROM direct_constraint WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'index'::text AS kind, '['||pg_catalog.to_json('private-index'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','exclusion',fact->'exclusion','live',fact->'live','primary',fact->'primary','ready',fact->'ready','unique',fact->'unique','valid',fact->'valid') AS fact FROM direct_index WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'policy'::text AS kind, '['||pg_catalog.to_json('private-policy'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('check',fact->'check','command',fact->'command','permissive',fact->'permissive','roles',fact->'roles','using',fact->'using') AS fact FROM direct_policy WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'trigger'::text AS kind, '['||pg_catalog.to_json('private-trigger'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('arguments',fact->'arguments','deferrable',fact->'deferrable','deferred',fact->'deferred','definition',fact->'definition','enabled',fact->'enabled','event_bits',fact->'event_bits','function',fact->'function','internal',fact->'internal','new_table',fact->'new_table','old_table',fact->'old_table','when',fact->'when') AS fact FROM direct_trigger WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'view'::text AS kind, '['||pg_catalog.to_json('private-view'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl',fact->'acl','definition',fact->'definition','options',fact->'options','owner',fact->'owner') AS fact FROM direct_view WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'rewrite'::text AS kind, '['||pg_catalog.to_json('private-rewrite'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('definition',fact->'definition','enabled',fact->'enabled','event',fact->'event','instead',fact->'instead') AS fact FROM direct_rewrite WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
UNION ALL
SELECT 'type'::text AS kind, '['||pg_catalog.to_json('private-type'::text)::text||','||pg_catalog.to_json(identity)::text||']' AS identity, pg_catalog.jsonb_build_object('acl',fact->'acl','alignment',fact->'alignment','analyze',fact->'analyze','array',fact->'array','base',fact->'base','by_value',fact->'by_value','category',fact->'category','collation',fact->'collation','default',fact->'default','defined',fact->'defined','delimiter',fact->'delimiter','dimensions',fact->'dimensions','element',fact->'element','input',fact->'input','kind',fact->'kind','length',fact->'length','not_null',fact->'not_null','output',fact->'output','owner',fact->'owner','preferred',fact->'preferred','receive',fact->'receive','relation',fact->'relation','send',fact->'send','storage',fact->'storage','subscript',fact->'subscript','type_modifier',fact->'type_modifier') AS fact FROM direct_type WHERE ((namespace IN('zasp_authorization80_ordered_current') OR false))
